### ISSUE TITLE
Bowtie2-2.2.9 run time

### ISSUE THREAD

**Issue by MGCBrown** [BenLangmead/bowtie2#101]
Hello, 

I'm using bowtie2 to align ~200 million sequence read-pairs to a transcriptome assembled with Trinity. I used this command:
bowtie2 --local --no-unal -x Trinity.fasta -q -1 OMNR_50254_1_BRAIN_R1_val_1.fq,CC1_1_BRAIN_R1_val_1.fq,6525_1_BRAIN_R1_val_1.fq,25428_BRAIN_R1_val_1.fq -2 OMNR_50254_1_BRAIN_R2_val_2.fq,CC1_1_BRAIN_R2_val_2.fq,6525_1_BRAIN_R2_val_2.fq,25428_BRAIN_R2_val_2.fq  | samtools view -Sb - | samtools sort -no - - > bowtie2.nameSorted.bam

I was wondering how long I should expect bowtie2 to run. It has been running for ~48 hours now, and I have 128 BAM output files (-.0000.bam to -.0127.bam). How many intermediate output files should I expect to be created?

Any info would be very appreciated. I realize I should have added the multithreading parameter "-@" to speed up the process, but I don't want to kill this job as it has been running a couple of days now.

Thanks, 

Mike

**Comment by BenLangmead** [comment]
Did this ever complete?  It's hard for us to predict or say whether the performance is surprising from afar.  Much better is to supply an example where you think it may be taking too long and we can investigate in detail.

**Comment by BenLangmead** [comment]
Closing for now as we haven't heard back
