### ISSUE TITLE
Bowtie 2 version 2.2.9 error on UBUNTU 16.10

### ISSUE THREAD

**Issue by shekas3** [BenLangmead/bowtie2#103]
Hi, the latest version of bowtie2 doesn't support ubuntu 16.10? I found this error similar to some other people that posted online. The issue was solved when I ran on ubuntu 16.4

here is the error : 
Segmentation fault (core dumped)
(ERR): bowtie2-align exited with value 139

**Comment by BenLangmead** [comment]
The latest released version is 2.3.1.  Do you see this same issue with that version?

**Comment by shekas3** [comment]
I installed it using apt-get. I thought that's the latest released version. I'll install it manually and let you know about this issue.
Thanks,
Sharok

**Comment by BenLangmead** [comment]
Closing as we haven't heard back in a while.  Feel free to reopen if it's still an issue.
