### ISSUE TITLE
N parameter doesn't make sense

### ISSUE THREAD

**Issue by linjc2011** [BenLangmead/bowtie2#104]
Hi. I test on Bowtie2 2.3 version, 2.2.6 version and very old version 1.6.
N parameter doesn't works for 2.2 and 2.3 version.
The mapping rates are the same when using N=0 or N=1.
What's the problem?
Thanks.

**Comment by BenLangmead** [comment]
We will look into this.  See also #94

**Comment by BenLangmead** [comment]
I see a difference:

```
13:00:29-langmead~/software/bowtie2-2.2.6$ ./bowtie2 -x example/index/lambda_virus -U example/reads/reads_1.fq > /dev/null -t -N 0
Time loading reference: 00:00:00
Time loading forward index: 00:00:00
Time loading mirror index: 00:00:00
Multiseed full-index search: 00:00:01
10000 reads; of these:
  10000 (100.00%) were unpaired; of these:
    596 (5.96%) aligned 0 times
    9404 (94.04%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
94.04% overall alignment rate
Time searching: 00:00:01
Overall time: 00:00:01
13:00:32-langmead~/software/bowtie2-2.2.6$ ./bowtie2 -x example/index/lambda_virus -U example/reads/reads_1.fq > /dev/null -t -N 1
Time loading reference: 00:00:00
Time loading forward index: 00:00:00
Time loading mirror index: 00:00:00
Multiseed full-index search: 00:00:01
10000 reads; of these:
  10000 (100.00%) were unpaired; of these:
    342 (3.42%) aligned 0 times
    9658 (96.58%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
96.58% overall alignment rate
Time searching: 00:00:01
Overall time: 00:00:01
```

I see this for v2.2.6, v2.2.9 and v2.3.1.  Could you share an example where there's no difference between `-N 0` and `-N 1`?

**Comment by linjc2011** [comment]
Hi Ben,
Here is my result. The problem is still there.

>bowtie2 -L 25 -x tair10 -U /home/lin/20170206/col01_1.fq > /home/lin/20170206/col_N0test -t -N 0
Multiseed full-index search: 00:11:22
14446415 reads; of these:
  14446415 (100.00%) were unpaired; of these:
    8841560 (61.20%) aligned 0 times
    4780267 (33.09%) aligned exactly 1 time
    824588 (5.71%) aligned >1 times
38.80% overall alignment rate
Time searching: 00:11:24
Overall time: 00:11:24

>bowtie2 -L 25 -x tair10 -U /home/lin/20170206/col01_1.fq > /home/lin/20170206/col_N1test -t -N 1
Multiseed full-index search: 00:10:42
14446415 reads; of these:
  14446415 (100.00%) were unpaired; of these:
    8841560 (61.20%) aligned 0 times
    4780267 (33.09%) aligned exactly 1 time
    824588 (5.71%) aligned >1 times
38.80% overall alignment rate
Time searching: 00:10:42
Overall time: 00:10:42

**Comment by BenLangmead** [comment]
Yes, I agree.  Thank you for the example.

It looks like the problem may occur when both `-L` and `-N` are specified.  Here is an example.  The problem is clear since the alignment rate for the final example should match the earlier example with `-N 1`.  I.e. it should be 96.58%.

```
21:54:15-langmead~/git/bowtie2 (alt_loci)$ ./bowtie2 -x example/index/lambda_virus -U example/reads/reads_1.fq > /dev/null
10000 reads; of these:
  10000 (100.00%) were unpaired; of these:
    596 (5.96%) aligned 0 times
    9404 (94.04%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
94.04% overall alignment rate
21:54:22-langmead~/git/bowtie2 (alt_loci)$ ./bowtie2 -x example/index/lambda_virus -U example/reads/reads_1.fq -N 0 > /dev/null
10000 reads; of these:
  10000 (100.00%) were unpaired; of these:
    596 (5.96%) aligned 0 times
    9404 (94.04%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
94.04% overall alignment rate
21:54:27-langmead~/git/bowtie2 (alt_loci)$ ./bowtie2 -x example/index/lambda_virus -U example/reads/reads_1.fq -N 1 > /dev/null
10000 reads; of these:
  10000 (100.00%) were unpaired; of these:
    342 (3.42%) aligned 0 times
    9658 (96.58%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
96.58% overall alignment rate
21:54:30-langmead~/git/bowtie2 (alt_loci)$ ./bowtie2 -x example/index/lambda_virus -U example/reads/reads_1.fq -L 22 -N 0 > /dev/null
10000 reads; of these:
  10000 (100.00%) were unpaired; of these:
    596 (5.96%) aligned 0 times
    9404 (94.04%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
94.04% overall alignment rate
21:54:35-langmead~/git/bowtie2 (alt_loci)$ ./bowtie2 -x example/index/lambda_virus -U example/reads/reads_1.fq -L 22 -N 1 > /dev/null
10000 reads; of these:
  10000 (100.00%) were unpaired; of these:
    596 (5.96%) aligned 0 times
    9404 (94.04%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
94.04% overall alignment rate
```

**Comment by linjc2011** [comment]
Thanks, Ben. So I can not use -L when I use -N option?

**Comment by BenLangmead** [comment]
In my example, using `-L 22` and `-N 1` together seemed to force `-N` to be 0.  This is all I know right now.  It's probably a bug, and we will investigate.

**Comment by ch4rr0** [comment]
I have not yet found the root of the issue, but it may not be as complicated as we think. By simply reordering the parameters we do get the desired output. Pay attention to the alignment rate below which was 94.04 in @BenLangmead's output, but is now 96.58 below.
```
(master) $ ./bowtie2 -N1 -L22 -x example/index/lambda_virus -U example/reads/reads_1.fq -S /dev/null
10000 reads; of these:
  10000 (100.00%) were unpaired; of these:
    342 (3.42%) aligned 0 times
    9658 (96.58%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
96.58% overall alignment rate
```

**Comment by BenLangmead** [comment]
We see the issue and think we know how to fix it.  It has to do with this check:

https://github.com/BenLangmead/bowtie2/blob/72d548770b865c24dc9686ddfb51e80497310c42/bt2_search.cpp#L1283

Which only seems to be necessary because of the ability for the `SEED` key in the policy string to specify either just the # mismatches allowed, or both # mismatches and length.  When length isn't specified, it's overwritten by the default:

https://github.com/BenLangmead/bowtie2/blob/master/aligner_seed_policy.cpp#L560

At the same time, there is a separate policy string key called `SEEDLEN` that sets only the seed length.

Our idea is to specialize `SEED` so that it only sets the # mismatches.  Any place in the code that currently uses the two-argument version of `SEED`, like here:

https://github.com/BenLangmead/bowtie2/blob/master/presets.cpp#L38

...will have to be changed to specify both `SEED` and `SEEDLEN` separately.
