### ISSUE TITLE
intermittent aligning.

### ISSUE THREAD

**Issue by rlebbink** [BenLangmead/bowtie2#108]
Hi,
I am aligning a ±10GB fastq file to a reference samples.  I used to do this on my macbook pro using an terminal account quite easily, where it would run a few hours to do this. However, for some reason the same analysis now takes 2-3 days to run, I don't know why. What I can see, is that the activity in terminal seems to be intermittent. It analyses for a couple minutes, then it stops for a long time, where it occasionally 'reactivates' and starts aligning again. I have the same when analyzing on an external drive, or on the hard-drive.

Does anyone know how this can happen? And more importantly, how to fix it and keep the analysis going till complete? This would be much appreciated! This is probably not a bowtie issue, but more a terminal issue?
Cheers
RJ

**Comment by BenLangmead** [comment]
Please share the exact Bowtie 2 command are you running, preferably for a run where all input (reads, index) and output (SAM) files are on local disk.  We want to be able to rule out I/O as the culprit, and the best way to do that is have all inputs and outputs be on (fast) local disk.

**Comment by BenLangmead** [comment]
I haven't heard back and so will close this for now.  I recommend tools like `vmstat`, `iostat` and `strace` for trying to determine what is happening on the system when Bowtie 2 is stalling.
