### ISSUE TITLE
Makefile `install` target

### ISSUE THREAD

**Issue by wookietreiber** [BenLangmead/bowtie2#11]
Without, it is really hard to figure out which files are actually needed for a distribution.

**Comment by BenLangmead** [comment]
That's true!  Val and I are considering how best to address this.
Thanks,
Ben

**Comment by wookietreiber** [comment]
Writing the `install` target takes me about 15 minutes. Just give me a file list and I'll have a PR ready quickly. You can see if you like it and whether you want to merge it.
