### ISSUE TITLE
Aligning hangs using version 2.3.2

### ISSUE THREAD

**Issue by yangwu91** [BenLangmead/bowtie2#110]
Hi,
Serveral weeks ago, I used version 2.3.1 for `trinity` assembly, which hanged for weeks and no error occured. I found someone already reported an issue that version 2.3.1 with multi cores could cause job hanging. Serveral days ago I started a job with `tophat` using version 2.3.2 and it still hangs today, while another server has done the same job with both version 2.2.9 and version 2.1.0 twice. The index is 1.5Mb, and paired-end data is 5Gb for each. Any suggestions? Thanks!
Best,
Yang

**Comment by BenLangmead** [comment]
Can you give an example of a command that hangs, including input data?  We need to narrow things down before we can investigate.

**Comment by yangwu91** [comment]
I am sorry the sequencing data has not published yet,, but I'll try some other public data to see if it hangs and post here. Thanks!

**Comment by ch4rr0** [comment]
This issue was most likely due to a multi-threaded bug that was fixed as of v2.3.4. Please feel free to reopen this issue if the problem persists
