### ISSUE TITLE
Current (v2.3.2) bowtie2 install via conda results in error

### ISSUE THREAD

**Issue by tantrev** [BenLangmead/bowtie2#112]
When trying to install bowtie2 via conda, with the following command:

```
conda install -yc bioconda bowtie2=2.3.2
```

the following error results:

```
PackageNotFoundError: Dependency missing in current linux-64 channels: 
  - bowtie2 2.3.2* -> perl 5.22.0*

Close matches found; did you mean one of these?

    perl: perl-b, petl, pepr
```

**Comment by tantrev** [comment]
@FelixKrueger - the same issue also appears to happen with the latest (v0.4.3) Trim Galore!

**Comment by ewels** [comment]
Hi @tantrev,

Chiming in here as @FelixKrueger asked me to take a look. I'm not able to replicate this error - `perl` installs fine from the `conda-forge` channel:

```
The following NEW packages will be INSTALLED:

    bowtie2:    2.3.2-py27pl5.22.0_1 bioconda
    openssl:    1.0.2l-0
    perl:       5.22.0.1-0           conda-forge
    pip:        9.0.1-py27_1
    python:     2.7.13-0
    readline:   6.2-2
    setuptools: 27.2.0-py27_0
    sqlite:     3.13.0-0
    tbb:        4.4_20150728-0       bioconda
    tk:         8.5.18-0
    wheel:      0.29.0-py27_0
    zlib:       1.2.8-3
```

Do you definitely have this channel configured? See the [bioconda docs](https://bioconda.github.io/#set-up-channels).

```
conda config --add channels conda-forge
conda config --add channels defaults
conda config --add channels r
conda config --add channels bioconda
```

Generally speaking, it's better to report problems with bioconda installations on the [bioconda-recipes repo](https://github.com/bioconda/bioconda-recipes) or in the [bioconda gitter chatroom](https://gitter.im/bioconda/Lobby) as many of the tools are packaged by people who weren't involved in originally writing the tool.

Cheers,

Phil

**Comment by tantrev** [comment]
Hi @ewels,

Thank you, that fixed everything!  I'm an idiot - next time I'll hit up bioconda and actually RTFM. :P

Thanks again,
Trev

**Comment by ewels** [comment]
Great! No problem at all, it's an easy mistake to make.. :)
