### ISSUE TITLE
feature request: compressed reference

### ISSUE THREAD

**Issue by matthdsm** [BenLangmead/bowtie2#113]
Hi,

Would it be possible to build in support for compressed reference genomes? I see you already support gzipped input files, so a compressed reference could be a logical next step.

Thanks
M

**Comment by ch4rr0** [comment]
The change is in development. I won't have included in the upcoming release, but will instead release it on a separate branch soon.

**Comment by BenLangmead** [comment]
This is supported as of v2.3.3
