### ISSUE TITLE
Discriminate between a truly unique and a very repetitive, but unique looking read

### ISSUE THREAD

**Issue by FelixKrueger** [BenLangmead/bowtie2#114]
Hi Ben,

We have run into an issue where a read is reported as a unique hit (i.e. no `XS:i:` tag), but in fact the read has hundreds of different possible alignments in the genome and we suspect that most of the repetitive hits just don't pass the `--score-min L,0,-0.2` filter. Here is an example:

```
ID:bowtie2      PN:bowtie2      VN:2.3.2        CL:"/bi/apps/bowtie2/2.3.2/bowtie2-align-s --wrapper basic-0 -q -t --score-min L,0,-0.2 --ignore-quals --nofw -x /bi/scratch/Genomes/Arabidopsis/TAIR10/Bisulfite_Genome/GA_conversion/BS_GA -U read2.fastq_C_to_T.fastq"
HS3:420:C3EHMACXX:8:1101:10176:30378_1:N:0:ACCTCA       16      3_GA_converted  13591519        0       100M    *       0       0       AAAAAACAAAAAAAAAATTAATTAATATTTTAAAATCAAATTTAACTTAATATCATATATATTATTAAATATAAAAACTTAAACCACAACACAATCTTATDDDDDA5DDDDDFFFFFHGHHHHHDIJJIJJJJJHHCJJIGHIHJJJJJJJIIFJJJJJJJJJJJJJJJJJJJJIHIJJIHGGGGFGHHFFFFFFDFCC@     AS:i:-18        XN:i:0  XM:i:3  XO:i:0  XG:i:0  NM:i:3  MD:Z:41A20A27C9 YT:Z:UU
```

This produces one alignment (AS:i:-18) but has not found a valid secondary alignment yet (hence no `XS:i:` field). As a result of this the alignment is considered unique. When I increase the `-D` parameter to look harder for valid alignments the situation looks much different:

```
PG     ID:bowtie2      PN:bowtie2      VN:2.3.2        CL:"/bi/apps/bowtie2/2.3.2/bowtie2-align-s --wrapper basic-0 -q -t -D 50 --score-min L,0,-0.2 --ignore-quals --nofw -x /bi/scratch/Genomes/Arabidopsis/TAIR10/Bisulfite_Genome/GA_conversion/BS_GA -U read2.fastq_C_to_T.fastq"
HS3:420:C3EHMACXX:8:1101:10176:30378_1:N:0:ACCTCA       16      3_GA_converted  13591519        0       100M    *       0       0       AAAAAACAAAAAAAAAATTAATTAATATTTTAAAATCAAATTTAACTTAATATCATATATATTATTAAATATAAAAACTTAAACCACAACACAATCTTATDDDDDA5DDDDDFFFFFHGHHHHHDIJJIJJJJJHHCJJIGHIHJJJJJJJIIFJJJJJJJJJJJJJJJJJJJJIHIJJIHGGGGFGHHFFFFFFDFCC@     AS:i:-18        XS:i:-18        XN:i:0  XM:i:3  XO:i:0  XG:i:0  NM:i:3  MD:Z:41A20A27C9 YT:Z:UU
```

With more reseeding attempts both `AS:i:-18` and `XS:i:-18` are reported, and the read consequently is ambiguous. (using Bowtie2 with `-a --score-min L,0,-0.6` produces some 306 alignments).

I guess my question here is: Is there a way to discriminate between reads that really only have one valid aligment, and reads that have undergone multiple reseeding attempts without a valid secondary alignment until they eventually exceed the `-D` limit? I understand that using `-D 15` is a trade-off between speed and specificity, but ultimately the scenario shown here reports repetitive reads as unique hits which we would like to exclude from the results.

Many thanks! Felix

**Comment by BenLangmead** [comment]
I'll make suggestions that don't involve changing the algorithm, but of course that is another option, and one we're always looking at.

First: what if we (optionally) reported a value for `XS:i` even if the second-best alignment found is not above the `--score-min` floor?  Might that help?

Second: what if we output more extra flags indicating how repetitive the seeds are?  We already do this with the undocumented `--mapq-extra` flag, but it's in an ugly format that might change in future versions.  But we could add a nicer flag in a future version if you think this addresses the issue.

**Comment by FelixKrueger** [comment]
Thanks for this speedy response! I don't think the First option would help a great deal in this case because the two scenarios above would probably still look the same, wouldn't they?

The second suggestion would be a very good alternative I think. If the new flag could report the number of seeds a given reads has we could use that to filter further. Ultimately it might be enough to know if a read has lots and lots of potential alignments, or at least more than would be tested with `-D`, because if a read has more seeds than `-D` there is no way to know which alignment is the best unless you have tested them all. Is that correct? So yes, an option to report the repetitiveness of a read would be much appreciated for a future release. 

Just out of interest, another option would be to increase `-D` to say 50 or 100 as a compromise between speed and peace of mind, do you have a feel of how bad this would actually be in terms of increased alignment times (I guess it depends a lot on the application and its repeat content, but let's say a typical bisulfite-Seq experiment...)?

Many thanks, Felix

**Comment by BenLangmead** [comment]
As for your final question, Felix, I'm not sure what the performance penalty would be.  It's a safe bet that doubling `-D` would less-than-double the running time, as the `-D` limit is met only for a subset of the reads.  But that's as much intuition as I have; the rest depends on e.g. bisulfite versus non-bisulfite.

@ch4rr0 A possible way to address this would be to add a new option that takes some of the information currently printed in the `ZT:Z` field when `--mapq-extra` is specified and optionally report it in a different, documented extra field.  The undocumented `--seed-summary` option might also be a model for this, though that option seems to be broken and it prints _only_ information about seed hits.

**Comment by BenLangmead** [comment]
Here's where some of the relevant information is printed with the current `--mapq-extra` option:

https://github.com/BenLangmead/bowtie2/blob/master/sam.cpp#L641

The measures we print are `seedsPerNucMS` (something to do with how much of the read is covered by seeds that aligned at least once), `seedPctUniqueMS` (fraction of aligned seeds that aligned uniquely), `seedPctRepMS` (fraction of aligned seeds that aligned repetitively), `seedHitAvgMS` (average number of seed hits for seeds that aligned).

**Comment by ch4rr0** [comment]
This one slipped through the cracks, but I may have found a solution that works. In my most recent commit I added the `XT:U` SAM Flag, inspired by BWA, to identify unique reads. Bowtie2 will add the tag if the aligner is unable to find a secondary alignment and the average number of seed hits for the read is less than the max DP fails as specified by `-D`.

**Comment by FelixKrueger** [comment]
This does indeed sounds like a potential solution. I guess it's time to close the issue, many thanks!
