### ISSUE TITLE
Cannot align an existing sequence in the mouse genome

### ISSUE THREAD

**Issue by lucapinello** [BenLangmead/bowtie2#115]
Hi Ben,
I am trying to align this seq CCACTCGAACGGCGGAACTT to mm10

I tried 

bowtie2 --very-sensitive  -x  /data/pinello/COMMON_DATA/REFERENCE_GENOMES/Mus_musculus/UCSC/mm10/Sequence/Bowtie2Index/genome -c -U  CCACTCGAACGGCGGAACTT

Without luck (i tried also the local mode ) (version 2.3.2 from bioconda)

1 reads; of these:
  1 (100.00%) were unpaired; of these:
    1 (100.00%) aligned 0 times
    0 (0.00%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
0.00% overall alignment rate
@HD	VN:1.0	SO:unsorted
@SQ	SN:chr10	LN:130694993
@SQ	SN:chr11	LN:122082543
@SQ	SN:chr12	LN:120129022
@SQ	SN:chr13	LN:120421639
@SQ	SN:chr14	LN:124902244
@SQ	SN:chr15	LN:104043685
@SQ	SN:chr16	LN:98207768
@SQ	SN:chr17	LN:94987271
@SQ	SN:chr18	LN:90702639
@SQ	SN:chr19	LN:61431566
@SQ	SN:chr1	LN:195471971
@SQ	SN:chr2	LN:182113224
@SQ	SN:chr3	LN:160039680
@SQ	SN:chr4	LN:156508116
@SQ	SN:chr5	LN:151834684
@SQ	SN:chr6	LN:149736546
@SQ	SN:chr7	LN:145441459
@SQ	SN:chr8	LN:129401213
@SQ	SN:chr9	LN:124595110
@SQ	SN:chrM	LN:16299
@SQ	SN:chrX	LN:171031299
@SQ	SN:chrY	LN:91744698
@PG	ID:bowtie2	PN:bowtie2	VN:2.3.2	CL:"/PHShome/lp698/anaconda2/bin/bowtie2-align-s --wrapper basic-0 --very-sensitive -x /data/pinello/COMMON_DATA/REFERENCE_GENOMES/Mus_musculus/UCSC/mm10/Sequence/Bowtie2Index/genome -c -U CCACTCGAACGGCGGAACTT"
0	4	*	0	0	*	*	0	0	CCACTCGAACGGCGGAACTT	IIIIIIIIIIIIIIIIIIII	YT:Z:UU

Bowtie 1 instead works fine:
bowtie /data/pinello/COMMON_DATA/REFERENCE_GENOMES/Mus_musculus/UCSC/mm10/Sequence/BowtieIndex/genome -c CCACTCGAACGGCGGAACTT

0	+	chr5	90561201	CCACTCGAACGGCGGAACTT	IIIIIIIIIIIIIIIIIIII	0	2:T>A,6:A>G
# reads processed: 1
# reads with at least one reported alignment: 1 (100.00%)
# reads that failed to align: 0 (0.00%)
Reported 1 alignments to 1 output stream(s)

What option should I use to recover this alignment?

Thanks,

Luca

**Comment by BenLangmead** [comment]
Reads this short do not play well with Bowtie 2's heuristics, which look for long stretches of exact-matching bases.  You could get it to work with Bowtie 2 by decreasing `-L` and possibly setting `-N 1`, among other things.  But you would be better off using Bowtie, which is designed with very short reads (say, <=35 bp) in mind.

**Comment by lucapinello** [comment]
Thanks for the explanation Ben, I will use Bowtie 1.
