### ISSUE TITLE
bowtie2 2.3.2 can not handle new lind in reads.

### ISSUE THREAD

**Issue by mkoohim** [BenLangmead/bowtie2#117]
I recently used bowtie2 2.3.2 in my work and the strange thing in result was the maximum alignment was 70 but average length of my read file was around 90. So I checked the results by details and found if there is new line in read sequence of read file (Which is usually happens) bowtie2 2.3.2 skip the second line and simply use the first line for alignment. For example:

>read000011
AGGTAGCTGTTGAGCCTGGGGCGGTAGCGTGCTTTTTCTGCTTCACCTTAATCGGATAATCTCAACAAAA
AGAGTTACTTGTGGATAAGCCATT

 bowtie2 2.3.2 just consider "AGGTAGCTGTTGAGCCTGGGGCGGTAGCGTGCTTTTTCTGCTTCACCTTAATCGGATAATCTCAACAAAA" in alignment and in result report:

read000011	0	AJ426044.2	1611	42	70M	*	0	0	AGGTAGCTGTTGAGCCTGGGGCGGTAGCGTGCTTTTTCTGCTTCACCTTAATCGGATAATCTCAACAAAA

And skip the second line "AGAGTTACTTGTGGATAAGCCATT" However I am sure that I have the whole of this read in my ref data.

Please check this issue.
Thank you,

**Comment by mkoohim** [comment]
@ch4rr0 I am wondering any update for this bug? Thanks,

**Comment by ch4rr0** [comment]
I pushed a change to the  `bug_fixes` branch that addresses this issue. If you're able to compile Bowtie 2 from source, then the fix should be available to you. If not, then the fixed will be made part of our next Bowtie 2 release scheduled for 18th.

**Comment by mkoohim** [comment]
Thanks!
