### ISSUE TITLE
bowtie2 has already run in ARM64, but the result is different from x86.

### ISSUE THREAD

**Issue by zoujingyuan** [BenLangmead/bowtie2#118]
I have transport the sse instruction in bowtie2 to arm neon instruction ,and check each instruction realize the same function. bowtie2 can be compiled in ARM64, but the result is different from x86. The following is the test result:
in X86
[root@foam2 bowtie2-2.3.1_x86]# ./bowtie2 -x lambda_virus -U example/reads/reads_1.fq -S eg1.sam
10000 reads; of these:
  10000 (100.00%) were unpaired; of these:
    596 (5.96%) aligned 0 times
    9404 (94.04%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
94.04% overall alignment rate

in ARM64:
node5:/home/zjy/bowtie2-2.3.1 # ./bowtie2 -x lambda_virus -U example/reads/reads_1.fq -S eg1.sam
10000 reads; of these:
  10000 (100.00%) were unpaired; of these:
    5605 (56.05%) aligned 0 times
    4395 (43.95%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
43.95% overall alignment rate

I can not find why the result is different.

**Comment by BenLangmead** [comment]
I'm afraid we are not familiar with those instructions and don't have the time to provide hands-on help with this.  Good luck, though.
