### ISSUE TITLE
bowtie2-build issue

### ISSUE THREAD

**Issue by cjyang90** [BenLangmead/bowtie2#12]
Hi, I encountered this following problem whenever I tried bowtie2-build, bowtie2-build-s OR bowtie2-build-l in Windows:

"bowtie2-build-s" has stopped working
"bowtie2-build-l" has stopped working

But, then it works when I used bowtie2-build-s-debug or bowtie2-build-l-debug. Everything here was done on lambda phage example provided in the bowtie2 folder. Any idea on why "debug" option is needed?

**Comment by val-antonescu** [comment]
I just double checked current version 2.2.4 and both debug and non debug versions are working fine for me. I am using a windows7 laptop. What Windows are you using? 

Val

**Comment by val-antonescu** [comment]
I will close this issue for now.

Val
