### ISSUE TITLE
unable to compile bowtie2 - 2.3.2 

### ISSUE THREAD

**Issue by alui07** [BenLangmead/bowtie2#124]
Hi, I've been getting this error after running "make" after unzipping the zipped source file

>>make

g++ -O3 -m64 -msse2 -funroll-loops -g3 -DCOMPILER_OPTIONS="\"-O3 -m64 -msse2 -funroll-loops -
g3 -DPOPCNT_CAPABILITY -DWITH_TBB -DNO_SPINLOCK -DWITH_QUEUELOCK=1\"" -DPOPCNT_CAPABILITY -DW
ITH_TBB -DNO_SPINLOCK -DWITH_QUEUELOCK=1 \
        -fno-strict-aliasing -DBOWTIE2_VERSION="\"`cat VERSION`\"" -DBUILD_HOST="\"`hostname`
\"" -DBUILD_TIME="\"`date`\"" -DCOMPILER_VERSION="\"`g++ -v 2>&1 | tail -1`\"" -D_LARGEFILE_S
OURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE  -DBOWTIE_MM  -DBOWTIE2 -DNDEBUG -Wall \
         -I third_party \
        -o bowtie2-build-s bt2_build.cpp \
        ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp edit.cpp bt2_idx.cpp bt2_io.cpp bt2_
util.cpp reference.cpp ds.cpp multikey_qsort.cpp limit.cpp random_source.cpp diff_sample.cpp
bowtie_build_main.cpp \
        -lz -lpthread -ltbb -ltbbmalloc_proxy
In file included from bt2_idx.h:42:0,
                 from bt2_build.cpp:27:
blockwise_sa.h:24:21: fatal error: tbb/tbb.h: No such file or directory
compilation terminated.
In file included from ds.h:30:0,
                 from ref_read.h:33,
                 from ref_read.cpp:20:
threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
compilation terminated.
In file included from ds.h:30:0,
                 from edit.h:29,
                 from edit.cpp:21:
threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
compilation terminated.
In file included from bt2_idx.h:42:0,
                 from bt2_idx.cpp:25:
blockwise_sa.h:24:21: fatal error: tbb/tbb.h: No such file or directory
compilation terminated.
In file included from bt2_idx.h:42:0,
                 from bt2_io.cpp:25:
blockwise_sa.h:24:21: fatal error: tbb/tbb.h: No such file or directory
compilation terminated.
In file included from bt2_idx.h:42:0,
                 from bt2_util.cpp:26:
blockwise_sa.h:24:21: fatal error: tbb/tbb.h: No such file or directory
compilation terminated.

it's very similar to issue #71 and https://github.com/Homebrew/homebrew-science/issues/5302, but none of the solutions seemed to help me.

Any help is appreciated! Thank you for your time

**Comment by V-Z** [comment]
I experience same problem with Bowtie 2.3.3.1 on openSUSE Linux with GCC7:
```
make
g++ -O3 -m64 -msse2 -funroll-loops -g3 -DCOMPILER_OPTIONS="\"-O3 -m64 -msse2 -funroll-loops -g3 -DPOPCNT_CAPABILITY -DWITH_TBB -DNO_SPINLOCK -DWITH_QUEUELOCK=1\"" -DPOPCNT_CAPABILITY -DWITH_TBB -DNO_SPINLOCK -DWITH_QUEUELOCK=1 \
        -fno-strict-aliasing -DBOWTIE2_VERSION="\"`cat VERSION`\"" -DBUILD_HOST="\"`hostname`\"" -DBUILD_TIME="\"`date`\"" -DCOMPILER_VERSION="\"`g++ -v 2>&1 | tail -1`\"" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE  -DBOWTIE_MM  -DBOWTIE2 -DNDEBUG -Wall \
         -I third_party \
        -o bowtie2-build-s bt2_build.cpp \
        ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp edit.cpp bt2_idx.cpp bt2_io.cpp bt2_util.cpp reference.cpp ds.cpp multikey_qsort.cpp limit.cpp random_source.cpp diff_sample.cpp bowtie_build_main.cpp \
          -lz -lpthread -ltbb -ltbbmalloc_proxy 
In file included from bt2_idx.h:42:0,
                 from bt2_build.cpp:28:
blockwise_sa.h:24:10: fatal error: tbb/tbb.h: No such file or directory
 #include <tbb/tbb.h>
          ^~~~~~~~~~~
compilation terminated.
In file included from ds.h:30:0,
                 from ref_read.h:33,
                 from ref_read.cpp:20:
threading.h:29:11: fatal error: tbb/mutex.h: No such file or directory
 # include <tbb/mutex.h>
           ^~~~~~~~~~~~~
compilation terminated.
In file included from ds.h:30:0,
                 from edit.h:29,
                 from edit.cpp:21:
threading.h:29:11: fatal error: tbb/mutex.h: No such file or directory
 # include <tbb/mutex.h>
           ^~~~~~~~~~~~~
compilation terminated.
In file included from bt2_idx.h:42:0,
                 from bt2_idx.cpp:25:
blockwise_sa.h:24:10: fatal error: tbb/tbb.h: No such file or directory
 #include <tbb/tbb.h>
          ^~~~~~~~~~~
compilation terminated.
In file included from bt2_idx.h:42:0,
                 from bt2_io.cpp:25:
blockwise_sa.h:24:10: fatal error: tbb/tbb.h: No such file or directory
 #include <tbb/tbb.h>
          ^~~~~~~~~~~
compilation terminated.
In file included from bt2_idx.h:42:0,
                 from bt2_util.cpp:26:
blockwise_sa.h:24:10: fatal error: tbb/tbb.h: No such file or directory
 #include <tbb/tbb.h>
          ^~~~~~~~~~~
compilation terminated.
In file included from ds.h:30:0,
                 from ref_read.h:33,
                 from reference.h:32,
                 from reference.cpp:22:
threading.h:29:11: fatal error: tbb/mutex.h: No such file or directory
 # include <tbb/mutex.h>
           ^~~~~~~~~~~~~
compilation terminated.
In file included from ds.h:30:0,
                 from ds.cpp:20:
threading.h:29:11: fatal error: tbb/mutex.h: No such file or directory
 # include <tbb/mutex.h>
           ^~~~~~~~~~~~~
compilation terminated.
In file included from ds.h:30:0,
                 from sequence_io.h:28,
                 from multikey_qsort.h:24,
                 from multikey_qsort.cpp:20:
threading.h:29:11: fatal error: tbb/mutex.h: No such file or directory
 # include <tbb/mutex.h>
           ^~~~~~~~~~~~~
compilation terminated.
In file included from ds.h:30:0,
                 from random_util.h:25,
                 from random_source.cpp:21:
threading.h:29:11: fatal error: tbb/mutex.h: No such file or directory
 # include <tbb/mutex.h>
           ^~~~~~~~~~~~~
compilation terminated.
In file included from diff_sample.cpp:20:0:
diff_sample.h:24:10: fatal error: tbb/tbb.h: No such file or directory
 #include <tbb/tbb.h>
          ^~~~~~~~~~~
compilation terminated.
In file included from ds.h:30:0,
                 from bowtie_build_main.cpp:25:
threading.h:29:11: fatal error: tbb/mutex.h: No such file or directory
 # include <tbb/mutex.h>
           ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:283: bowtie2-build-s] Error 1
```

**Comment by V-Z** [comment]
I'm sorry, it was issue with TBB development library...
