### ISSUE TITLE
Making Small Indexes

### ISSUE THREAD

**Issue by davebridges** [BenLangmead/bowtie2#13]
Since Tophat dosent accept bt2l index files is there a way to over-ride bowtie2-build to force it to build the smaller *.bt2 index files.  I tried

```sh
bowtie2-build-s hg19.fa
```

But it still generated a large index.  I am using bowtie2-2.2.4

**Comment by val-antonescu** [comment]
That shouldn't happen for files smaller than ~4 GB. The wrapper takes a rough approximation of the index size and builds the correct index. However the bowtie2-build-s should always build a small index. I checked bowtie2-2.2.4 and it behaves as expected. In your case something must have gone wrong. Did you recompile from source code or use the pre-made binaries?

Val

**Comment by val-antonescu** [comment]
I assume this was solved. I will close it for now.

Val
