### ISSUE TITLE
Issue of running bowtie2, malloc_zone error!

### ISSUE THREAD

**Issue by vatanparast** [BenLangmead/bowtie2#133]
Hello,
I have hard time running bowtie2 (compiled latest version: bowtie 2-2.3.2) and getting this error:

```
bowtie2-build(26845,0x7fffea2723c0) malloc: *** malloc_zone_unregister() failed for 0x7fffea268000
Warning: Empty fasta file: 'Fabales.fsa'
Warning: All fasta inputs were empty
Error: Encountered internal Bowtie 2 exception (#1)
Command: bowtie2-build --wrapper basic-0 Fabales.fsa Clitoria_ternatea_bowtie
bowtie2-align-s(26847,0x7fffea2723c0) malloc: *** malloc_zone_unregister() failed for 0x7fffea268000
bowtie2-align-s(26848,0x7fffea2723c0) malloc: *** malloc_zone_unregister() failed for 0x7fffea268000
```
According to the SourceForce page, installing latest TBB, should solve the issue, but it didn't in my case. I installed latest TBB via Home brew and running macOS 10.12.6. I got the same error in the HP cluster running CentOS.

Thanks
Mohammad

**Comment by ch4rr0** [comment]
I too am running 10.12.6 with TBB 2017 U7, but I don't get the "malloc_zone_unregister" failures. Can you confirm that you are indeed running the  most recent version of TBB?

This is what `brew` outputs for me:
```
$ brew info tbb
tbb: stable 2017_U7
Rich and complete approach to parallelism in C++
https://www.threadingbuildingblocks.org/
/usr/local/Cellar/tbb/2017_U7 (120 files, 2.0MB) *
  Built from source on 2017-07-27 at 22:32:52
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tbb.rb
==> Dependencies
Build: swig ✔
==> Requirements
Required: macOS >= 10.7 ✔
==> Options
--c++11
	Build using C++11 mode
```

FYI - the `malloc_zone_unregister` failures should not affect your bowtie alignment. Bowtie 2 seems to have encountered an internal error that could possibly have been as a result of your FASTA files?

>Warning: Empty fasta file: 'Fabales.fsa'
>Warning: All fasta inputs were empty
>Error: Encountered internal Bowtie 2 exception (#1)

**Comment by vatanparast** [comment]
Thank you for the feedback. It seems that I'm running older version of TBB?! Though I installed through brew using 'brew install tbb'.

```
[~] brew info tbb                                                    
tbb: stable 4.4-20160128
Rich and complete approach to parallelism in C++
https://www.threadingbuildingblocks.org/
/usr/local/Cellar/tbb/4.4-20160128 (108 files, 1.9M) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/tbb.rb
==> Options
--c++11
	Build using C++11 mode
```

I'll re-check again the TBB version.

About FASTA files, I don't know why I get this warning, the FASTA files are in the path!

**Comment by ch4rr0** [comment]
Your version is from 2016 according to the above brew output. You should upgrade to the latest version, `brew update && brew upgrade tbb`

**Comment by vatanparast** [comment]
Thank you. That solved the issue!
