### ISSUE TITLE
mapq scores

### ISSUE THREAD

**Issue by Carol-Symbiomics** [BenLangmead/bowtie2#135]
Hi everyone, 
I just wanted to make sure if Bowtie2 is working properly regarding the mapq scores assignment. Although there is not precise information in the Bowtie2 manual about the ranges that the map score can have, I've seen other post referring to the range from 0 to 42. Nevertheless, I have a large number of sequences that got a score of 44. Can someone tell me if that is a mistake?? The version I have installed is the 2.1.0

Thanks in advance

**Comment by BenLangmead** [comment]
Yes, MAPQs can indeed range up to 44 in local alignment mode.  Not a mistake :-)
