### ISSUE TITLE
option "--sam-noqname-trunc" unrecognized

### ISSUE THREAD

**Issue by lipido** [BenLangmead/bowtie2#136]
When using `--sam-noqname-trunc` option, bowtie2 gives an error saying that such option is unrecognized. However, it is available in the manual.

Looking at source code, the real option name is `--sam-no-qname-trunc`, instead of `--sam-noqname-trunc`. With `--sam-no-qname-trunc` works as expected.

**Comment by BenLangmead** [comment]
Thanks -- we fixed that with: https://github.com/BenLangmead/bowtie2/commit/4679616befdce686cdd6444f85495d05c3c6d00c
