### ISSUE TITLE
Skip the input files more than cpu numbers, v2.3.3

### ISSUE THREAD

**Issue by mkoohim** [BenLangmead/bowtie2#139]
Hi,
I would be so thankful if you check and fix the following bug in new version of bowtie2:

`bowtie2 --no-unal -f -x BGCDB -U sample1.fasta,sample2.fasta,sample3.fasta,sample4.fasta -S out_sam.txt -p 4` 
The above command works fine, but if the number of cpu change to the 3, bowtie2 skip the last sample! If you change it to 2 the two last sample will be skipped!
It seems bowtie2 skips the samples more than cpu number.

Thank you,

**Comment by BenLangmead** [comment]
Thank you.  Question: How are you determining that `bowtie2` is skipping some of the samples?

**Comment by mkoohim** [comment]
I am working on a metagenomics pipeline and I have some test samples (smaller than real one to save time) and some python test scripts, Honestly, I found bowtie2-2.2.6 is the best and most stable version for Fasta files (I didn't use 2.3.2 because of newline skipping issue). 
After running the test script on the test files I saw in some cases I have different number of reads and for some of them same number of reads. For those ones which the number of input samples are less than cpu number the result is same and for those one with more than cpu number there is difference. 
The following are some real examples:

`bowtie2 --no-unal -f -x BGCDB -U ERR480791_1.fasta,ERR480793_1.fasta,ERR480792_1.fasta,ERR480790_1.fasta -S out_sam.txt -p 3`

**3174257 reads**; of these:
  3174257 (100.00%) were unpaired; of these:
    3169456 (99.85%) aligned 0 times
    468 (0.01%) aligned exactly 1 time
    4333 (0.14%) aligned >1 times
0.15% overall alignment rate

`bowtie2 --no-unal -f -x BGCDB -U ERR480791_1.fasta,ERR480793_1.fasta,ERR480792_1.fasta,ERR480790_1.fasta -S out_sam.txt -p 4`

**4231667 reads**; of these:
  4231667 (100.00%) were unpaired; of these:
    4225223 (99.85%) aligned 0 times
    631 (0.01%) aligned exactly 1 time
    5813 (0.14%) aligned >1 times
0.15% overall alignment rate

**4231667**  is the correct number of reads for these 4 samples, not 3174257.

**Comment by BenLangmead** [comment]
Thanks.  Could you let us know whether this is also an issue when using the latest (2.3.3) release?

**Comment by mkoohim** [comment]
What do you mean by last release? I used the following version:
https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.3.3/bowtie2-2.3.3-linux-x86_64.zip/download
Yes, this is issue of 2.3.3. The previous version (2.2.6) works fine! I didn't try your github last update.

**Comment by BenLangmead** [comment]
Thank you, I misunderstood

**Comment by mkoohim** [comment]
No problem, I would be so thankful if you check it and if it is really a bug make a patch for it as it can affect the result dramatically. Thank you!

**Comment by ch4rr0** [comment]
I am looking into. I will follow up with results as soon as I have them.

**Comment by mkoohim** [comment]
Thanks, in case if you want to use those samples which I used in the above examples  you can use the following metagenomics sample:
https://www.ncbi.nlm.nih.gov/sra/?term=CCIS74239020ST-4-0

**Comment by ch4rr0** [comment]
Sorry for the inconvenience. I created this patched build for you which should contain a fix for this issue. The changes are not finalized, so I won't have an official build until then. Thank you for your patience.

https://github.com/BenLangmead/bowtie2/releases/download/v2.3.3/bowtie2-2.3.3_p1-linux-x86_64.zip

**Comment by mkoohim** [comment]
Really tanks for your hard working. Just as a suggestion, that would be good if you aware your users about this issue and ask them to use this patch version. Because, definitely some of them use -p 1 or less than 5 cpus in their work and it can affect their final result dramatically. Thank you!

**Comment by ch4rr0** [comment]
I have updated the patched build with a change to address an edge case that I found while testing. I will be updating the release notes on GitHub and Sourceforge tomorrow to bring attention to this issue. Thank you!

**Comment by mkoohim** [comment]
Thank you!

**Comment by BenLangmead** [comment]
This is fixed in 2.3.3.1  Thanks!
