### ISSUE TITLE
Bowtie2 character encoding and format error

### ISSUE THREAD

**Issue by vcepeda** [BenLangmead/bowtie2#14]
Although bowtie2  detects errors in the fastq file, it does not give accurate information to determine where is the error.
For example, an error like this:
"Saw ASCII character 0 but expected 33-based Phred qual.
terminate called after throwing an instance of 'int'
(ERR): bowtie2-align died with signal 6 (ABRT) "
is thrown if there is a flipped bit somewhere in the fastq file or the fastq files is incorrectly formatted (e.g. missing read seq or quality).

**Comment by val-antonescu** [comment]
Fixed it for next release. 

thanks,
Val
