### ISSUE TITLE
Wrong alignment score in local mode with ignore-quals?

### ISSUE THREAD

**Issue by pavanvidem** [BenLangmead/bowtie2#144]
Used bowtie2 2.2.6. I have the following 2 alignments, with exactly the same CIGAR. The only difference is that there is a mismatch in the second alignment. My scoring options are: `--rdg 2,1 --rfg 2,1 --score-min L,18,0 --np 1 --ma 1 --mp 5,1`. 
For the first alignment AS = 21 (M) - 2 (`XO:i:1`) - 15 (`XG:i:15`) + 22 (M) = 26, which matches.
For the second alignment AS = 21 (M) - 2 (`XO:i:1`) - 15 (`XG:i:15`) + 21 (M) - 5 (`XM:i:1`) = 20, which is diffrent from `AS.i:24` in the alignment. Is there something I'm missing? 
Alignment 1: `tag_344761|1	0	MI0000167_mmu-mir-142a	4	255	6S21M15D22M	*	0	0	CTTTCTCATAAAGTAGAAAGCACTACTTGTAGTGTTTCCTACTTTATGG	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:26	XN:i:0	XM:i:0	XO:i:1	XG:i:15	NM:i:15	MD:Z:21^AACAGCACTGGAGGG22	YT:Z:UU`
Alignment 2: `tag_457953|1	0	MI0000167_mmu-mir-142a	4	255	6S21M15D22M	*	0	0	GTCTCTCATAAAGTAGAAAGCACTACTTGTAGTGTTNCCTACTTTATGG	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:24	XN:i:0	XM:i:1	XO:i:1	XG:i:15	NM:i:16	MD:Z:21^AACAGCACTGGAGGG9T12	YT:Z:UU`

**Comment by BenLangmead** [comment]
It's odd to see `--mp 5,1` because `--mp` should only take 1 option.  Can you try omitting `--mp` or try passing `--mp` a single integer (the max penalty) and let us know if you still see something unexpected?

**Comment by pavanvidem** [comment]
I overlooked an ambiguous base N in the read of 2nd alignment. With --np 1, AS = 21 (M) - 2 (XO:i:1) - 15 (XG:i:15) + 21 (M) - 1 (for N) = 24.
