### ISSUE TITLE
2.3.3 stopped using BOWTIE2_INDEXES

### ISSUE THREAD

**Issue by jakewendt** [BenLangmead/bowtie2#145]
I just tried the latest binary downloads, as well as downloaded source, and they don't recognize old indexes. 

```
(ERR): "XXXXXX" is not a Bowtie 2 index
```

If they are in the current directory, they work. It appears that it stopped searching in BOWTIE2_INDEXES.

If I backup to 2.2.9, everything works as expected.

**Comment by jakewendt** [comment]
Trying with git source code.

```
git clone https://github.com/BenLangmead/bowtie2.git
cd bowtie2
INC="-L /opt/local/lib/" make -e
make install
bowtie2 -x XXXXXX ...

(ERR): "XXXXXX" is not a Bowtie 2 index
Exiting now ...
```
Latest fails.


```
git checkout v2.3.1
INC="-L /opt/local/lib/" make -e
make install
bowtie2 -x XXXXXX ...
```
2.3.1 works.


```
git checkout v2.3.2
INC="-L /opt/local/lib/" make -e
make install
bowtie2 -x XXXXXX ...
```
2.3.2 works

```
git checkout v2.3.3
INC="-L /opt/local/lib/" make -e
make install
bowtie2 -x XXXXXX ...

(ERR): "XXXXXX" is not a Bowtie 2 index
Exiting now ...
```
2.3.3 fails to find the index in the directory designated with $BOWTIE2_INDEXES

**Comment by ch4rr0** [comment]
I pushed a commit to master that addresses this issue. Please take a look.

**Comment by jakewendt** [comment]
Perfect. Thank you.
