### ISSUE TITLE
--reorder does not work with version 2.3.3

### ISSUE THREAD

**Issue by laurencowley** [BenLangmead/bowtie2#146]
I am trying to output a sam file in the same order as the input fastq but that --reorder flag doesn't seem to work with version 2.3.3?

**Comment by ch4rr0** [comment]
The option works for me. If possible can you share your command line?

**Comment by laurencowley** [comment]
`/usr/local/bin/../Cellar/bowtie2/2.3.3/bin/bowtie2 -p 8 --reorder -q --ignore-quals -D 24 -R 3 -N 0 -L 7 -i S,1,0.50 -x Streptococcus_pneumoniae_ATCC_700669_v1 -S seer_filtered.sam -U seer00_filtered.fastq`

**Comment by laurencowley** [comment]
also get this error:

`Saw ASCII character 0 but expected 33-based Phred qual.
libc++abi.dylib: terminating with uncaught exception of type int
(ERR): bowtie2-align died with signal 6 (ABRT)`

**Comment by ch4rr0** [comment]
Would it be possible to share your input files?

**Comment by laurencowley** [comment]
[Streptococcus_pneumoniae_ATCC_700669_v1.fasta.txt](https://github.com/BenLangmead/bowtie2/files/1333363/Streptococcus_pneumoniae_ATCC_700669_v1.fasta.txt)
[seer00_filtered_fastq.txt](https://github.com/BenLangmead/bowtie2/files/1333365/seer00_filtered_fastq.txt)

**Comment by ch4rr0** [comment]
Your fastq file contains non-printable characters hence the error:
> Saw ASCII character 0 but expected 33-based Phred qual. libc++abi.dylib: terminating with uncaught exception of type int (ERR): bowtie2-align died with signal 6 (ABRT)

Issuing the below command confirms this:
```
$ file seer00_filtered_fastq.txt 
seer00_filtered_fastq.txt: data
```

To remove offending characters, which happen to be the quality values of some of the reads, you need to:
`$ sed -i '' -e 's/[[:cntrl:]]/~/g' seer00_filtered_fastq.txt`

This command will modify the input file in-place substituting the non-printable characters with tildes. You can then confirm that the output is now ASCII:
```
$ file seer00_filtered_fastq.txt
/dev/stdin: ASCII text
```

Once you've done that you can then rerun your alignment without error.

To confirm that the `--reorder` command works I did the following:
`diff <(awk '{ print $1 }' seer_filtered.sam) <(awk '{ print $1 }' seer_filtered.sam | sort -n)`

Please let me know if the issue persists. Thank you.

**Comment by laurencowley** [comment]
Thanks so much, the alignment now runs without error but the sam file is still in a different order to the fast. When I ran:
`diff <(awk '{ print $1 }' seer_filtered.sam) <(awk '{ print $1 }' seer_filtered.sam | sort -n)`
I got:
`2d1
< @SQ
3a3
> @SQ`

**Comment by laurencowley** [comment]
actually I have just worked out that they are in the same order, some are just reverse complement! Sorry!
