### ISSUE TITLE
Multiseed length and policy string parsing

### ISSUE THREAD

**Issue by Ferrantisimo** [BenLangmead/bowtie2#15]
Certain command line arguments that are passed via policy string to SeedAlignmentPolicy::parseString are parsed in an order-specific manner, and can lead to unintended behavior.

Specifically, the multiseed length parameter can be set by both the SEED and SEEDLEN policy string arguments.  The SEED policy is set by the -N and --multiseed command-line arguments; SEEDLEN policy is set by the -L command-line argument.  If a SEED policy string appears after the SEEDLEN string, it will overwrite the multiseed length parameter specified by SEEDLEN policy.  The effect of this is that the -N and -L command-line arguments must be given in the proper order, or else the multiseed length parameter will be set to the default value (22) rather than the value specified by the -L command-line argument.

To recreate this behavior: 
`bowtie2 -N 1 -L 10 --verbose` gives the following policy string: `SEED=0,22;DPS=15;ROUNDS=2;IVAL=S,1,1.15;SEED=1;SEEDLEN=10`.  The multiseed length variable (multiseedLen) is set by both SEED parameters and the SEEDLEN parameter.  It is first set to 22 as specified in the first SEED policy string, then to 22 again as a result of the handling of the SEED string, and finally to 10 as per the SEEDLEN parameter from the -L command-line option.  multiseedLen value is 10 and the multiseed alignment proceeds as expected.

`bowtie2 -L 10 -N 1 --verbose` gives the following policy string: `SEED=0,22;DPS=15;ROUNDS=2;IVAL=S,1,1.15;SEEDLEN=10;SEED=1`.  The multiseed length variable (multiseedLen) is set first to 22 as specified in the first SEED policy string, then to 10 by the SEEDLEN parameter.  The final SEED parameter results in multiseedLen being overwritten with the default value of 22.  This is the result of the `if(ctoks.size() >= 2)` check (aligner_seed_policy.cpp, line 560), which evaluates as false and resets the multiseedLen value.  As a result, multiseedLen value is 22 rather than 10 as specified on the command line.  The multiseed alignment will attempt to extract seeds of length 22, which differs from the expected behavior.

I have verified this behavior in bowtie2-2.2.4 as well as the current repository version.

Fix: I don't have a specific fix as I am not a project member, nor am I very familiar with the bowtie2 code base.  However, placing the -L argument at the end of the command will work.  Alternatively, one can comment out aligner_seed_policy.cpp line 560 without any obvious ill effects.

P.S.  The handling of the SEED parameter also gives rise to another unintended problem.  In local mode the default seed length is 20.  Passing the command-line arguments `--local -N 1` will produce a policy string ending with `SEED=1`, resulting in the multiseed length being reset to 22 rather than the local-mode default of 20.

**Comment by BenLangmead** [comment]
Thank you!  We took a look and we think we fixed it by: (a) when -N is specified but the seed length is not one of the specified values, it only attempts to change seed length if it *hasn't* already been set with -L. (b) when --local mode is enabled, the default value for the seed length is modified accordingly.  Please let us know if you have any other problems.  We appreciate the detailed report!

Best,
Ben

**Comment by val-antonescu** [comment]
These fixes will be available in the next release. I will close this issue for now.  

thanks again for reporting this,
Val
