### ISSUE TITLE
Different alignment output depending on the ordering of sequences used to build an index

### ISSUE THREAD

**Issue by willhooper** [BenLangmead/bowtie2#153]
Hi, 

I noticed an issue, I'm not sure if this is intentional or not. Essentially, I was using a collection of relatively short sequences to build an index, which I was then aligning reads to (and extracting the unmapped reads). Depending on the ordering of the sequences in the FASTA supplied to bowtie2-build, different numbers of unmapped reads were output from the same sample. The discrepancy wasn't huge (~700 reads), but this seems like it shouldn't be happening. 

For reference, I'm running Bowtie 2.3.2 on Ubuntu 16.04. 

Thanks,
Will

**Comment by BenLangmead** [comment]
This is expected.  Changing the order of the reference sequences changes the index.  More specifically, prior to indexing the sequences are concatenated.  Then the concatenated string is put through the Burrows Wheeler Transform.  The Transform will give a slightly different result depending on the order of the concatenation.  Aspects of the alignment algorithm that use randomness might therefore give different results depending on this order.

**Comment by BenLangmead** [comment]
I'll close this for now; feel free to reopen if you feel you're seeing incorrect behavior
