### ISSUE TITLE
Named pipe conflict

### ISSUE THREAD

**Issue by softbiome** [BenLangmead/bowtie2#157]
In "bowtie2.pl" the pipe is named after the PID (e.g., at line 371, my $m1fn = "$temp_dir/$$.inpipe1";). This works fine when running on a workstation. However, when submitting multiple bowtie2 jobs on an HPC, there is possibility that more than one jobs, which are concurrently running on different nodes, have the same PID. This will cause an error if these jobs share the same temp directory.

Proposed solution:
Instead of using only PID, using the hostname and PID to name the pipe.

**Comment by BenLangmead** [comment]
Resolved in 2.3.4.  Please reopen/comment if this doesn't solve it.
