### ISSUE TITLE
V2.3.3 / V2.3.3.1 duplicated and deleted output lines when using 30 or more cores

### ISSUE THREAD

**Issue by lpagie** [BenLangmead/bowtie2#158]
When I run bowtie on PE reads, max insert length=1000, and use 30 or more cores, in few cases some alignments are output double or are skipped. V2.3.2 does not appear to have this problem.
I run the same command 20x and in 1-5 cases the sam output contains single, or more than two copies of some readIDs (where you expect exactly 2 for PE reads).
Running the same command using small number of cores does not seem to generate this erroneous output. I tested on two machines, same result. The errors occur randomly though.

Please let me know how I can further help in figuring out whether this is my error or an error in bowtie. I have an archive containing all input data and index files, run script for testing, log files of tests performed, etc (nearly 5GB).

thanks, Ludo

**Comment by ch4rr0** [comment]
Thank you for your detailed feedback on this issue. It's a known issue that we have had difficulty reproducing. By confirming that the issue is isolated to v2.3.3 will certainly help us in narrowing down on the cause.

**Comment by ch4rr0** [comment]
We believe that we have found a solution to this issue and issue #155 and have created an [alpha build](https://github.com/BenLangmead/bowtie2/releases/tag/v2.3.4-alpha) with the fixes to have you confirm. Please let us know the outcome.

**Comment by lpagie** [comment]
I tested the alpha build and the problem appears gone. In versions 2.3.3 & 2.3.3.1 my reported error occurs in 5-10% of runs. In the alpha build the problem did not occur in 500 runs.
If you want I can transfer the complete set of data, scripts, logs, etc.
Thanks for looking into this

**Comment by BenLangmead** [comment]
Great! -- thanks for checking.  A new release including this fix is coming very soon.
