### ISSUE TITLE
v2.3.3.1 finds almost no --very-sensitive-local mappings compared to v2.2.9

### ISSUE THREAD

**Issue by sujaikumar** [BenLangmead/bowtie2#159]
Hi Ben/Bowtie team

I think I finally have it pinned down:
bowtie2-2.3.3.1 does not find MOST --very-sensitive-local mappings that bowtie2-2.2.9 can find.

Steps to reproduce the problem:

query.fa:
```
>1
TGAGGTAGTAGATTGTATAGTTAAAGGTGGAACTTCTATACAAATATTACCTCATTTGTTGTGTGACTGAGT
```
genome.fa:
```
>mmu-let-7f-1 MI0000562 Mus musculus let-7f-1 stem-loop
ATCAGAGTGAGGTAGTAGATTGTATAGTTGTGGGGTAGTGATTTTACCCTGTTTAGGAGA
TAACTATACAATCTATTGCCTTCCCTGAG
>mmu-let-7f-2 MI0000563 Mus musculus let-7f-2 stem-loop
TGTGGGATGAGGTAGTAGATTGTATAGTTTTAGGGTCATACCCCATCTTGGAGATAACTA
TACAGTCTACTGTCTTTCCCACG
>mmu-mir-15a MI0000564 Mus musculus miR-15a stem-loop
CCCTTGGAGTAAAGTAGCAGCACATAATGGTTTGTGGATGTTGAAAAGGTGCAGGCCATA
CTGTGCTGCCTCAAAATACAAGGA
```

bowtie2-2.2.9:
```
bowtie2-build genome.fa genome.fa
bowtie2 -f -U query.fa -x genome.fa --very-sensitive-local
# gives back 1 hit
```

bowtie2-2.3.3.1
```
bowtie2-build genome.fa genome.fa
bowtie2 -f -U query.fa -x genome.fa --very-sensitive-local
# gives back 0 hits
```

For both versions I downloaded the linux64 binary install. This is just a small example, but in my full dataset I was missing hundreds (if not thousands) of alignments.

Hope you can fix this. Till then I think I'll let other people know not to upgrade bowtie2...

Best wishes,

- Sujai

**Comment by ch4rr0** [comment]
The missing alignments are due to a change that we made in v2.3.1 to correct a discrepancy between the manual and the code. In this change we updated the default min alignment score for local mode from G,10,1, to G,20,8. To achieve pre v2.3.1 behavior you can append `--score-min G,10,1` to your command line. This should produce the desired output as evidenced below:
```
$ ./bowtie2 -f -U query.fa -x genome --very-sensitive-local --score-min G,10,1 --no-head
1 reads; of these:
  1 (100.00%) were unpaired; of these:
    0 (0.00%) aligned 0 times
    0 (0.00%) aligned exactly 1 time
    1 (100.00%) aligned >1 times
100.00% overall alignment rate
1	0	mmu-let-7f-1	8	0	22M50S	*	0	0	TGAGGTAGTAGATTGTATAGTTAAAGGTGGAACTTCTATACAAATATTACCTCATTTGTTGTGTGACTGAGT	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:44	XS:i:44	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:22	YT:Z:UU
```

**Comment by sujaikumar** [comment]
Thank you! That makes sense (I did panic initially though... :-))
