### ISSUE TITLE
Spaces in executable path or file paths

### ISSUE THREAD

**Issue by nivekkagicom** [BenLangmead/bowtie2#16]
There are a couple of places in the bowtie wrapper perl script that execute a command using Perl's open:

 "open(BT, "$cmd |")"

which passes $cmd to the shell. Unfortunately, if the executable is in a location where the path contains spaces or if any of the paths to data files contain spaces the command fails. Could someone fix this?

**Comment by val-antonescu** [comment]
I will look into this. Just proposed a fix for 2 other options which had the same issue, but we need to add filenames to these too. 
thanks for pointing this,
Val

**Comment by nivekkagicom** [comment]
Thanks for the quick response. I'd be glad to test any changes if that is helpful.

**Comment by val-antonescu** [comment]
I changed a little my proposal and it seems the space issue in paths is fixed on my machine. If you have some time to test it on your side it will be great. 

See bugs/325 branch (https://github.com/BenLangmead/bowtie2/archive/bugs/325.zip)

thanks,
Val

**Comment by nivekkagicom** [comment]
It's the path to the executable that is still at issue. I get the following error from the bowtie2 perl script:

(ERR): Failed to run command '/Applications/Genetic Software/bowtie2-align-s --wrapper basic-0 --arg-desc'

This occurs because script gets the path to the script and uses that to find the small or large alignment tool. In the perl wrapper script:

	my $cmd = "$align_prog --wrapper basic-0 --arg-desc";
	open(my $fh, "$cmd |") || Fail("Failed to run command '$cmd'\n");

Since $align_prog is not enclosed in quotes or otherwise escaped the executable cannot be found. This also occurs later in the script where again $cmd is again set and passed to the shell in an perl open.

	quote_params(\@bt2_args);
	my $cmd = "$align_prog$debug_str --wrapper basic-0 ".join(" ", @bt2_args);

Here again $align_prog$debug_str needs to be quoted or escaped.

**Comment by val-antonescu** [comment]
Oh, now I see what you mean. You are right. We need to quote the full path to program name.

**Comment by nivekkagicom** [comment]
Works great! Thank you!
