### ISSUE TITLE
Indecipherable segemenation faults

### ISSUE THREAD

**Issue by xapple** [BenLangmead/bowtie2#164]
I downloaded the prebuilt binary of the latest version and launched the mapping of a pair of fastq files from an Illumina Hiseq experiment against an assembly containing some contigs. The commands were thus the following:

    wget https://downloads.sourceforge.net/project/bowtie-bio/bowtie2/2.3.3.1/bowtie2-2.3.3.1-linux-x86_64.zip
    unzip bowtie2-2.3.3.1-linux-x86_64.zip
    rm bowtie2-2.3.3.1-linux-x86_64.zip
    mv bowtie2-2.3.3.1-linux-x86_64 ~/programs/bowtie
    export PATH="$HOME/programs/bowtie:$PATH"
    cd ~/metagenomics_project/
    bowtie2 -p 128 -x assembly/metaspades/filtered.fasta -1 sample_1/clean/forward_reads.fastq -2 sample_1/clean/reverse_reads.fastq -S bowtie_results/map.sam

The standard error contained the following:

    Segmentation fault (core dumped)
    Segmentation(ERR): bowtie2-align exited with value 139

The standard out was empty. The program exited after some amount of computation had happened by observing `top`.

There is basically nothing I can do to attempt to debug the problem in such a case, and it's usually a sign that the program was badly designed.

**Comment by BenLangmead** [comment]
This might be the same as #158.  Note that @ch4rr0 posted an alpha build in that thread that we think fixes this issue.  That fix will also be present in a new release coming soon.

**Comment by xapple** [comment]
So you are saying until you get this fixed, better stay away from bowtie altogether ?

**Comment by BenLangmead** [comment]
It the issue you're seeing is the one we think it is, then it seems to be affecting some users of 2.3.3 and 2.3.3.1 when `-p` is set high.  But it would help if you could try the alpha release linked to above to confirm that it is the issue we think it it.

**Comment by ch4rr0** [comment]
A fix for this has been released as part of v2.3.4
