### ISSUE TITLE
v2.3.4 Segmentation fault when using multiple CPUs

### ISSUE THREAD

**Issue by stevendavis** [BenLangmead/bowtie2#172]
OS = Ubuntu 14.04.5 

Installed with these commands:
cd ~/Downloads
wget https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.3.4/bowtie2-2.3.4-linux-x86_64.zip
mkdir  ~/software
cd  ~/software
unzip ~/Downloads/bowtie2-2.3.4-linux-x86_64.zip

Edit .bashrc, add this:
    export PATH=$PATH:~/software/bowtie2-2.3.4-linux-x86_64

$ bowtie2   --reorder -X 1000 -p 8 -x reference/lambda_virus -1 samples/sample2/sample2_1.fastq -2 samples/sample2/sample2_2.fastq > out
10000 reads; of these:
  10000 (100.00%) were paired; of these:
    888 (8.88%) aligned concordantly 0 times
    9112 (91.12%) aligned concordantly exactly 1 time
    0 (0.00%) aligned concordantly >1 times
    ----
    888 pairs aligned concordantly 0 times; of these:
      59 (6.64%) aligned discordantly 1 time
    ----
    829 pairs aligned 0 times concordantly or discordantly; of these:
      1658 mates make up the pairs; of these:
        1044 (62.97%) aligned 0 times
        614 (37.03%) aligned exactly 1 time
        0 (0.00%) aligned >1 times
94.78% overall alignment rate
Segmentation fault (core dumped)
(ERR): bowtie2-align exited with value 139

Bowtie works as expected when using only one thread (-p 1).

What am I doing wrong?

**Comment by BenLangmead** [comment]
Thanks for this report.  We noticed this too (https://github.com/BenLangmead/bowtie2/pull/171) and just merged a fix yesterday.  The fix will be included in the next release, but if you'd like it sooner you can build from the current master branch.

**Comment by stevendavis** [comment]
@BenLangmead Thank you for the prompt reply.  May I ask what is the most recent official release without this problem?

**Comment by BenLangmead** [comment]
There is none yet

**Comment by stevendavis** [comment]
Let me ask this in a different way.  In which release was this problem introduced?

**Comment by BenLangmead** [comment]
I see, @ch4rr0 can you answer?

**Comment by ch4rr0** [comment]
This change was introduced in v2.3.4, however 2.3.4 fixed a major issue in prior versions whited caused corrupt SAM output when running using more than one thread. I think the solution here is to create a beta build until our next release is available. Let me know if that's something that interests you.

**Comment by stevendavis** [comment]
@ch4rr0 Thank you for the update.  Would it be possible to prepare a beta build with pre-built binaries?  We need a way be sure multiple computer systems have the same version installed.

**Comment by ch4rr0** [comment]
Here's is the [link](https://github.com/BenLangmead/bowtie2/releases/tag/v2.3.4.1-beta) to the beta build. Please let us know whether or not It resolves the issue.

**Comment by stevendavis** [comment]
@ch4rr0 The problem is fixed in the 2.3.4.1 beta .  Thank you very much for the rapid response.
