### ISSUE TITLE
v2.3.4.1 bowtie2 build:  No tbb/tbb.h or tbb/mutex.h file when making bowtie2-build-s?

### ISSUE THREAD

**Issue by katharinedickson** [BenLangmead/bowtie2#175]
I'm attempting to build Trinity 2.5.1 on my lab's computer and a problem's arisen with the installation.  I've managed to trace it to our Bowtie 2 installation, and I get this error message when I type 'make' in the directory in which I've unzipped the bowtie2 source .zip:

labcomputer@labcomputer-OptiPlex-7010:~/bowtie2-2.3.4.1$ make
g++ -O3 -m64 -msse2 -funroll-loops -g3 -DCOMPILER_OPTIONS="\"-O3 -m64 -msse2 -funroll-loops -g3 -std=c++98 -DPOPCNT_CAPABILITY -DWITH_TBB -DNO_SPINLOCK -DWITH_QUEUELOCK=1\"" -std=c++98 -DPOPCNT_CAPABILITY -DWITH_TBB -DNO_SPINLOCK -DWITH_QUEUELOCK=1 \
	-fno-strict-aliasing -DBOWTIE2_VERSION="\"`cat VERSION`\"" -DBUILD_HOST="\"`hostname`\"" -DBUILD_TIME="\"`date`\"" -DCOMPILER_VERSION="\"`g++ -v 2>&1 | tail -1`\"" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE  -DBOWTIE_MM  -DBOWTIE2 -DNDEBUG -Wall \
	-I third_party \
	-o bowtie2-build-s bt2_build.cpp \
	ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp edit.cpp bt2_idx.cpp bt2_io.cpp bt2_util.cpp reference.cpp ds.cpp multikey_qsort.cpp limit.cpp random_source.cpp diff_sample.cpp bowtie_build_main.cpp \
	 -lz -lpthread -ltbb -ltbbmalloc_proxy
In file included from bt2_idx.h:42:0,
                 from bt2_build.cpp:28:
blockwise_sa.h:24:21: fatal error: tbb/tbb.h: No such file or directory
compilation terminated.
In file included from ds.h:30:0,
                 from ref_read.h:33,
                 from ref_read.cpp:20:
threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
compilation terminated.
In file included from ds.h:30:0,
                 from edit.h:29,
                 from edit.cpp:21:
threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
compilation terminated.
In file included from bt2_idx.h:42:0,
                 from bt2_idx.cpp:25:
blockwise_sa.h:24:21: fatal error: tbb/tbb.h: No such file or directory
compilation terminated.
In file included from bt2_idx.h:42:0,
                 from bt2_io.cpp:25:
blockwise_sa.h:24:21: fatal error: tbb/tbb.h: No such file or directory
compilation terminated.
In file included from bt2_idx.h:42:0,
                 from bt2_util.cpp:26:
blockwise_sa.h:24:21: fatal error: tbb/tbb.h: No such file or directory
compilation terminated.
In file included from ds.h:30:0,
                 from ref_read.h:33,
                 from reference.h:32,
                 from reference.cpp:22:
threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
compilation terminated.
In file included from ds.h:30:0,
                 from ds.cpp:20:
threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
compilation terminated.
In file included from ds.h:30:0,
                 from sequence_io.h:28,
                 from multikey_qsort.h:24,
                 from multikey_qsort.cpp:20:
threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
compilation terminated.
In file included from ds.h:30:0,
                 from random_util.h:25,
                 from random_source.cpp:21:
threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
compilation terminated.
In file included from diff_sample.cpp:20:0:
diff_sample.h:24:21: fatal error: tbb/tbb.h: No such file or directory
compilation terminated.
In file included from ds.h:30:0,
                 from bowtie_build_main.cpp:25:
threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
compilation terminated.
Makefile:303: recipe for target 'bowtie2-build-s' failed
make: *** [bowtie2-build-s] Error 1

**Comment by ch4rr0** [comment]
Bowtie2 depends on the Thread Building Blocks library, TBB. As it appears in the output you've provided, you either do not have TBB installed on the host machine or the TBB library/headers are not included in your build environment's LD_LIBRARY_PATH/CPLUS_INCLUDE_PATH variables. If you are able to point Trinity to pre-built Bowtie 2 binaries we do [provide such binaries](https://github.com/BenLangmead/bowtie2/releases/download/v2.3.4.1/bowtie2-2.3.4.1-linux-x86_64.zip) with TBB statically linked that should be portable across almost all Linux flavors. If you absolutely require that Bowtie 2 be built from source then the options available to you are to:
1) Alter Trinity's build script for Bowtie 2 to include `NO_TBB=1` which will have Bowtie 2 default to pthreads (should be a standard system library)
2) Install TBB

**Comment by katharinedickson** [comment]
Ok, sounds good.  Thanks!

**Comment by holgerbrandl** [comment]
Imho this should be documented. Like in the repo README.md. E.g. on ubuntu tbb could be installed with `apt-get install -y libtbb-dev`

**Comment by vivekruhela** [comment]
Hello,

I am getting the same error of ` fatal error: tbb/mutex.h: No such file or directory` whenever I try to compile Bowtie2 in MinGW (via msys2 command prompt, as mentioned in bowtie2 documentation). I am trying to compile Bowtie2 in the windows10 operating system. I have attached the screenshot for the same. Kindly suggest how to deal with this issue. Thanks.
![image](https://user-images.githubusercontent.com/13174913/76405209-cc854700-63ad-11ea-8eb2-358993f38653.png)
