### ISSUE TITLE
bowtie2-build on gzip'ed files

### ISSUE THREAD

**Issue by nick-youngblut** [BenLangmead/bowtie2#181]
`bowtie2` works with gzip'ed files, but it appears that `bowtie2-build` does not (using version 2.2.6). For really large references, this uncompressing requirement can take up a ton of hard drive space. It would be great to all gzip'ed files for `bowtie2-build`

**Comment by BenLangmead** [comment]
This was added in v2.3.3

**Comment by nick-youngblut** [comment]
Great! Sorry to bug you!

**Comment by BenLangmead** [comment]
But now that I think of it, it probably simply uncompresses the file at the outset.  Is that right, @ch4rr0 ?

**Comment by BenLangmead** [comment]
(in other words, I think bowtie2-build may need to take multiple passes, and so cannot receive a stream of output from `gzip -dc`)

**Comment by nick-youngblut** [comment]
I'm using bowtie2 installed from bioconda, and the version for bowtie2 is 2.3.4.1, but the version for bowtie2-build is 2.2.6. At least with bowtie2-build v2.2.6, I just get the following when running bowtie2-build on gzip'ed fasta files: `Warning: Encountered empty reference sequence`.

When you say "v2.3.3", do you mean bowtie2 v2.3.3 or bowtie2-build v2.2.6?

**Comment by ch4rr0** [comment]
@BenLangmead -- Yes that is correct.

**Comment by ch4rr0** [comment]
Correction -- it does **not** decompress the entire input file from the outset, but instead uses `gzread` to obtain data from the file upon request.

**Comment by BenLangmead** [comment]
This should be addressed in the latest versions of Bowtie 2.  Please reopen if that's not he case.
