### ISSUE TITLE
undocumented/confusing behavior when --soft-clipped-unmapped-tlen comes before --local

### ISSUE THREAD

**Issue by odoublewen** [BenLangmead/bowtie2#197]
This command works: `bowtie2 --local --soft-clipped-unmapped-tlen`

But this `bowtie2 --soft-clipped-unmapped-tlen --local` results in:

```
WARNING: --soft-clipped-unmapped-tlen can only be set for local alignment... ignoring
```

This behavior is not documented, and surprising (they're not positional arguments, right?)  Named args should be parsed regardless of order supplied.  If this can't be done, then this should be a fatal ERROR -- user's supplied arguments should not be ignored.  Thanks!

```
/bioinfo_analysis/bin/bowtie2-align-s version 2.3.4.1
64-bit
Built on default-df05fd51-3d07-4109-abba-6883676f3ae8
Mon Jun 25 23:07:08 UTC 2018
Compiler: gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC) 
Options: -O3 -m64 -msse2 -funroll-loops -g3  -DBOOST_MATH_DISABLE_FLOAT128 -m64 -fPIC -std=c++98 -DPOPCNT_CAPABILITY -DWITH_TBB -DNO_SPINLOCK -DWITH_QUEUELOCK=1
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
```

**Comment by ch4rr0** [comment]
We addressed this issue in our most recent release, v2.3.4.2.
