### ISSUE TITLE
bowtie2.started’: No such file or directory

### ISSUE THREAD

**Issue by fynfyn** [BenLangmead/bowtie2#198]
Dear
When I type the command like the below: 

perl align_and_estimate_abundance.pl --transcripts ~/tools/trinityrnaseq-Trinity-v2.5.1/util/trinity/Trinity_Cleaned.fa --est_method RSEM --aln_method /home/bioinformatics1/tools/bowtie2 --trinity_mode --prep_reference --SS_lib_type RF --output prefix --debug --thread_count 20 

It shows  error  like this: 
CMD: touch /home/bioinformatics1/tools/trinityrnaseq-Trinity-v2.5.1/util/trinity/Trinity_Cleaned.fa./home/bioinformatics1/tools/bowtie2.started
touch: cannot touch ‘/home/bioinformatics1/tools/trinityrnaseq-Trinity-v2.5.1/util/trinity/Trinity_Cleaned.fa./home/bioinformatics1/tools/bowtie2.started’: No such file or directory

I don't know why?    Can someone help me to solve the problem?

**Comment by BenLangmead** [comment]
This looks like an issue with Trinity, not Bowtie 2.  Some trinity wrapper script is trying, but failing, to create a file indicating that alignment is in progress.

**Comment by fynfyn** [comment]
Thanks a lot! I will try to solve it.

**Comment by BenLangmead** [comment]
I'll close for now, but please reopen if it turns out to be a Bowtie 2 issue
