### ISSUE TITLE
NH tag

### ISSUE THREAD

**Issue by apredeus** [BenLangmead/bowtie2#200]
I've searched for a while, but all I find is very old threads with many confused people, so I figured I will ask here. 

Apparently, bowtie2 and bwa do not report NH tag, which supposed to label how many times do you see this particular read ID in the resulting alignment (as far as I understand). Normally I would say this is not a big deal since there is MAPQ fields, and you can filter your results if you need to. 

However, there is a specific case when it starts to matter quite a lot: bacterial RNA-seq. Since there's no splicing, people often tend to use a fast and robust genomic short-read aligner, like bowtie2. However, the downstream tools for RNA-seq analysis rely on NH tag - for example, featureCounts does. 

So, is there a specific reason bowtie2 does not report the NH tag? And is there an easy way to add it to the resulting SAM/BAM file? Thank you for any hints.

**Comment by BenLangmead** [comment]
The `NH:i` extra flag made more sense in the era of shorter reads, and Bowtie 1 does report `NH:i`.  In the era of longer reads (e.g. 100 nt), it became less sensible to make a binary distinction between repetitive (NH=1) non-repetitive (NH>1).  E.g. imagine a longer read with one perfect alignment and one alignment with a single mismatch at a low-quality base.  Should that be NH=1 or NH=2?  Hard to say.  What Bowtie 2 and BWA did instead -- as you point out -- is report MAPQ.  [MAPQ has its own problems](https://doi.org/10.1186/s13059-017-1290-3), but I think it's fair to say it does a better job than NH:i of expression the overall repetitiveness of the read for a variety of read lengths.

In light of this, I'm not sure of the best way to use Bowtie 2 in combination with featureCounts.  I would hope that featureCounts would know how to deal with either (a) MAPQ, or (b) output from Bowtie 2 using the `-k` option, which outputs more than one alignment per read.  Either of these are more general than `NH:i`, though `-k` makes the output bigger.

**Comment by apredeus** [comment]
Thank you for the complete answer and for the reference - that is a really cool paper. As far as featureCounts is concerned, accounting for multi-mapping reads is not their focus (and they do it in a very primitive way), but they do only consider "NH" tag - otherwise every BAM line is counted as a unique read. Unfortunately, using more sophisticated tools is very hard for bacteria, since annotation usually does not include UTRs (and thus things like kallisto/RSEM with bowtie would fail to align lots of reads). 

At any rate, thank you for you help!

**Comment by BenLangmead** [comment]
Sure thing, I'll close for now
