### ISSUE TITLE
bowtie2-inspect needs `import sys`

### ISSUE THREAD

**Issue by nieder** [BenLangmead/bowtie2#201]
When running `./bowtie2-inspect --version` from v2.3.4.2, I get this error:
````
$ ./bowtie2-inspect --version
Traceback (most recent call last):
  File "./bowtie2-inspect", line 83, in <module>
    main()
  File "./bowtie2-inspect", line 80, in main
    sys.exit(subprocess.call(argv))
NameError: global name 'sys' is not defined
````
If I add `import sys` to the top of ./bowtie-ins, then `./bowtie2-inspect --version` outputs correctly.
````diff
--- a/bowtie2-inspect	2018-08-07 14:24:25.000000000 -0500
+++ b/bowtie2-inspect	2018-08-15 05:40:17.000000000 -0500
@@ -21,6 +21,7 @@
 
 
 import os
+import sys
 import imp
 import inspect
 import logging
````

**Comment by Xiaohuaniu0032** [comment]
yeah, i just found the same error and came here to reflect this problem

**Comment by ch4rr0** [comment]
I have already committed a fix for this to the master branch. I am currently waiting until the end of the week to have it released. This will serve as a buffer in case additional issues come up with this release.

**Comment by pcantalupo** [comment]
I installed Bowtie2 with Conda (through bioconda channel) on a Mac OSX system. The version is 2.3.4.2 and I'm getting the bowtie2-inspect 'sys' error. How do I fix this on my system?  Thank you
