### ISSUE TITLE
TLEN is negative for both reads in a properly aligned read pair

### ISSUE THREAD

**Issue by brianyu2010** [BenLangmead/bowtie2#208]
This is an issue I've noticed with several different version of bowtie2. Under paired end sequencing configurations and when the insert size of the library is shorter than the sequencing read length, reads in both direction often go into adapters. After trimming the adapters off, both reads in a pair contain essentially the same sequence (different orientations). Under such circumstances, when performing bowtie2 alignments, TLEN for both reads end up receiving a negative sign. In the figure attached, I have included an example of a correctly assigned TLEN example and an incorrectly assigned TLEN example. I believe it is an edge case where both alignments are the left most and the right most alignments. However, since such edge cases are much more abundant now that read lengths can be longer on Illumina platforms, it may be useful to assign one as plus and one as minus using some random methods.
![insertsizeanalysis_figure6](https://user-images.githubusercontent.com/20360104/45976903-e043be80-bffc-11e8-945c-512fd2dd038b.png)

**Comment by ch4rr0** [comment]
We have committed a change to address this. The change will be part of an upcoming release.
