### ISSUE TITLE
bowtie2 runs in one core despite the --threads and despite the TBB libraries properly installed

### ISSUE THREAD

**Issue by anagtz** [BenLangmead/bowtie2#209]
Hi,

I am mapping reads towards a big metagenome assembly. Total of 2,848,663,973 bp and the bt2 index files weight:

530M C_contigs.1.bt2
388M C_contigs.2.bt2
2.7M  C_contigs.3.bt2
388M C_contigs.4.bt2
120M C_contigs.rev.1.bt2
86M  C_contigs.rev.2.bt2

on a server of 48 threads and 256G of RAM.

However when I launch bowtie with the following command:

`bowtie2 --threads 48 -x C_contigs  -1 C2.II_R1_paired.fq   -2 C2.II_R2_paired.fq  -S C_C2.II.sam  --no-unal`

it runs only in one thread, and the command that appears to be running is the wrapper bowtie2-align-s

This is weird, because this doesn't happen if I use the same command on the same server on smaller datasets.
This process can run for 8 days if I leave it like this (I haven't had the patience to leave it longer)

Is this normal? which is the pre-process that is running only in one core? i.e., what is the first process that the bowtie mapper runs? can this step be run in parallel? 

Thanks a lot,
Ana

**Comment by anagtz** [comment]
anyone?

**Comment by ch4rr0** [comment]
The wrapper chooses a binary to run based on the index given (`bowtie2-align-s` for small indexes `bowtie2-align-l` for large indexes). The bottleneck here might be the `--no-unal` flag which is a post-processing step done by the wrapper  (single threaded) after the reads get aligned. Could you try removing the `--no-unal` to see if that makes a difference?

**Comment by sheikki** [comment]
I have the same issue with prebuilt binaries and when I build from source, bowtie2-build, align, etc.

```
/usr/local/bin/bowtie2-align-s version 2.3.4.1
64-bit
Built on avaruus
Tue  3 Jul 15:17:51 EEST 2018
Compiler: gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) 
Options: -O3 -m64 -msse2 -funroll-loops -g3 -std=c++98 -DPOPCNT_CAPABILITY -DWITH_TBB -DNO_SPINLOCK -DWITH_QUEUELOCK=1
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
```

**Comment by anagtz** [comment]
In my case, I rebuilt the index files and that worked. The index files were maybe corrupted? I am not sure :/

**Comment by ch4rr0** [comment]
@sheikki -- can you share your command line and a snippet of `top` output showing the running bowtie2 process?

**Comment by mtojek** [comment]
@anagtz 

Bugs are in reading procedures which don't handle cases in which an input file is too short. MM_READ returns 0, which in fact means EOF, but the routine keeps reading until the expected end of file.

@BenLangmead
Do you need a PR for that?

**Comment by BenLangmead** [comment]
Aha!  -- yes, please -- very helpful indeed
