### ISSUE TITLE
Documentation: sensitive mode -L default value

### ISSUE THREAD

**Issue by stevendavis** [BenLangmead/bowtie2#215]
There are two sections of the documentation that have different default values for the -L option in sensitive mode.

http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#bowtie2-options-sensitive
Same as: -D 15 -R 2 -L 22 -i S,1,1.15 (default in --end-to-end mode)

http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#bowtie2-options-L
Default: the --sensitive preset is used by default, which sets -L to 20 both in --end-to-end mode and in --local mode.

Also, the default value of the -N option in sensitive mode is not documented.

As an aside, it would be helpful if verbose logging printed the values of all configurable parameters.

**Comment by skarunan** [comment]
Perhaps, a log file with all the values of params used would be helpful.

**Comment by ch4rr0** [comment]
I have updated the documentation for this on the 1`bug_fixes` branch. I plan on including the changes in the upcoming release.

> As an aside, it would be helpful if verbose logging printed the values of all configurable parameters.

I do agree with this and will have it planned for the future update.

Thank you.

**Comment by ch4rr0** [comment]
This change is available in v2.4.0 and later.
