### ISSUE TITLE
Error "Must specify at least one read input with -U/-1/-2"

### ISSUE THREAD

**Issue by nivekkagicom** [BenLangmead/bowtie2#220]
Specifying only an interleaved file on the bowtie2 align results in the error "Must specify at least one read input with -U/-1/-2" even though the syntax in the help suggests that it should be allowed "bowtie2 [options]* -x <bt2-idx> {-1 <m1> -2 <m2> | -U <r> | --interleaved <i>} [-S <sam>]". Is the syntax in the help incorrect or is the code incorrectly checking the input parameters and forgetting to include --interleaved as a valid read input?

**Comment by ch4rr0** [comment]
Can you post an example command that produces this error? Also, what version of bowtie 2 are you using?

**Comment by nivekkagicom** [comment]
Bowtie 2 version 2.3.4.3 by Ben Langmead (langmea@cs.jhu.edu, www.cs.jhu.edu/~langmea)

This is the command line I originally used; however, I do not have access to the original data so when I supply my own data I see:

`bowtie2 --threads 7 --sensitive-local -I 400 -X 800 --fr --gbar 4 --dovetail -x REF_3  --interleaved "TC_I.fq.gz" | samtools view -bS -F 4 -o REF_3.bam -
`
```
Warning: Output file 'TC_I.fq.gz' was specified without -S.  This will not work in future Bowtie 2 versions.  Please use -S instead.
(ERR): bowtie2-align died with signal 11 (SEGV) 
```
Not sure if the output file identified is the same as that specified in the --interleaved option though clearly the names are the same.

**Comment by nivekkagicom** [comment]
On further research it appears that the problem is that --interleaved paths contained spaces and despite being quoted in the command were not processed that way resulting in the confusion with -S. The original argument was

`--interleaved "/Users/kevin/Desktop/MacVector Data/spades/TC_I.fq.gz"`

And "Data/spades/TC_I.fq.gz" was not included in the file path for the --interleaved file.

Other options support spaces in the path when quoted. Can bowtie2 please handle quoted paths correctly?

**Comment by nivekkagicom** [comment]
The problem would seem to arise from the quote_params subroutine. Specifically, --interleaved is not the params_2_quote hash and thus does not get its arguments quoted. Simply adding the option to the hash has corrected all the issues I am seeing.

```
    my %params_2_quote = ('--rg' => 1, '--rg-id' => 1,
                          '-S' => 1, '-U' => 1,
                          '-1' => 1, '-2' => 1,
                          '-x' => 1, '--interleaved' => 1
    );
```

Please consider making this change for a future release of bowtie2. Thanks.

**Comment by ch4rr0** [comment]
I've committed this change to the `bug_fixes` branch. It will be part of our next release.
