### ISSUE TITLE
bowtie2-align died with signal 9 (KILL)

### ISSUE THREAD

**Issue by dcopetti** [BenLangmead/bowtie2#221]
Hello,

I am trying to run Bowtie2, but I run out of resources on my server. The error is the following:
`bowtie2-align died with signal 9 (KILL)`
and I get it when I try to align short reads to a "reference" of Oxford Nanopore reads (for error correction). The reference is 74 GB, NNN reads, obtained with
`bowtie2-build --threads 14 -q reference.fa reference.fa`
the alignment command is 
`bowtie2 --end-to-end -a -f -L 15 --mp 1,1 --np 1 --rdg 0,1 --rfg 0,1 --score-min L,0,-0.12 --no-unal -p 14 -x reference.fa  -U short.fasta > alignment_raw.sam`
I understand that it uses all the memory on my server (126 GB), and it does so even if I run it with 2 processors.
Is there a way to do the same alignment without requiring too much memory? Would splitting the reference help? (and then merge the bams) Or, what other options do I have to get the same sam file?
thanks,
Dario

**Comment by stanislasmorand** [comment]
Hi Dario,
I encountered a similar situation (when tyring to map a million of long nanopore reads onto a bacterial genome fasta reference sequence). I could use from 1 to 24 CPUs on my cluster but systematically run out of memory (after 30sec when using 24 CPUs and after 6 hours when using a single CPU) which is 132GB. 
I would be very interested on how to manage such nanpore reads w/ bowtie2 if you have found a solution.....
Cheers,
Stan

**Comment by dcopetti** [comment]
Hi Stan,

No, I did not find a solution to that. I just abandoned the option and went with another method
Sorry for not being of help

**Comment by stanislasmorand** [comment]
Hi Dario, I also switched toward another tool, the Graphmap tool, that can handle the mapping of  nanopore reads onto a fasta reference sequence. Cheers. Stan

**Comment by ch4rr0** [comment]
Apologies @dcopetti, @stanislasmorand -- some these memory related issues are very circumstantial and as such difficult to debug reliably. If you're trying to map short reads maybe [bowtie](https://github.com/BenLangmead/bowtie/) might be a better choice.

**Comment by stanislasmorand** [comment]
Dear ch4rro,
I agree, Bowtie2 works pretty well w/ Illumina reads. 
**Another question** : how Bowtie2 handle circular reference sequence (such as plasmid or bacterial chromosomes) ? Is there any option to specify in the commande line ? Or a trick to do such as performing a second round of remapping by shifting the nucleotide numbering and collect the new aligned reads? Lookind forward to receiving your input.
Cheers,
Stan

**Comment by BenLangmead** [comment]
If your reads are a predictable length (call it "r"), then you can mimic a circular genome by adding r - 1 of the bases from the beginning of the genome onto the end.  An alignment that includes any of those copied r - 1 bases is actually "wrapping" around the original string.

If the read is not a predictable length, I wouldn't recommend the same trick.  You would have to go by the maximum read length, but then some shorter reads would have spuriously repetitive alignments to the beginning and end of the genome.

I hope this helps

**Comment by sf202303** [comment]
Hi all, I had the same issue. I increased the maximum memory per node from 72 gb to 150gb and solved the issue. Hope this will be helpful.
