### ISSUE TITLE
Bowtie2-2.3.4.3 binaries for Windows

### ISSUE THREAD

**Issue by DmitriiSukhomlinov** [BenLangmead/bowtie2#224]
Dear developers,
Can you, please, provide a binary zip archive of the above-mentioned (2.3.4.3) version for Windows? I need exactly this binary and I've tried to build it for a few days already, but, unfourtunately, I didn't figure some problems out, so, I hope for your help!

Thanks!

**Comment by ch4rr0** [comment]
Hello,

I have updated the release to include Windows binaries.

**Comment by DmitriiSukhomlinov** [comment]
Thank you very much!
