### ISSUE TITLE
Reads with read length less than 22bp gets ignored in alignment

### ISSUE THREAD

**Issue by skarunan** [BenLangmead/bowtie2#230]
I recently updated my bowtie2 to version 2.3.4.3 from 2.2.5, and noticed that my alignment results vary significantly. To be specific, irrespective of the datasets I’ve tried, bowtie2 reported only alignment for reads with read length greater than or equal to 22bp. 

With the help of conda, I tried different version of bowtie2. And, I could see this issue had **started from version 2.3.2.** 

Command used:

`bowtie2 --local -k 100 -x NDgene -U test.fastq.gz -S test.sam
`
With the mentioned params, I see in the SAM file that reads with length <22bp as unaligned. 

However,  in version 2.3.4.3, instead of using `--local`, I tried using the default (`--sensitive-local`) mode values, and they report alignments for reads with length >17bp. I also tried playing around with different values of -L, -D, and -R, assuming discrepancies in the preset values. However, they reported alignments for reads with length >17bp, BUT performed only an end-to-end alignment. 

Why do I not get any alignments for reads with length <22 bp, when I use the '--local’ option from version 2.3.2? 
 
Could you please look in to the issue? If it is not an issue, perhaps you can point me to what I'm doing wrong.

Toy data, I used :
```
SeqData: https://github.com/SchulzLab/RAPID/blob/master/testData/test.fastq.gz
ReferenceSeq: https://github.com/SchulzLab/RAPID/blob/master/testData/NDgene.fa
```

Many thanks.

**Comment by ch4rr0** [comment]
Sorry for the late response on this. This difference in alignment was the result of [change](https://github.com/BenLangmead/bowtie2/commit/3b1631b1703e391a1616afdeac9892fc9505eae8) that we made to the scoring defaults when aligning in local mode. You can use the `--score-min` option to revert the the old behavior. For example:

```
./bowtie2 --local -k 100 -x NDgene -U test.fastq.gz -S test.sam --score-min G,1,10
```

Let me know if this works for you and once again apologies for the late response.

**Comment by skarunan** [comment]
No worries about the delay @ch4rr0 Thanks for the solution! It works with the options you suggested. 
I'm not sure, if this info is updated in the documentation. But, it would be nice to have it.
