### ISSUE TITLE
bowtie-2.3.4.3: does --interleaved allow STDIN and FASTA input?

### ISSUE THREAD

**Issue by mmokrejs** [BenLangmead/bowtie2#232]
Hi,
  I am trying to get bowtie2 running under abyss assembler (https://github.com/bcgsc/abyss/issues/283) and it seems either `-` for STDIN or `-f` are not accepted:

```
$ cat interleaved.fa | bowtie2-align-s --local -p2 -x $prefix.fa -f --interleaved - > a.sam
Error: reads file does not look like a FASTQ file
terminate called after throwing an instance of 'int'
Aborted
```

**Comment by ch4rr0** [comment]
`--interleaved` allows reading from `stdin, but does not serve as modifier for FASTA i.e. bowtie2 assumes that all read file arguments to `--interleaved` are FASTQ.

**Comment by ch4rr0** [comment]
Since we already did the foundational work to have `--interleaved` be independent for read format, I went ahead and added support for interleaved FASTA.
