### ISSUE TITLE
BOWTIE2_INDEXES environment variable not honored for large indexes

### ISSUE THREAD

**Issue by mykmaley** [BenLangmead/bowtie2#235]
If you export your index directory, the bowtie2 perl script fails to correctly resolve the index directory correctly after entering the large index conditionals.

Reproduce by exporting the index directory:
> [root@compute00 tmp]# BOWTIE2_INDEXES=/data/aligner/bowtie2/indexes/TRITICUM_AESTIVUM_L/chineseSpringWheat10
[root@compute00 tmp]# export BOWTIE2_INDEXES`

Then, when execute bowtie2: 
> [root@compute00 v9]# /tmp/bowtie2-2.3.4.3-linux-x86_64/bowtie2 --verbose --end-to-end --fast --mp 6 --np 1 --rdg 5,3 --rfg 5,3 --score-min L,-0.6,-0.6 --mm -x chineseSpringWheat10 -1 R1bq -2 R2bq -S out.sam`

This is the verbose output of it attempting to resolve the directory and failing:
> Applying preset: 'sensitive' using preset menu 'V0'
Applying preset: 'fast' using preset menu 'V0'
Final policy string: 'SEED=0;SEEDLEN=22;DPS=15;ROUNDS=2;IVAL=S,1,1.15;MMP=Q,6;NP=C1;RDG=5,3;RFG=5,3;MIN=L,-0.6,-0.6;SEED=0;SEEDLEN=22;DPS=10;ROUNDS=2;IVAL=S,0,2.50'
Input bt2 file: "chineseSpringWheat10"
Query inputs (DNA, FASTQ):
Quality inputs:
Output file: "out.sam"
Local endianness: little
Sanity checking: disabled
Assertions: disabled
Entered driver(): 11:13:34
Creating PatternSource: 11:13:34
Opening hit output file: 11:13:34
About to initialize fw Ebwt: 11:13:34
Trying chineseSpringWheat10
  didn't work
Trying /data/aligner/bowtie2/indexes/TRITICUM_AESTIVUM_L/chineseSpringWheat10/chineseSpringWheat10
  didn't work
Could not locate a Bowtie index corresponding to basename "chineseSpringWheat10"
Error: Encountered internal Bowtie 2 exception (#1)
Command: /tmp/bowtie2-2.3.4.3-linux-x86_64/bowtie2-align-s --wrapper basic-0 --verbose --end-to-end --fast --mp 6 --np 1 --rdg 5,3 --rfg 5,3 --score-min L,-0.6,-0.6 --mm -x chineseSpringWheat10 -S out.sam -1 R1bq -2 R2bq
(ERR): bowtie2-align exited with value 1`

**Comment by ch4rr0** [comment]
I committed a fix for this issue, give it a try and let me know if it works for you.

**Comment by mykmaley** [comment]
Fantastic!  Thank you for the fix.

>[root@compute00 v9]# BOWTIE2_INDEXES=/data/aligner/bowtie2/indexes/TRITICUM_AESTIVUM_L/chineseSpringWheat10/
[root@compute00 v9]# export BOWTIE2_INDEXES
[root@compute00 v9]# /tmp/bowtie2-2.3.4.3-linux-x86_64/bowtie2-fixed --verbose --end-to-end --fast --mp 6 --np 1 --rdg 5,3 --rfg 5,3 --score-min L,-0.6,-0.6 --mm -x chineseSpringWheat10 -1 R1aa -2 R2aa -S out.sam
Applying preset: 'sensitive' using preset menu 'V0'
Applying preset: 'fast' using preset menu 'V0'
Final policy string: 'SEED=0;SEEDLEN=22;DPS=15;ROUNDS=2;IVAL=S,1,1.15;MMP=Q,6;NP=C1;RDG=5,3;RFG=5,3;MIN=L,-0.6,-0.6;SEED=0;SEEDLEN=22;DPS=10;ROUNDS=2;IVAL=S,0,2.50'
Input bt2l file: "chineseSpringWheat10"
Query inputs (DNA, FASTQ):
Quality inputs:
Output file: "out.sam"
Local endianness: little
Sanity checking: disabled
Assertions: disabled
Entered driver(): 14:01:14
Creating PatternSource: 14:01:14
Opening hit output file: 14:01:14
About to initialize fw Ebwt: 14:01:14
Trying chineseSpringWheat10
  didn't work
Trying /data/aligner/bowtie2/indexes/TRITICUM_AESTIVUM_L/chineseSpringWheat10//chineseSpringWheat10
  worked
  About to open input files: 14:01:14
Opening "/data/aligner/bowtie2/indexes/TRITICUM_AESTIVUM_L/chineseSpringWheat10//chineseSpringWheat10.1.bt2l"
Opening "/data/aligner/bowtie2/indexes/TRITICUM_AESTIVUM_L/chineseSpringWheat10//chineseSpringWheat10.2.bt2l"
  Finished opening input files: 14:01:14
  Memory-mapping input file 1: 14:01:14
  Memory-mapping input file 2: 14:01:14
  Reading header: 14:01:14
Headers:
    len: 14271578887
    bwtLen: 14271578888
    sz: 3567894722
    bwtSz: 3567894722
    lineRate: 7
    offRate: 4
    offMask: 0xfffffffffffffff0
    ftabChars: 10
    eftabLen: 20
    eftabSz: 160
    ftabLen: 1048577
    ftabSz: 8388616
    offsLen: 891973681
    offsSz: 7135789448
    lineSz: 128
    sideSz: 128
    sideBwtSz: 96
    sideBwtLen: 384
    numSides: 37165571
    numLines: 37165571
    ebwtTotLen: 4757193088
    ebwtTotSz: 4757193088
    color: 0
    reverse: 0
About to initialize rev Ebwt: 14:01:14
  About to open input files: 14:01:14
Opening "/data/aligner/bowtie2/indexes/TRITICUM_AESTIVUM_L/chineseSpringWheat10//chineseSpringWheat10.rev.1.bt2l"
Opening "/data/aligner/bowtie2/indexes/TRITICUM_AESTIVUM_L/chineseSpringWheat10//chineseSpringWheat10.rev.2.bt2l"
  Finished opening input files: 14:01:14
  Memory-mapping input file 1: 14:01:14
  Memory-mapping input file 2: 14:01:14
  Reading header: 14:01:14
Headers:
    len: 14271578887
    bwtLen: 14271578888
    sz: 3567894722
    bwtSz: 3567894722
    lineRate: 7
    offRate: 4
    offMask: 0xfffffffffffffff0
    ftabChars: 10
    eftabLen: 20
    eftabSz: 160
    ftabLen: 1048577
    ftabSz: 8388616
    offsLen: 891973681
    offsSz: 7135789448
    lineSz: 128
    sideSz: 128
    sideBwtSz: 96
    sideBwtLen: 384
    numSides: 37165571
    numLines: 37165571
    ebwtTotLen: 4757193088
    ebwtTotSz: 4757193088
    color: 0
    reverse: 1
Dispatching to search driver: 14:01:14
  Memory-mapping reference index file /data/aligner/bowtie2/indexes/TRITICUM_AESTIVUM_L/chineseSpringWheat10//chineseSpringWheat10.4.bt2l: 14:01:14
Read 22 reference strings from 693050 records: 14:01:14
  About to open input files: 14:01:14
Opening "/data/aligner/bowtie2/indexes/TRITICUM_AESTIVUM_L/chineseSpringWheat10//chineseSpringWheat10.1.bt2l"
Opening "/data/aligner/bowtie2/indexes/TRITICUM_AESTIVUM_L/chineseSpringWheat10//chineseSpringWheat10.2.bt2l"
  Finished opening input files: 14:01:14
  Memory-mapping input file 1: 14:01:14
  Memory-mapping input file 2: 14:01:14
  Reading header: 14:01:14
Reading rstarts (2079150): 14:01:14
Reading fchr (5)
Reading ftab (1048577): 14:01:14
Reading eftab (20): 14:01:14
Reading offs (89197368164-bit words): 14:01:14
Headers:
    len: 14271578887
    bwtLen: 14271578888
    sz: 3567894722
    bwtSz: 3567894722
    lineRate: 7
    offRate: 4
    offMask: 0xfffffffffffffff0
    ftabChars: 10
    eftabLen: 20
    eftabSz: 160
    ftabLen: 1048577
    ftabSz: 8388616
    offsLen: 891973681
    offsSz: 7135789448
    lineSz: 128
    sideSz: 128
    sideBwtSz: 96
    sideBwtLen: 384
    numSides: 37165571
    numLines: 37165571
    ebwtTotLen: 4757193088
    ebwtTotSz: 4757193088
    color: 0
    reverse: 0
Ebwt (memory):
    zOff: 6262197675
    zEbwtByteOff: 2087399210
    zEbwtBpOff: 3
    nPat: 22
    plen: non-NULL, [0] = 594102056
    rstarts: non-NULL, [0] = 0
    ebwt: non-NULL, [0] = A
    fchr: non-NULL, [0] = 0
    ftab: non-NULL, [0] = 0
    eftab: non-NULL, [0] = 309832733
    offs: non-NULL, [0] = 6064168896
  About to open input files: 14:01:14
Opening "/data/aligner/bowtie2/indexes/TRITICUM_AESTIVUM_L/chineseSpringWheat10//chineseSpringWheat10.rev.1.bt2l"
  Finished opening input files: 14:01:14
  Memory-mapping input file 1: 14:01:14
  Reading header: 14:01:14
Reading rstarts (2079150): 14:01:14
Reading fchr (5)
Reading ftab (1048577): 14:01:14
Reading eftab (20): 14:01:14
Headers:
    len: 14271578887
    bwtLen: 14271578888
    sz: 3567894722
    bwtSz: 3567894722
    lineRate: 7
    offRate: 4
    offMask: 0xfffffffffffffff0
    ftabChars: 10
    eftabLen: 20
    eftabSz: 160
    ftabLen: 1048577
    ftabSz: 8388616
    offsLen: 891973681
    offsSz: 7135789448
    lineSz: 128
    sideSz: 128
    sideBwtSz: 96
    sideBwtLen: 384
    numSides: 37165571
    numLines: 37165571
    ebwtTotLen: 4757193088
    ebwtTotSz: 4757193088
    color: 0
    reverse: 1
Ebwt (memory):
    zOff: 6228329538
    zEbwtByteOff: 2076109840
    zEbwtBpOff: 2
    nPat: 22
    plen: non-NULL, [0] = 594102056
    rstarts: NULL
    ebwt: non-NULL, [0] = !
    fchr: non-NULL, [0] = 0
    ftab: non-NULL, [0] = 0
    eftab: non-NULL, [0] = 327120872
    offs: NULL
1 reads; of these:
  1 (100.00%) were paired; of these:
    0 (0.00%) aligned concordantly 0 times
    0 (0.00%) aligned concordantly exactly 1 time
    1 (100.00%) aligned concordantly >1 times
    ----
    0 pairs aligned concordantly 0 times; of these:
      0 (0.00%) aligned discordantly 1 time
    ----
    0 pairs aligned 0 times concordantly or discordantly; of these:
      0 mates make up the pairs; of these:
        0 (0.00%) aligned 0 times
        0 (0.00%) aligned exactly 1 time
        0 (0.00%) aligned >1 times
100.00% overall alignment rate
