### ISSUE TITLE
Patch to build on aarch64

### ISSUE THREAD

**Issue by junaruga** [BenLangmead/bowtie2#238]
This ticket is a task note.
Right now we need to run below 4 `sed` commands to build `bowtie2` on aarch64.

https://github.com/BenLangmead/bowtie2/blob/v2.3.5/Dockerfile-aarch64#L24-L27

```
sed -i 's/__m/simde__m/g' aligner_*
sed -i 's/__m/simde__m/g' sse_util*
sed -i 's/_mm_/simde_mm_/g' aligner_*
sed -i 's/_mm_/simde_mm_/g' sse_util*
```

I like the logic is included in the source code level.
The difference between before and after is like this.

aligner_swsse_ee_i16.cpp

```
-   __m128i z = _mm_setzero_si128(); \
-   __m128i tmp = _mm_setzero_si128(); \
-   z = _mm_xor_si128(z, z); \
-   tmp = _mm_cmpeq_epi16(x, z); \
-   assert_eq(0xffff, _mm_movemask_epi8(tmp)); \
+ simde__m128i z = simde_mm_setzero_si128(); \
+ simde__m128i tmp = simde_mm_setzero_si128(); \
+ z = simde_mm_xor_si128(z, z); \
+ tmp = simde_mm_cmpeq_epi16(x, z); \
+ assert_eq(0xffff, simde_mm_movemask_epi8(tmp)); \
```

```
-   rfgapo = _mm_insert_epi16(rfgapo, sc_->refGapOpen(), 0);
-   rfgapo = _mm_shufflelo_epi16(rfgapo, 0);
-   rfgapo = _mm_shuffle_epi32(rfgapo, 0);
+ rfgapo = simde_mm_insert_epi16(rfgapo, sc_->refGapOpen(), 0);
+ rfgapo = simde_mm_shufflelo_epi16(rfgapo, 0);
+ rfgapo = simde_mm_shuffle_epi32(rfgapo, 0);
```

Do you have an idea to implement this?

**Comment by sjaenick** [comment]
I'd suggest to wrap the code in question by some

```
#ifdef __aarch64__
#else
#endif
```
and submit a PR.

**Comment by ch4rr0** [comment]
We're planning a new release slated for the 04/15. Can you submit a PR before then?

**Comment by junaruga** [comment]
@ch4rr0 I submitted teh PR now!

**Comment by junaruga** [comment]
> We're planning a new release slated for the 04/15. Can you submit a PR before then?

@ch4rr0 today is the 04/15. I wish this PR is going to be merged.

**Comment by ch4rr0** [comment]
Sure. I'm still prepping a few more changes for the release, so go ahead.

**Comment by junaruga** [comment]
@ch4rr0 okay I thought you forgot merging the PR :)

**Comment by ch4rr0** [comment]
I didn't. I just haven't gotten around to merging the changes yet.

**Comment by junaruga** [comment]
Thank you for the working!

**Comment by ch4rr0** [comment]
Release date moved to 04/16. Sorry for the delay.
