### ISSUE TITLE
problems compiling on snow leopard MacOSX

### ISSUE THREAD

**Issue by pcantalupo** [BenLangmead/bowtie2#24]
Hello,

Just cloned bowtie2 to a Snow Leopard MacOSX with g++ from homebrew. After typing `make`, I get the following error:

```
$ make
/usr/local/homebrew/bin/g++ -O3 -m64 -msse2  -funroll-loops -g3 -DCOMPILER_OPTIONS="\"-O3 -m64 -msse2  -funroll-loops -g3 -DPOPCNT_CAPABILITY\"" -DPOPCNT_CAPABILITY \
                -fno-strict-aliasing -DBOWTIE2_VERSION="\"`cat VERSION`\"" -DBUILD_HOST="\"`hostname`\"" -DBUILD_TIME="\"`date`\"" -DCOMPILER_VERSION="\"`/usr/local/homebrew/bin/g++ -v 2>&1 | tail -1`\"" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE  -DBOWTIE_MM  -DBOWTIE2 -DNDEBUG -Wall \
                 -I third_party \
                -o bowtie2-build-s bt2_build.cpp \
                ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp edit.cpp bt2_idx.cpp bt2_io.cpp bt2_util.cpp reference.cpp ds.cpp multikey_qsort.cpp limit.cpp random_source.cpp tinythread.cpp diff_sample.cpp bowtie_build_main.cpp \
                -lpthread
bt2_idx.h:449:suffix or operands invalid for `popcnt'
bt2_idx.h:449:suffix or operands invalid for `popcnt'
reference.cpp: In member function 'int BitPairReference::getStretch(uint32_t*, size_t, size_t, size_t) const':
reference.cpp:456:12: warning: variable 'origBufOff' set but not used [-Wunused-but-set-variable]
   uint64_t origBufOff = bufOff;
            ^
reference.cpp:450:7: warning: variable 'binarySearched' set but not used [-Wunused-but-set-variable]
  bool binarySearched = false;
       ^
make: *** [bowtie2-build-s] Error 1
```

Any ideas of what to try next? Thank you,
Paul

**Comment by val-antonescu** [comment]
Hi Paul,

Sorry about this, but we dropped the Snow Leopard support a while back. I would recommend to try an older version of bowtie2. Currently we are focused on Mavericks and planning to move on to Yosemite. 

thanks,
Val

**Comment by BenLangmead** [comment]
We haven't seen this before, but could be as simple as changing the following line:

```
            asm ("popcntq %[x],%[count]\n": [count] "=&r" (count): [x] "r" (x));
```

in `bt2_idx.h` to:

```
            asm ("popcnt %[x],%[count]\n": [count] "=&r" (count): [x] "r" (x));
```

I don't quite understand why, but your version of GNU assembler doesn't want to see a suffix on the end of the `popcnt` instruction.  If you try this and it works, please let us know and we might try to add a workaround for this.

Best,
Ben

**Comment by pcantalupo** [comment]
That worked! It successfully compiled and I tested some alignments. Thank you.

Paul

**Comment by BenLangmead** [comment]
Interesting!  Thanks for testing it.  Val and I will consider how to fix this for everyone.

Best,
Ben

**Comment by cutsort** [comment]
That single change also allows hisat-0.1.6-beta-source.zip to compile on Ubuntu 14.04.1 LTS.

**Comment by BenLangmead** [comment]
I'm reopening the issue since multiple people have reported it.  Val: can you suggest a solution?

Best,
Ben

**Comment by val-antonescu** [comment]
I do not have access to a Snow Leopard anymore and it is surprising to accept AT&T syntax but to not recognize the suffix extensions. Good news is though that the operands are both 64 bit integers (one an unsigned integer). So their size is already known. Removing the 'q' suffix seem safe to me in this situation.  I will update the code and test it and if passes the tests I will include this in the next release.

Val

**Comment by val-antonescu** [comment]
This will be available in the next release. I will close it for now. Many thanks to all that provides useful feedback about this.

Val
