### ISSUE TITLE
wildcard '*' character for input only works with comma in list

### ISSUE THREAD

**Issue by 0ct0puss** [BenLangmead/bowtie2#251]
The project I am doing has many input files. I had done one run where I specified the input file names using the wildcard '*' character to iterate over multiple files. As these were in three separate directories I had a list of file specifications. All worked well. The second run had a single directory with multiple files. Having single specifications containing wildcards each for the -1 and -2 options resulted in an error message saying that XXXX could not be opened for output and in future editions the -S flag needed to be used followed by a list of the remaining input files. Backing off a level and having a list (still with a wildcard character) solved the problem and all ran smoothly. The issue seems to be that without the comma the input is expected to be only a single file despite the presence of the wildcard?

Libby Guethlein, Stanford University

**Comment by ch4rr0** [comment]
I'll look into a fix for this today.

**Comment by ch4rr0** [comment]
I committed a [change](https://github.com/BenLangmead/bowtie2/commit/7d11912c7210f91dafdeaeb583f16cc7b7bdf8a1) to `bug_fixes` to do just that. Feel free to try it out and provide feedback.

**Comment by ch4rr0** [comment]
This change is available in v2.4.0 and later.
