### ISSUE TITLE
How is the MAPQ score calculated in local alignment mode?

### ISSUE THREAD

**Issue by FelixKrueger** [BenLangmead/bowtie2#252]
Dear Bowtie2-Team,

I am wondering how Bowtie 2 calculates its MAPQ values in local aligment mode. A few years ago, Devon Ryan posted a C implementation of the code employed by Bowtie2 in end-to-end mode [here](http://seqanswers.com/forums/showpost.php?p=119928&postcount=510), and there is also a [Python version](https://www.blogger.com/blogger.g?blogID=6625226809475407629), and we adapted this code for use in Bismark.

We recently added `--local` mode for both Bowtie2 and HISAT2 in Bismark, but if we use the same code we use for end-to-end mode, the MAPQ scores end up being either 0 or 2, while the same reads appear to have hight MAPQ scores in end-to-end mode. Would you be able to give me a clue or point me to the piece of code that does it?

Many thanks, Felix

**Comment by BenLangmead** [comment]
Hi Felix,

Good to hear from you!  The relevant code is in `unique.h`.  Specifically, I think the else block of the `if(sc_.monotone)` in `BowtieMapq2::mapq(...)` is the right place to look:

https://github.com/BenLangmead/bowtie2/blob/master/unique.h#L331

Does this sound right to you as well, @ch4rr0 ?

Best,
Ben

**Comment by FelixKrueger** [comment]
Perfect, this is exactly what I needed. Thanks for the incredibly fast reply! 

PS: Am I right to assume that HISAT2 is using the same code base for local alignments, or shall I ask separately over at their repo?

**Comment by BenLangmead** [comment]
My guess is that Daehwan probably implemented a new MAPQ calculation in HISAT2, given that the alignment algorithm is substantially different.  But yes, I suggest asking over in their repo.

**Comment by FelixKrueger** [comment]
Thanks again. Felix
