### ISSUE TITLE
Mapping Phred+64 encoded reads with Bowtie2

### ISSUE THREAD

**Issue by DenisGoryunov** [BenLangmead/bowtie2#253]
Hello,
I always used the following command line for reads mapping:
bowtie2 -p 15 --very-sensitive -x some_index1 -U R1.fastq -S file.sam
Everything worked well, there were not any errors. Recently i've realized that reads i used for mapping were Phred+64 encoded. I'm wondering if Bowtie2 can automatically determine Phred quality encoding of the reads? Otherwise why i did not get any error message after mapping?

Many thanks,
Denis

**Comment by BenLangmead** [comment]
Bowtie 2 does not have a feature to automatically determine Phred quality encoding.

I think you may also be the author of a BioStars post about the difference observed in alignment statistics between using `--phred64` and `--phred33` (https://www.biostars.org/p/381457/).  I would _not_ expect the alignment statistics to change much, consistent with what you report.  As far as the alignment algorithm is concerned, these parameters control what penalty to give to a mismatch.  The range of penalties is already constrained to be between 2 and 6 by default.  If you specify the "wrong" version of the `--phred` parameter, it will either have the effect of making the base qualities seem higher than they should (e.g. if they're 64-based but you specified 33-based) or much lower (vice versa).  In the first case, all penalties will be 6 and in the second they will all be 2.  In most cases, most of the reads have relatively few mismatches, and this difference alone won't drive very many below the min-score threshold.  That's my theory, but please feel free to post an issue if you see specific cases where Bowtie 2 is mis-scoring a mismatch.

**Comment by DenisGoryunov** [comment]
Hi Ben,
Thank you for your reply. I asked that for a very specific use case. I'm
running Bowtie2 within the Tassel5GBSv2Pipeline (
https://bitbucket.org/tasseladmin/tassel-5-source/wiki/Tassel5GBSv2Pipeline/Bowtie2andBWA
).
The recommended command line for Bowtie2 according to the pipeline
documentation is:

bowtie2 -p 15 --very-sensitive -x ../AGPv3/ZMAGP3_9103 -U tagsForAlign.fq
-S tagsForAlignFullvs.sam

However the file "tagsForAlign.fq" is quite specific, in particular it's
Phred64 encoded and all the bases within the file have the same "f" letter
in the quality string (please look at the example below).

@Seq=TGCAGCTTGCTGGTCATTGAGTGGAGCTGGGTCTTAGCCTTGAGATGGA
TGCAGCTTGCTGGTCATTGAGTGGAGCTGGGTCTTAGCCTTGAGATGGA
+
fffffffffffffffffffffffffffffffffffffffffffffffff
@Seq=TGCAGCTTGCTGGTCATTGAGTGGAGCTGGGTCTTAGCCTTGAGGTGGA
TGCAGCTTGCTGGTCATTGAGTGGAGCTGGGTCTTAGCCTTGAGGTGGA
+
fffffffffffffffffffffffffffffffffffffffffffffffff

If i'll use the above command line and will not include the --phred64 flag,
how will it influence the alignment score, reads mapping quality and other
mapping statistics ?

After small testing i can see that the 11th field of the SAM file is
Phred64 encoded.

Can you advise me please, if including  --phred64 flag is important for my
use case?

Many thanks,
Denis


вс, 26 мая 2019 г. в 14:29, Ben ***@***.***>:
