### ISSUE TITLE
Documentation for using `--sra-acc` is unclear

### ISSUE THREAD

**Issue by ababaian** [BenLangmead/bowtie2#255]
Thanks for the great package!

I'm building a pipeline to use bowtie2 to align data from the SRA and I'm finding the documentation for the `--sra-acc` command is a little unclear.

> Reads are SRA accessions. If the accession provided cannot be found  in local storage it will be fetched from the NCBI database. If you find  that SRA alignments are long running please rerun your command with the -p/--threads parameter set to desired number of threads.

What path is **local storage**? is it `~/ncbi/public/sra`? (The default for `prefetch` SRA files). Does it check whatever the download directory is defined by `prefetch` contains the SRA? Does it check the current directory?

Edit: For documentation, using a default installation of prefetch, the `~/ncbi/public/sra/` directory is looked up for 'local storage'. If you download your SRA files to another directory by setting up sratoolkit, it is unknown if bowtie2 will use the alternative dir or the default one.

**Comment by ch4rr0** [comment]
I understand your confusion. It would have been better if we said that user can either specify the name of the accession to be downloaded or the full pathname to the accession if already it's available locally. Deoes that make more sense.

**Comment by ababaian** [comment]
I think I understand how it works a bit better now. You don't have to specify the full pathname if you've already prefetched the sra file. If I put in just the `SRAXXXXX` and it's already downloaded to `~/ncbi/public/sra` then it will automatically detect. The only possible source of confusion is if my local installation of `prefetch` downloads to a directory that isn't the default `~/ncbi/public/sra/` then will it also still work  :thinking:

**Comment by ch4rr0** [comment]
I did some more testing since my last response and these are my findings:
* if you specify just the accession number the library will first check if that accession is available in the NCBI database. If it is, then it will stream the reads, else it try to find it in your current working directory.

* If you specify a pathname e.g. ~/ncbi/public/sra/SRA12345, in your case, then the library will simply try to find the accession there.

**Comment by ch4rr0** [comment]
If it's not in the standard prefetch location you will have the specify the full path name of the accession.

Sorry for all the edits. :(

**Comment by ch4rr0** [comment]
I did some futher research and found there is in fact a way to change your prefetch.
http://ncbi.github.io/sra-tools/install_config.html
