### ISSUE TITLE
Please port test scripts to python3

### ISSUE THREAD

**Issue by mestia** [BenLangmead/bowtie2#263]
As python2 reaches EOL soon, please update scripts to use python3.

**Comment by junaruga** [comment]
@mestia do you know how to fix it?

I received email mentioning about this issue page in Debian.
Did you write the message in Debian bug tracking system?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=936233

Right now `python` exists in below parts.
Do you like just replacing `python` with `python3`?

```
$ grep -r python *
Makefile:	echo "python %~dp0/bowtie2-build %*" >> bowtie2-build.bat
Makefile:	echo "python %~dp0/bowtie2-inspect %*" >> bowtie2-inspect.bat
bowtie2-build:#!/usr/bin/env python
bowtie2-inspect:#!/usr/bin/env python
scripts/test/benchmark/run.py:#!/usr/bin/env python
scripts/test/benchmark/samreader.py:#!/usr/bin/env python
scripts/test/benchmark/benchmarks.py:#!/usr/bin/env python
scripts/test/btdata.py:#!/usr/bin/env python
scripts/test/dataface.py:#!/usr/bin/env python
scripts/test/bt2face.py:#!/usr/bin/env python
scripts/test/README.md:    python scripts/test/regressions.py --verbose
scripts/test/README.md:    python scripts/test/large_idx.py --verbose
scripts/test/regressions.py:#!/usr/bin/env python
scripts/test/large_idx.py:#!/usr/bin/env python
scripts/sa.py:#!/usr/bin/env python
```

What `python` means python 2 or 3 depends on the environment.
For example, if you create a python virtual environment from python3. On the environment, python means Python 3.

I think you can simply replace `python` with `python3` by `sed -i 's/python/python3' <file>` in deb package's script file.

**Comment by mestia** [comment]
It has been fixed already. See: https://salsa.debian.org/med-team/bowtie2/blob/master/debian/patches/2to3.patch
Simply replacing python by python3 is not sufficient.

Best, 
Alex

**Comment by junaruga** [comment]
@mestia how did you test it to fix Python 2 specific issues?

Like below code in your patch file.

```
-    def next(self):
+    def __next__(self):
```

I assume you executed `bowtie2-*` commands and '*.py` files with some way.
This repository need to add it as unit tests to CI, to check if the Python2 issues are fixed.

**Comment by mestia** [comment]
@junaruga. There are no issues with python2 code. It is working. The problem is that python2 is supported only up to 2020. And thus it is recommended to update your python2 code to python3.
I used a tool called 2to3[0]  which helps migrating python2 code to python3.
[0] https://docs.python.org/2/library/2to3.html

**Comment by junaruga** [comment]
Note: seeing the popular python project's source code pip, even pip project does not change the shebang from python to python3.

```
git clone https://github.com/pypa/pip.git

cd pip

$ grep -r '#!/usr/bin/env python' *
src/pip/_internal/__init__.py:#!/usr/bin/env python
src/pip/_vendor/appdirs.py:#!/usr/bin/env python
src/pip/_vendor/requests/certs.py:#!/usr/bin/env python
src/pip/_vendor/chardet/cli/chardetect.py:#!/usr/bin/env python
Binary file tests/data/packages/script.wheel2a-0.1-py2.py3-none-any.whl matches
tests/data/src/compilewheel/setup.py:#!/usr/bin/env python
tests/data/src/simplewheel-1.0/setup.py:#!/usr/bin/env python
tests/data/src/pep518_with_extra_and_markers-1.0/setup.py:#!/usr/bin/env python
tests/data/src/pep518_missing_requires/setup.py:#!/usr/bin/env python
tests/data/src/pep518_invalid_requires/setup.py:#!/usr/bin/env python
tests/data/src/pep518_invalid_build_system/setup.py:#!/usr/bin/env python
tests/data/src/pep518_conflicting_requires/setup.py:#!/usr/bin/env python
tests/data/src/simplewheel-2.0/setup.py:#!/usr/bin/env python
tests/data/src/pep518-3.0/setup.py:#!/usr/bin/env python
```

**Comment by mestia** [comment]
According [debian-policy](https://www.debian.org/doc/packaging-manuals/python-policy/ch-programs.html) the "#!/usr/bin/env interpreter_name" shebang is deprecated. However it is also a valid one.

**Comment by junaruga** [comment]
The policy makes sense in the distribution world. Actually the policy exists in Fedora project too.
The reason is exactly to refer the system python (3) and the python deb packages certainly from a deb package.

What I want to say here is this policy does not mean to change the shebang in this repository (upstream code).

**Comment by mestia** [comment]
Sure, there is no need to change the shebang in this repository, but the changed shebang is not the only change made by `2to3` tool. There are other changes in the source code, which need to be applied to make the program work with python3. This issue is opened to inform the upstream about a problem and provides a possible solution. It will be useful if the problem is solved upstream, so we don't need to maintain the patch in Debian.

**Comment by junaruga** [comment]
Possibly you already do not need to maintain the 2to3 patch in Debian.

You can run following `sed` command to replace the shebang in the process of building bowtie2 deb package in Debian instead of the patch.

Then, does following command to run the tests work on your environment?

```
for file in $(find . -name "*.py") bowtie2-{build,inspect}; do
  sed -i '1s|/usr/bin/env python|/usr/bin/python3|' "${file}"
done

make allall
make simple-test
```

See https://github.com/BenLangmead/bowtie2/issues/207#issuecomment-571120145 .
I was succeeded to pass the tests on Python 3.8 and Python 3.4.

If it works on your environment, you already do not need to maintain the patch.

And in case of Fedora project, the '#!/usr/bin/env python' is checked as error in the RPM build common logic, each maintainer of the RPM has to fix it in each RPM spec file (recipe file).
Here is the common logic's line.
https://src.fedoraproject.org/rpms/redhat-rpm-config/blob/master/f/brp-mangle-shebangs#_146
And some shebang is replaced here. Each maintainer do not need to replace it on each RPM spec file.

**Comment by mestia** [comment]
You are right, bowtie2-{build,inspect} work both for py2 and py3. And the Makefile will not run the regression and large_idx tests which need porting to pyhton3. I am closing the issue as it is not that important. Thank you for your effort!

**Comment by junaruga** [comment]
> And the Makefile will not run the regression and large_idx tests which need porting to pyhton3.

Yeah, it seems that the `*.py` files in scripts directory do not work on python3.
And I think the files are for only internal use, and actually not released by `make installed`.
Your [2to3.patch](https://salsa.debian.org/med-team/bowtie2/blob/master/debian/patches/2to3.patch) has useful information to fix the files.
When maintainers run the scripts manually with python3, they might fix it.

**Comment by mmokrejs** [comment]
Please fix the python code to be executable by python3. Do not make other users and Linux distros to re-invent the wheel and apply some existing py2to3 patches.

Also, make it clear in README.md which python versions are supported, and which not (I care merely only about 2.7, 3.4, 3.5, 3.6, 3.7, 3.8). So, document current status first, then if the code gets changed (and it should), update the README.md as well.

Most distros are dropping python 2.7 as of now, and that is why this issue has been raised in Sept.

Thank you.

**Comment by ch4rr0** [comment]
I can get this done before the next release. I do have one question though. 
Is there some consensus on what the shebang should be set to, python, python3, python3.6?

**Comment by ch4rr0** [comment]
Nvm seems like python3 is the most common.

**Comment by junaruga** [comment]
There is a document about it.
https://www.python.org/dev/peps/pep-0394/

And on the Python project itself https://github.com/python/cpython , `#! /usr/bin/env python3` is the most common.

```
$ git clone https://github.com/python/cpython.git
$ cd cpython
$ find . -name "*.py" | xargs grep -h '^#!' | sort | uniq -c
      2 #! /usr/bin/env python
     58 #! /usr/bin/env python3
      1 #! /usr/local/bin/python
      3 #!%s
      1 #!./python
      6 #!/usr/bin/env python
     67 #!/usr/bin/env python3
      2 #!/usr/bin/python
      1 #!/usr/bin/python3
```

**Comment by ch4rr0** [comment]
Thanks @junaruga.

**Comment by mmokrejs** [comment]
From biopython https://github.com/biopython/biopython I would infer `#! /usr/bin/env python` , but `#! /usr/bin/env python3` is fine too, and more explicit.

**Comment by junaruga** [comment]
In case of the biopython, the result is like this. There is no one space after `#!`.

```
$ find . -name "*.py" | xargs grep -h '^#!' | sort | uniq -c
     66 #!/usr/bin/env python
      1 #!/usr/bin/env python3
```

**Comment by mmokrejs** [comment]
> In case of the biopython, the result is like this. There is no one space after #!.

But there should be a space, the file(1) utility looks at those first 4 chars. People tend to omit the space as they are unaware of its reasoning, but that doe snot mean we couldn't write it properly.

The https://en.wikipedia.org/wiki/Shebang_(Unix) where is speaks of this "Magic number" is not correct:

> It has been claimed that some old versions of Unix expect the normal shebang to be followed by a space and a slash (#! /), but this appears to be untrue;[citation needed] rather, blanks after the shebang have traditionally been allowed, and sometimes documented with a space (see the 1980 email in history section below). 

Nobody just bothered to dig the proper reference. Anyway, people installed a fallback years ago so that `#!/u` works too, but is not technically correct.

**Comment by junaruga** [comment]
> Nobody just bothered to dig the proper reference. Anyway, people installed a fallback years ago so that #!/u works too, but is not technically correct.

I did not know that. Thank you for sharing the info.

Just for your information, here is the biopython's situation about python2.
https://mailman.open-bio.org/pipermail/biopython/2020-January/016745.html
> Biopython 1.76 released 20 December 2019 was our last release to
support Python 2, although surprisingly the same day it was announced
that Python 2.7 got a last minute support extension until April 2020:

**Comment by junaruga** [comment]
> Is there some consensus on what the shebang should be set to, python, python3, python3.6?

For the topic, sorry for my repeating posts.

There is a plan for python 4.0.
http://charlesleifer.com/blog/new-features-planned-for-python-4-0/
The question is how to support both python3 and python4 in the future with a shebang?

**Comment by ch4rr0** [comment]
We will most likely support just python3 until that gets EOL'd since our python scripts are pretty static and mostly used for internal testing.

**Comment by ch4rr0** [comment]
I have push a [changeset](https://github.com/BenLangmead/bowtie2/commit/2942e0279f2ad2f50958dbc6e4df731ac78afcdc) to the `bug_fixes` branch that updates the scripts to python3. I opted for the `#!/usr/bin/env python3` shebang since that appears to be most portable variant.

**Comment by junaruga** [comment]
Alright. Thank you for updating the scripts to python3.

**Comment by junaruga** [comment]
I executed the tool `2to3` to replace Python 2 code with Python 3 code, for the current latest `bug_fixes` branch like this. `-w` is the option to writing option. Following result for `scripts/test/btdata.py` is false positive?

```
$ pwd
/home/jaruga/git/bowtie2

$ python3 ~/git/cpython/Tools/scripts/2to3 -w .

$ git diff
diff --git a/scripts/test/btdata.py b/scripts/test/btdata.py
index 17edb74..338f581 100755
--- a/scripts/test/btdata.py
+++ b/scripts/test/btdata.py
@@ -66,14 +66,14 @@ class LargeTestsData(object):
     def init_data(self):
         """ Try and init the data we need.
         """
-        for genome,gdata in self.genomes.items():
+        for genome,gdata in list(self.genomes.items()):
             gn_path  = os.path.join(self.data_dir_path,genome)
             gn_fasta = os.path.join(gn_path,gdata['ref_name'])
             if not os.path.exists(gn_fasta):
                 self._get_genome(genome)
                 self._build_genome(genome)
         
-        for genome,gdata in self.joint_genomes.items():
+        for genome,gdata in list(self.joint_genomes.items()):
             gn_path  = os.path.join(self.data_dir_path,genome)
             gn_fasta = os.path.join(gn_path,gdata['ref_name'])
             if not os.path.exists(gn_fasta):
```

And you might need to replace `python` with `python3` in `Makefile` too, seeing following result and [Debian bowtie2 project's 2to3.patch file](https://salsa.debian.org/med-team/bowtie2/blob/master/debian/patches/2to3.patch).

```
$ grep -r python *
bowtie2-build:#!/usr/bin/env python3
bowtie2-inspect:#!/usr/bin/env python3
Makefile:	echo "python %~dp0/bowtie2-build %*" >> bowtie2-build.bat
Makefile:	echo "python %~dp0/bowtie2-inspect %*" >> bowtie2-inspect.bat
scripts/sa.py:#!/usr/bin/env python3
scripts/test/README.md:    python3 scripts/test/regressions.py --verbose
scripts/test/README.md:    python3 scripts/test/large_idx.py --verbose
scripts/test/regressions.py:#!/usr/bin/env python3
scripts/test/btdata.py.bak:#!/usr/bin/env python3
scripts/test/large_idx.py:#!/usr/bin/env python3
scripts/test/btdata.py:#!/usr/bin/env python3
scripts/test/dataface.py:#!/usr/bin/env python3
scripts/test/benchmark/run.py:#!/usr/bin/env python3
scripts/test/benchmark/samreader.py:#!/usr/bin/env python3
scripts/test/benchmark/benchmarks.py:#!/usr/bin/env python3
scripts/test/bt2face.py:#!/usr/bin/env python3
```

**Comment by ch4rr0** [comment]
I’ll have those fixed first thing tomorrow.

**Comment by ch4rr0** [comment]
This was done in v2.4.0
