### ISSUE TITLE
Bad file descriptor error

### ISSUE THREAD

**Issue by rchavez-langebio** [BenLangmead/bowtie2#264]
Hi. When running a bowtie2, version 2.3.5.1, alignment of paired-end reads with multiple fastq files I get this message:
stat: Bad file descriptor
Warning: Could not open read file "/path/file_1.fastq.gz" for reading; skipping...
stat: Bad file descriptor
Warning: Could not open read file "/path/file_2.fastq.gz" for reading; skipping...
followed by the alignment summary.
It appears that file_1 and file_2 are always the first files in the comma separated list of fastqs. Files are ok and individual pairs of fastqs align ok.

**Comment by ch4rr0** [comment]
Are you including spaces before/after the comma separating the files? Example:
`./bowtie2-align-s -x /path/to/index  -1 /path/to/read_1_0.fq, /path/to/read_1_1.fq -2 /path/to/read_2_0.fq ,/path/to/read_2_1.fq`

**Comment by rchavez-langebio** [comment]
I'm sorry and embarrassed... Path to file was incorrect. I think what threw me off is that bowtie didn't print a "No such file or directory" message. Please close this issue.
