### ISSUE TITLE
What's the meaning of MAPQ 255 in sam file?

### ISSUE THREAD

**Issue by MrDigest0305** [BenLangmead/bowtie2#267]

**Comment by MrDigest0305** [comment]
Hey,

I use bowtie2 for mapping with parameters "-p 12 -N 1 --local -k 2 --no-unal --qc-filter" when aligning either single- or pair-end NGS data. I find the MAPQ value sometimes equals 255 in my sam files.

There is no explanation about this on bowtie2 manual(http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml) and only a SAM format link attached. In 'Sequence Alignment/Map Format Specification', it says '3. No alignments should be assigned mapping quality 255'. This makes me confused. Since I have used '--no-unal' parameter in aligning, there should be no ummapped reads in my SAM file but according to the SAM format, the MAPQ 255 means the reads aren't mapped. 

So I want to know what's the meaning of MAPQ value 255 in bowite2 and whether I should keep the reads with MAPQ value 255?

Thanks!

**Comment by ch4rr0** [comment]
Bowtie2 does not consider MAPQ when `-k` or `-a` is specified. Unfortunately this detail is not well documented, but we do plan on updating the manual in a subsequent release.

**Comment by jggatter** [comment]
Hi @ch4rr0, could you elaborate on why Bowtie2 does not assign MAPQ values for secondary alignments? My research involves finding the top alignments to two subregions variants of a gene and having MAPQ for all secondary alignments could additionally be beneficial in filtering out alignments/reads.

**Comment by BenLangmead** [comment]
Since the secondary alignments are by definition not the "best", the MAPQ is bound to be very low.  So the problem of how to calculate it correctly never got much attention.  That said, the AS:i field, which gives the alignment score, should be useful for your task of finding top alignments even among the secondary alignments.
