### ISSUE TITLE
How to get alignments with max gap/mismatch number

### ISSUE THREAD

**Issue by alp78** [BenLangmead/bowtie2#268]
I'm trying to find a proper way to get a very simple result: allow a max gap/mismatch number for an alignment of a short sequence against multiple reference sequences, disregarding any scoring factors and gap/mismatch positions.

use case:
primer: gagtcaaagaaaggggtgacgga

all fasta records against which I align this sequence are in a file called 'recs.fasta' and contain sequences of about 6000bp

I run the following commands:
1) bowtie2-build recs.fasta recs_ref
2) bowtie2 --very-sensitive-local -a -x recs_ref primer.fq > primer_bowtie.sam

in the SAM I only get full matches. I tried to tweak the cumbersome scoring system without getting anywhere. I need to get all alignments that have less than 3 mismatch/gap. Where and how the gaps/mismatches occur is not important, start/end/middle/open/extend, all the same, just 3 max possible gaps/mismatches compared to the reference sequence. 

Is there a way to get this result?

related posts are not explaining how to get to it: 
https://www.biostars.org/p/75438/
http://seqanswers.com/forums/showthread.php?t=19729

I should get a list of matches in the range XM:i:0 - XM:i:3

**Comment by ch4rr0** [comment]
Bowtie may be a better choice here since you're trying to align short reads.
Using the following command line should get you the results you need:

`./bowtie recs_ref -q primer.fq -a -v3 -S`

where `-v <int>`: report end-to-end hits w/ <=v mismatches; ignore qualities
