### ISSUE TITLE
blockwise_sa.h:24:10: fatal error: tbb/tbb.h: No such file or directory

### ISSUE THREAD

**Issue by MahejabeenNidhi** [BenLangmead/bowtie2#282]
I am working from a mysy environment. the directory to the source appears to be okay because 
/c/users/Kevin/Downloads/bowtie2-2.4.1-source/bowtie2-2.4.1
I was trying to run make, but I got the following errors
$ make
g++ -O3 -msse2 -funroll-loops -g3 -DCOMPILER_OPTIONS="\"-O3 -msse2 -funroll-loops -g3 -DPOPCNT_CAPABILITY -DWITH_TBB -std=c++11 -DNO_SPINLOCK -DWITH_QUEUELOCK=1 -static-libgcc -static-libstdc++\"" -DPOPCNT_CAPABILITY -DWITH_TBB -std=c++11 -DNO_SPINLOCK -DWITH_QUEUELOCK=1 -static-libgcc -static-libstdc++ \
                -fno-strict-aliasing -DBOWTIE2_VERSION="\"`cat VERSION`\"" -DBUILD_HOST="\"\"" -DBUILD_TIME="\"`date -u`\"" -DCOMPILER_VERSION="\"`g++ -v 2>&1 | tail -1`\"" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE    -DBOWTIE2 -DNDEBUG -Wall \
                -I third_party \
                -o bowtie2-build-s bt2_build.cpp \
                ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp edit.cpp bt2_idx.cpp bt2_io.cpp bt2_util.cpp reference.cpp ds.cpp multikey_qsort.cpp limit.cpp random_source.cpp diff_sample.cpp bowtie_build_main.cpp \
                 -lz  -ltbb -ltbbmalloc_proxy
In file included from bt2_idx.h:42,
                 from bt2_build.cpp:28:
blockwise_sa.h:24:10: fatal error: tbb/tbb.h: No such file or directory
   24 | #include <tbb/tbb.h>
      |          ^~~~~~~~~~~
compilation terminated.
In file included from ds.h:30,
                 from ref_read.h:33,
                 from ref_read.cpp:20:
threading.h:30:11: fatal error: tbb/spin_mutex.h: No such file or directory
   30 | # include <tbb/spin_mutex.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ds.h:30,
                 from edit.h:29,
                 from edit.cpp:21:
threading.h:30:11: fatal error: tbb/spin_mutex.h: No such file or directory
   30 | # include <tbb/spin_mutex.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from bt2_idx.h:42,
                 from bt2_idx.cpp:25:
blockwise_sa.h:24:10: fatal error: tbb/tbb.h: No such file or directory
   24 | #include <tbb/tbb.h>
      |          ^~~~~~~~~~~
compilation terminated.
In file included from bt2_idx.h:42,
                 from bt2_io.cpp:25:
blockwise_sa.h:24:10: fatal error: tbb/tbb.h: No such file or directory
   24 | #include <tbb/tbb.h>
      |          ^~~~~~~~~~~
compilation terminated.
In file included from bt2_idx.h:42,
                 from bt2_util.cpp:26:
blockwise_sa.h:24:10: fatal error: tbb/tbb.h: No such file or directory
   24 | #include <tbb/tbb.h>
      |          ^~~~~~~~~~~
compilation terminated.
In file included from ds.h:30,
                 from ref_read.h:33,
                 from reference.h:32,
                 from reference.cpp:22:
threading.h:30:11: fatal error: tbb/spin_mutex.h: No such file or directory
   30 | # include <tbb/spin_mutex.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ds.h:30,
                 from ds.cpp:20:
threading.h:30:11: fatal error: tbb/spin_mutex.h: No such file or directory
   30 | # include <tbb/spin_mutex.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ds.h:30,
                 from sequence_io.h:28,
                 from multikey_qsort.h:24,
                 from multikey_qsort.cpp:20:
threading.h:30:11: fatal error: tbb/spin_mutex.h: No such file or directory
   30 | # include <tbb/spin_mutex.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ds.h:30,
                 from random_util.h:25,
                 from random_source.cpp:21:
threading.h:30:11: fatal error: tbb/spin_mutex.h: No such file or directory
   30 | # include <tbb/spin_mutex.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from diff_sample.cpp:20:
diff_sample.h:24:10: fatal error: tbb/tbb.h: No such file or directory
   24 | #include <tbb/tbb.h>
      |          ^~~~~~~~~~~
compilation terminated.
In file included from ds.h:30,
                 from bowtie_build_main.cpp:25:
threading.h:30:11: fatal error: tbb/spin_mutex.h: No such file or directory
   30 | # include <tbb/spin_mutex.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [bowtie2-build-s] Error 1

**Comment by junaruga** [comment]
You need to install tbb and zlib library on your environment, or run `NO_TBB=1 make` to build without tbb. See http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#building-from-source .
