### ISSUE TITLE
Use of uninitialized value $bt2_args

### ISSUE THREAD

**Issue by brobr** [BenLangmead/bowtie2#289]
Hi. While trying out bowtie2 for mapping small RNAs to a fungal genome, this popped up on the terminal at the beginning of each run:

>Use of uninitialized value $bt2_args[17] in join or string at /usr/bin/bowtie2 line 423.
Use of uninitialized value $bt2_args[18] in join or string at /usr/bin/bowtie2 line 423.
Use of uninitialized value in exists at /usr/bin/bowtie2 line 81.
Use of uninitialized value in exists at /usr/bin/bowtie2 line 81.
Use of uninitialized value $bt2_args[17] in join or string at /usr/bin/bowtie2 line 459.
Use of uninitialized value $bt2_args[18] in join or string at /usr/bin/bowtie2 line 459.

It does not affect the alignment process as far as I can see.
For a series of mappings  bowtie is run from a bash script:
>for i in "${seqs[@]}"; do 
	echo "Processing ${i}"
	bowtie2 \\
	-p 4 \\
	-q \\
	-D 5 -R 2 -N 0 \\
	-L 12 \\
	-i S,1,1.15 \\
	--end-to-end \\
	--no-unal \\
	--un-gz $i-unmapped.fastq.gz \\
	-x $INDEX/index \\
	-U $SRC_DIR/$i-in.fastq \\
	-q \\
	-S $i-out.sam
done

Bowtie2 was compiled from source; on a 64 bit linux box with perl-5.30 and tbb-2020u2

**Comment by ch4rr0** [comment]
This is a known issue with the wrapper script, a fix for which has already been committed to the bug_fixes branch. I plan on having this change released soon.

**Comment by brobr** [comment]
Ok, fabulous; at least stuff is mapping very fast; thank you

**Comment by karolisr** [comment]
I am still getting the same error whenever I use the `--no-unal` option. Bowtie 2 version 2.4.1.

**Comment by ch4rr0** [comment]
This issue should be resolved in the most recent release, v2.4.2.

**Comment by brobr** [comment]
Ok. Thank you very much
