### ISSUE TITLE
ultrafast or ultra fast?

### ISSUE THREAD

**Issue by junaruga** [BenLangmead/bowtie2#291]
It's a small thing. When having a RPM packaging review for bowtie2, the reviewer mentioned the used word "ultrafast" in the document could be "ultra fast" based on the result of the following lint program.

```
bowtie2.src: W: spelling-error Summary(en_US) ultrafast -> ultra fast, ultra-fast, ultrasound
The value of this tag appears to be misspelled. Please double-check.
```

How do you think?
Thank you.

**Comment by BenLangmead** [comment]
I'm not wedded to the term, and think it could be replaced with "fast."  But ultrafast (without a hyphen) is not a misspelling and is commonly used to describe methods in optics, for example.  Examples can be found with google or google scholar.  It's also in the title of the Bowtie paper.

**Comment by junaruga** [comment]
Sure. Thank you for the explanation.
