### ISSUE TITLE
bowtie 2.4.1 unaligned output errors

### ISSUE THREAD

**Issue by lokapal** [BenLangmead/bowtie2#293]
Hello, developers!
I should report that options --un and/or --no-unal lead to unused variables warnings/errors. Old version (2.3.4.1) works flawlessly.

**Comment by StevenWingett** [comment]
I have encountered the same problem.  

I am using Bowtie2 (version 2.4.1) on CentOS Linux release 7.7.1908 (Core).  If I run Bowtie2 without the --no-unal command, everything runs fine:

[wingetts@headstone hicup_patches]$ /bi/apps/bowtie2/2.4.1/bowtie2 --very-sensitive -x /bi/scratch/Genomes/Human/GRCh38/Homo_sapiens.GRCh38 -U test_dataset/test_dataset1.fastq -S output.sam
99742 reads; of these:
  99742 (100.00%) were unpaired; of these:
    11554 (11.58%) aligned 0 times
    64512 (64.68%) aligned exactly 1 time
    23676 (23.74%) aligned >1 times
88.42% overall alignment rate


However, "uninitialized value" warnings are reported if I add the --no-unal flag (while keeping everything else the same):

[wingetts@headstone hicup_patches]$ /bi/apps/bowtie2/2.4.1/bowtie2 --very-sensitive -x /bi/scratch/Genomes/Human/GRCh38/Homo_sapiens.GRCh38 --no-unal -U test_dataset/test_dataset1.fastq -S output.sam
Use of uninitialized value $bt2_args[3] in join or string at /bi/apps/bowtie2/2.4.1/bowtie2 line 423.
Use of uninitialized value $bt2_args[4] in join or string at /bi/apps/bowtie2/2.4.1/bowtie2 line 423.
Use of uninitialized value in exists at /bi/apps/bowtie2/2.4.1/bowtie2 line 81.
Use of uninitialized value in exists at /bi/apps/bowtie2/2.4.1/bowtie2 line 81.
Use of uninitialized value $bt2_args[3] in join or string at /bi/apps/bowtie2/2.4.1/bowtie2 line 459.
Use of uninitialized value $bt2_args[4] in join or string at /bi/apps/bowtie2/2.4.1/bowtie2 line 459.
99742 reads; of these:
  99742 (100.00%) were unpaired; of these:
    11554 (11.58%) aligned 0 times
    64512 (64.68%) aligned exactly 1 time
    23676 (23.74%) aligned >1 times
88.42% overall alignment rate


There are fewer alignments in the SAM file after adding the --no-unal parameter, suggesting it is working.

Thanks for your assistance and maintaining Bowtie2.

Steven

**Comment by ch4rr0** [comment]
This one is a known issue and was addressed in the bug_fixes branch. I have gone ahead and made the changes available on the main branch for testing.

**Comment by jialiu232** [comment]
I have these warnings while using bowtie 2.4.1 too:  

Use of uninitialized value $bt2_args[6] in join or string at /opt/software/Bowtie2/2.4.1-GCC-9.3.0/bin/bowtie2 line 423.
Use of uninitialized value $bt2_args[7] in join or string at /opt/software/Bowtie2/2.4.1-GCC-9.3.0/bin/bowtie2 line 423.
Use of uninitialized value in exists at /opt/software/Bowtie2/2.4.1-GCC-9.3.0/bin/bowtie2 line 81.
Use of uninitialized value in exists at /opt/software/Bowtie2/2.4.1-GCC-9.3.0/bin/bowtie2 line 81.
Use of uninitialized value $bt2_args[6] in join or string at /opt/software/Bowtie2/2.4.1-GCC-9.3.0/bin/bowtie2 line 459.
Use of uninitialized value $bt2_args[7] in join or string at /opt/software/Bowtie2/2.4.1-GCC-9.3.0/bin/bowtie2 line 459.


I saved the unaligned sequences to a file with `--un` argument and aligned sequences to another file with `--al` argument. Should I ignore these warnings and trust the results from bowtie2 or are there anything else I need to do? Thanks

**Comment by ch4rr0** [comment]
> I have these warnings while using bowtie 2.4.1 too:  
>
>
> `Use of uninitialized value $bt2_args[6] in join or string at /opt/software/Bowtie2/2.4.1-GCC-9.3.0/bin/bowtie2 line 423.`  
> `Use of uninitialized value $bt2_args[7] in join or string at /opt/software/Bowtie2/2.4.1-GCC-9.3.0/bin/bowtie2 line 423.`  
> `Use of uninitialized value in exists at /opt/software/Bowtie2/2.4.1-GCC-9.3.0/bin/bowtie2 line 81.`  
> `Use of uninitialized value in exists at /opt/software/Bowtie2/2.4.1-GCC-9.3.0/bin/bowtie2 line 81.`  
> `Use of uninitialized value $bt2_args[6] in join or string at /opt/software/Bowtie2/2.4.1-GCC-9.3.0/bin/bowtie2 line 459.`  
> `Use of uninitialized value $bt2_args[7] in join or string at /opt/software/Bowtie2/2.4.1-GCC-9.3.0/bin/bowtie2 line 459.`  
>
>
> I saved the unaligned sequences to a file with `--un` argument and aligned sequences to another file with `--al` argument. Should I ignore these warnings and trust the results from bowtie2 or are there anything else I need to do? Thanks

Hello,

This issue was resolved in v2.4.2. As far as I remember the arguments to `--un`
and `--al` do contain the correct outputs, so the warnings can be ignored.
