### ISSUE TITLE
Question regarding Bowtie2 for metagenomics data.

### ISSUE THREAD

**Issue by Krithika-Bhuvan** [BenLangmead/bowtie2#298]
Hello, I have a question regarding application of Bowtie2 for metagenomics data.

I have created a reference fasta file with a list of 10 viruses of interest. 

Lets say I take one input sample containing a bunch of reads. When I run the Bowtie or Bowtie2 alignment algorithm on the input sample,  some reads are aligned to a genome, let's say Influenza A virus.  

Question - Would the same read be also included into alignment to the other viruses genomes or would those reads be excluded from further analysis? 

It would be great if you can give us more information about this. 

Thanks,
Krithika

**Comment by sleepvet** [comment]
I'm also looking for the answer of this issue

**Comment by BenLangmead** [comment]
All the sequences in the database would be treated equally, just like chromosomes of a single genome.  If you would like more than one valid alignment, you might use `-k`.  In that case, a read might align many times, including alignments to multiple genomes and/or multiple alignments to a given genome.
