### ISSUE TITLE
'S' CIGAR operator

### ISSUE THREAD

**Issue by brainfo** [BenLangmead/bowtie2#299]
when I use SNPsplit to on bowtie2 output bam files, it said that `Found CIGAR operations other than M, I, D or N: 'S'. Not allowed at the moment`
How do I specify parameters so that no 'S' reads in bam files?
Could I just filter the sam file to get alignments other than 'S' alignments? I'm not sure if bowtie2 has smarter ways to deal with specific types of alignments.
would `--end-to-end `  be the solution?
why 

> we don’t recommend "local" alignment mode for mapping of ChIP-seq data

?

**Comment by ch4rr0** [comment]
Yes, running end-to-end should get rid of the San since S indicates soft trimming which happens in ‘local’ mode.

**Comment by BenLangmead** [comment]
I'll close this for now; feel free to reopen if issue persists even with end-to-end mode
