### ISSUE TITLE
bowtie2-build: incorrect parsing of command line parameters

### ISSUE THREAD

**Issue by fplaza** [BenLangmead/bowtie2#307]
Hi,

Since commit e8e63ed340b85ece460b9af8b9b002720b8b215b, command line parameters are incorrectly parsed.

In the following command:
```
bowtie2-build --threads 32 ref.fna ref
```
'32' is considered as the reference name

**Comment by ch4rr0** [comment]
This issue should be fixed in our most recent version, v2.4.2. Please try it out and let us know.
