### ISSUE TITLE
Issue to fetch SRA accessions using the --sra-acc bowtie2 option

### ISSUE THREAD

**Issue by JustineCharon** [BenLangmead/bowtie2#308]
Hi,

The command --sra-acc doesn't recognize the SRA accessions anymore (remote access, I don't have them locally) with the following output error : "Warning: Could not access "SRRxxxxx" for reading; skipping...". 
It used to work well last week though...Any idea what could be wrong and how can I check the proper modules or versions are set up ? 

I currently use the sratoolkit v2.9.2 and bowtie2 v.2.3.5.1-sra

Thanks a lot in advance for your help,

Kind regards

Justine

**Comment by ch4rr0** [comment]
Hello,

I tried aligning reads from SRA using the very same package, and it worked fine for me. I used accession SRX4637787 for my testing. Are you still experiencing the issue? If so, is it possible to share the accession you are using?

**Comment by JustineCharon** [comment]
Hi,

Thnaks a lot for your early reply. I've just had a feedback from my HPC helpdesk, the issue actually comes from our cluster. Security parameters have been reinforced recently and seem to interfere with NCBI fetching... Sorry for that, your sra tool is great and works fine !

Cheers

Justine
