### ISSUE TITLE
Separate unpaired reads in output file?

### ISSUE THREAD

**Issue by jrede** [BenLangmead/bowtie2#309]
When specifying unpaired reads, the output is in a single file. is there a way to separate forward and reverse reads? Thank you.

**Comment by ch4rr0** [comment]
We currently do not have an option to do this directly, but you can try using
`--nofw`, `--norc`, and `--no-unal` to achieve something similar:

The below command will output reads that align to the reverse-complement of the reference.
`./bowtie2 -x example/index/lambda_virus example/reads/longreads.fq --nofw --no-unal`

The below command will output reads that align to the forward reference.
`./bowtie2 -x example/index/lambda_virus example/reads/longreads.fq --norc --no-unal`

Here's an explanation of the options from the manual.

>     --nofw/--norc
>
> If --nofw is specified, bowtie2 will not attempt to align unpaired reads
> to the forward (Watson) reference strand. If --norc is specified,
> bowtie2 will not attempt to align unpaired reads against the
> reverse-complement (Crick) reference strand. In paired-end mode, --nofw
> and --norc pertain to the fragments; i.e. specifying --nofw causes
> bowtie2 to explore only those paired-end configurations corresponding to
> fragments from the reverse-complement (Crick) strand. Default: both
> strands enabled.
