### ISSUE TITLE
Is there a maximum input size?

### ISSUE THREAD

**Issue by antgonza** [BenLangmead/bowtie2#311]
We are having issues getting some sequence alignments from an input file; basically bowtie2 is not any alignments for any sequences at the end of the file. It only returns alignments for those sequences at the top of the file. 

Note that our FNA file is a combined FNA with multiple samples based on the header: >sampleName_sequenceID. BTW, the reason we caught this is that we have gotten results from a similar run using an older version of bowtie2 (a). Just FYI, there are around 19 samples that we are missing alignments from the full run.

We are running bowtie2 [version see (b)] as follows:
```:bash:
$ bowtie2 -p 10 -x wol -f combined.fna -S output.sam --seed 42 --very-sensitive -k 16 --np 1 --mp "1,1" --rdg "0,1" --rfg "0,1" --score-min "L,0,-0.05" --no-head --no-unal
```
We tried 10 and 32 threads to test tentative multi-thread issues but we got the similar results.

Now, if we replace the input file with a smaller file containing the 19 missing samples + 1 that actually returned alignments in the full run, we get results for all of them. This made us wonder if the position of the samples/sequences in the original `combined.fna` file matter and all of them are at the _end_ of the file (last 4th).

Anyway, we are making available the files to reproduce this issue but I thought it might help opening this issue first in case there is an _expected_ maximum input size. In the meantime, the wol-database can be found here via Globus https://biocore.github.io/wol/download (55G) and the input files are:
- combined.fna [801G]: full
- combined_test.fna [95G]: smaller test

Thank you! 

==========================

(a) older version of bowtie2
$ bowtie2 --version
/home/qiita/miniconda3/envs/qp-shogun-0.1.7/bin/bowtie2-align-s version 2.3.5
64-bit
Built on default-9ec70d2b-0cae-4ef9-8b8a-41ee9710f4ef
Mon Apr  1 13:45:20 UTC 2019
Compiler: gcc version 7.3.0 (crosstool-NG 1.23.0.449-a04d0)
Options: -O3 -m64 -msse2 -funroll-loops -g3 -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/qiita/miniconda3/envs/qp-shogun-0.1.7/include -fdebug-prefix-map=/opt/conda/conda-bld/bowtie2_1554125862557/work=/usr/local/src/conda/bowtie2-2.3.5 -fdebug-prefix-map=/home/qiita/miniconda3/envs/qp-shogun-0.1.7=/usr/local/src/conda-prefix -std=c++98 -DPOPCNT_CAPABILITY -DWITH_TBB -DNO_SPINLOCK -DWITH_QUEUELOCK=1
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}

(b) current version of bowtie2
$ bowtie2 --version
/home/qiita/miniconda3/envs/qp-shogun-072020/bin/bowtie2-align-s version
64-bit
Built on
Sat Jun  6 20:17:22 UTC 2020
Compiler: gcc version 7.5.0 (crosstool-NG 1.24.0.123_1667d2b)
Options: -O3 -msse2 -funroll-loops -g3 -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/qiita/miniconda3/envs/qp-shogun-072020/include -fdebug-prefix-map=/opt/conda/conda-bld/bowtie2_1591474367590/work=/usr/local/src/conda/bowtie2-2.4.1 -fdebug-prefix-map=/home/qiita/miniconda3/envs/qp-shogun-072020=/usr/local/src/conda-prefix -DPOPCNT_CAPABILITY -DWITH_TBB -std=c++11 -DNO_SPINLOCK -DWITH_QUEUELOCK=1
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}

cc: @wasade, @qiyunzhu

**Comment by ch4rr0** [comment]
Thank you for the detailed issue @antgonza. There should not be any limits on the size of the read files that bowtie2 is able to process which leads me to believe that this issue is indeed a bug. 

Could you fix the links to the input files so I can start looking into this?

**Comment by antgonza** [comment]
@ch4rr0, thank you for looking into this! BTW great handle!

Anyway, we are currently making the files available here: ftp://ftp.microbio.me/dev_test/, they should be there soon, these are their md5s:
- combined.fna [801G]: c265b6ad7971c82817d2135f806ed5fd
- combined_test.fna [95G]: 85b644e2e9ba612305bf85eed28b1392

Also, after further review we realized that we have never had a fully successful run with input files larger of 600G (this is an estimation) and this is independent of the reference database so, _in theory_, you could use any DB and any large file to reproduce this issue.

**Comment by antgonza** [comment]
@ch4rr0, turns out that we can _not_ share the data publicly AKA via FTP but we can share it directly with you via a Globus endpoint; sorry for the inconvenience; would you mind sending me to antoniog at ucsd dot edu your GlobusID.

**Comment by ch4rr0** [comment]
@antgona -- unfortunately I don't have a Globus account, I will look into setting on up today.
