### ISSUE TITLE
Checksum change

### ISSUE THREAD

**Issue by sam-bassett** [BenLangmead/bowtie2#32]
Installing bowtie2 with Homebrew currently fails due to a mismatch between the SHA256 checksum recorded by the Homebrew team and the checksum produced by bowtie2-2.2.6:
```
==> Installing bowtie2 from homebrew/homebrew-science
==> Downloading https://github.com/BenLangmead/bowtie2/archive/v2.2.6.tar.gz
==> Downloading from https://codeload.github.com/BenLangmead/bowtie2/tar.gz/v2.2.6
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: fb4d09a96700cc929e8191659ee8509bb2f19816235322d1f012338d4a177358
Actual: 06d584040d9ce457873c59e4a5889aafe1a5f74ada207793335765d7abdf4eeb
Archive: /Library/Caches/Homebrew/bowtie2-2.2.6.tar.gz
To retry an incomplete download, remove the file above.
```

Is this intended? We just need to get confirmation before changing the checksum on our side.

**Comment by val-antonescu** [comment]
Yes, we confirm the checksums are changed. We had to do a terrible thing and changed the whole repo history. We apologize for the trouble we created downstream but it was no other way around it.

sorry again,
Val

**Comment by sam-bassett** [comment]
Thanks Val, the change has now been made on our end.
