### ISSUE TITLE
Print Only Alignment Summary

### ISSUE THREAD

**Issue by jrede** [BenLangmead/bowtie2#320]
I'm assembling transcriptomes and am trying to map my reads back to my contigs using bowtie2. Is there a way to only print the summary statistics or ignore alignment information? Otherwise summary file is hundreds of gigs. Thanks for any help!

**Comment by ch4rr0** [comment]
`./bowtie2 -x example/index/lambda_virus example/reads/longreads.fq > /dev/null`

This command will redirect standard output, the alignments, to /dev/null outputting only standard error, the alignment summary, to the terminal. I hope this helps.
