### ISSUE TITLE
How to convert mapped reads from Sam to Bam format?

### ISSUE THREAD

**Issue by bioramg** [BenLangmead/bowtie2#324]
Hi, 
I mapped both Illumina and ONT reads with reference sequences using Bowtie2 and having in Sam format. I would like to covert Sam to Bam format of mapped reads. I can able to see only for unmapped reads. So, how can I convert mapped_reads.sam --> mapped_reads.bam?

Could you please help me?
Thank you.

**Comment by ch4rr0** [comment]
You can use `samtools` to achieve this. We have an example in the [bowtie2 manual](http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#using-samtoolsbcftools-downstream).
