### ISSUE TITLE
Outdated commands in `Getting Started` @ Sourceforge page

### ISSUE THREAD

**Issue by goekce** [BenLangmead/bowtie2#325]
The commands for variant calling seem to be outdated in [Getting Started page in SF](http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#using-samtoolsbcftools-downstream)

For example:

```
$ samtools mpileup -uf /opt/bowtie2/example/reference/lambda_virus.fa paired-end.sorted.bam

[warning] samtools mpileup option `u` is functional, but deprecated. Please switch to using bcftools mpileup in future.
[E::fai_build3_core] Failed to open FASTA index /opt/bowtie2/example/reference/lambda_virus.fa.fai : Permission denied
```

**Comment by ch4rr0** [comment]
Thank you for pointing this out. I have updated the example in MANUAL.markdown and will update the remaining documentation in time for the next release.
