### ISSUE TITLE
How to run bowtie2 with only R1 data

### ISSUE THREAD

**Issue by samchrist12** [BenLangmead/bowtie2#331]
Hi,
I'm doing a genome analysis, I'm using bclconvert software to process my data and then I want to use bowtie2 for mapping.
The data I got from bclconvert was 4 fastq.gz file (L001, L002, L003, L004) R1 data for each genome sample and no R2 data produced from there.

How can I run bowtie2 to mapping the data with only R1 file.

Thanks.

**Comment by ch4rr0** [comment]
Hello,

I am assuming by "R1 data" you are referring to read 1 data. If so, you can align the reads
using Bowtie2's unpaired mode using the command:

`./bowtie2 -x <index> -U L001,L002,L003,L004`

Please let me know if this helps.

**Comment by samchrist12** [comment]
> Hello,
> 
> I am assuming by "R1 data" you are referring to read 1 data. If so, you can align the reads
> using Bowtie2's unpaired mode using the command:
> 
> `./bowtie2 -x <index> -U L001,L002,L003,L004`
> 
> Please let me know if this helps.

Hi @ch4rr0 thanks for replying, yes what I mean is read 1 data because our data only have 1 reads. I'll try it later and let you know if there is a problem. 

I'm planning to use the output from Bowtie2 for wisecondor and I need BAM file, from what I read in Bowtie2's documentation I need to convert the SAM file to BAM file using samtools later on. Am I right ?

**Comment by ch4rr0** [comment]
> > Hello,
> > 
> > I am assuming by "R1 data" you are referring to read 1 data. If so, you can align the reads
> > using Bowtie2's unpaired mode using the command:
> > 
> > `./bowtie2 -x <index> -U L001,L002,L003,L004`
> > 
> > Please let me know if this helps.
>
> Hi @ch4rr0 thanks for replying, yes what I mean is read 1 data because our data only have 1 reads. I'll try it later and let you know if there is a problem. 
>
> I'm planning to use the output from Bowtie2 for wisecondor and I need BAM file, from what I read in Bowtie2's documentation I need to convert the SAM file to BAM file using samtools later on. Am I right ?

Yes that is correct. You can use the command `samtools view -bS eg2.sam > eg2.bam` to do so.

**Comment by samchrist12** [comment]
Ok, thanks a lot @ch4rr0 !
