### ISSUE TITLE
Clarification of mate orientation following trimming

### ISSUE THREAD

**Issue by JaredTangeman** [BenLangmead/bowtie2#332]
Hello,
I am looking for clarification of the --fr (mate orientation) argument in a particular RNA-seq application when it is used in mapping to a transcriptome. The sequencing / library prep method I am using empoys an fr-firstrand Illumina paired-end approach (similar to dUTP method), so read 1 is always a downstream reverse compliment and read 2 is always an up-stream forward stranded alignment.

Thus, using this setup, --fr and --nofw would appear to be appropriate.

Due to an artifact of library preparation, I had to hard trim the first 10 bps from Read 2 in this data, making Read2 shorter than read 1. Thus, in the case where insert size is below the read length, mate 1 actually aligns <=10 bp upstream of mate 2 and is in reverse orientation, thus ostensibly breaking the --fr rule, which states for a valid alignment "mate 2 appears upstream of the reverse complement of mate 1" (or the opposite, "mate 1 appears upstream of the reverse complement of mate 2", which should not happen in my case since aligning to transcriptome and using --nofw).

Are --fr and --nofw still the appropriate parameters to use in this case, or will I be inadvertently discarding short fragments by using these?
Thanks in advance.

**Comment by ch4rr0** [comment]
Hello @JaredTangeman,

Yes, Bowtie2 allows this but only if you specify to `--dovetail` option. Please let us know if this helps.

``` text
And it's also possible, though unusual, for the mates to "dovetail",
with the mates seemingly extending "past" each other as in this example:

    Mate 1:                 GTCAGCTACGATATTGTTTGGGGTGACACATTACGC
    Mate 2:            TATGAGTCAGCTACGATATTGTTTGGGGTGACACAT
    Reference: GCAGATTATATGAGTCAGCTACGATATTGTTTGGGGTGACACATTACGCGTCTTTGAC

In some situations, it's desirable for the aligner to consider all these
cases as "concordant" as long as other paired-end constraints are not
violated. Bowtie 2's default behavior is to consider overlapping and
containing as being consistent with concordant alignment. By default,
dovetailing is considered inconsistent with concordant alignment.

These defaults can be overridden. Setting --no-overlap causes Bowtie 2
to consider overlapping mates as non-concordant. Setting --no-contain
causes Bowtie 2 to consider cases where one mate alignment contains the
other as non-concordant. Setting --dovetail causes Bowtie 2 to consider
cases where the mate alignments dovetail as concordant.
```

Thank you.
