### ISSUE TITLE
Very long runtime

### ISSUE THREAD

**Issue by evangeloo** [BenLangmead/bowtie2#334]
I am analyzing ChIP-seq data on my MacBook Pro. I recently trimmed the initial .fastq.gz files using trim_galore and paired-end settings, and am now trying to align the resulting .fq.gz files to the GRCm38 genome using bowtie2. However, I am experiencing a very long runtime; over 8 hours at this point. Is this because the size of my files are large? Is there any way to decrease runtime?

For reference, I used the indexed GRCm38 genome from http://bowtie-bio.sourceforge.net/bowtie2/index.shtml for the alignment. The trimmed .fq.gz files I am aligning contain ~60 million 150bp sequences and are ~5 GB in size. 

To use bowtie2, I used: bowtie2 -x /gscratch/anaconda3/GRCm39/GRCm39 -1 file_R1_val_1.fq.gz -2 file_R2_val_2.fq.gz -S file.sam

The output sam file is currently at 20GB, is this a normal size?

Thank you for your help!!

**Comment by ch4rr0** [comment]
Hello,

Bowtie2 has support for running with many threads using the `--threads/-p <n>` option. The output SAM file is usually about the same size as the sum of the _uncompressed_ read files assuming you have not provided any filtering options, e.g. `--no-unal`, or searching for multiple mappings, `-k/-a` options. I hope this helps.

**Comment by evangeloo** [comment]
Thank you so much, that greatly decreased runtime.
