### ISSUE TITLE
Locally aligned portion of read as the effective read length for --score-min.

### ISSUE THREAD

**Issue by JohnUrban** [BenLangmead/bowtie2#335]
Hi all,

Thanks for all your hard work on creating and maintaining bowtie2.

Bowtie2 has options/flags (`-i` and `--score-min`) that depend on read length (unless specified otherwise).

As a possible feature request, particularly for `--score-min`, it would be useful to have a flag/option that allows the user to use the read length minus the soft clipped bases in local mode as the effective read length for computing the minimum score. 

The use case is the following. There are many times I see people do adapter trimming before bowtie2. However, in local mode, bowtie2 can simply ignore the adapters with soft clipping. So the adapter trimming step is not necessary per se. BUT Bowtie2 treats the same genomic fragment differently in the adapter-trimmed vs adapter-containing state due to the difference in read length. Thus, if you have genomic fragments in the 22-29 bp range that have 40+ bp of adapter sequence at the 3' end, bowtie2 will align 100% of the adapter-trimmed versions, but much less of adapter-containing until fragments reach approximately 30 bp, at which point bowtie2 performs identically with adapter-free vs adapter-containing reads.

This can already be solved by using different parameters for `--score-min`. However, it does require using either a more promiscuous read-length dependent strategy or a read length independent strategy (e.g. `--score-min C,40,0`).

Rather than change `--score-min`, I think it would be great to have option called something like, `--use-local-read-length`, that computes the minimum score using the "effective local read length". Thus if it is a 25 bp genomic fragment with 50 bp of 3' adapter that is soft-clipped (read = 75 bp), `--use-local-read-length` would instruct bowtie2 to use 24 bp to compute the minimum score. Such an option would result in absolutely no difference between using the adapter-trimmed or adapter-containing reads described above.

Thanks for considering this.

Best,

John Urban

**Comment by BenLangmead** [comment]
@ch4rr0 and I spoke about this and we had to conclude that it wasn't something we could readily implement in Bowtie 2.  The problem is that the overall scoring function -- including the minimum score for a "valid" alignment -- has to be defined over the read.  We cannot (without big changes) refine the "scoring function" abstraction so that it's a function of a particular alignment, as we would need to do in order to make the change you suggest.  My general advice for your scenario is that trimming up-front, then handing trimmed reads to Bowtie 2 is probably the best way forward.

**Comment by JohnUrban** [comment]
Shucks! It was worth a try. Thanks for considering it @BenLangmead and @ch4rr0. It does sound like a pain to implement. You're probably right about the path forward. Unless of course it's easy to add a feature where the user adds adapters to the bowtie2 index as special sequences that allow for splitting the read and adding the 2 scores from the split alignments (adapter score + genome fragment score)?!?! Just kidding (maybe). There is some laziness deep in my soul that just wants to skip trimming. Oh well. :P 
I will close up. Thanks again.
