### ISSUE TITLE
Conda version does not work with most recent tbb version

### ISSUE THREAD

**Issue by bkille** [BenLangmead/bowtie2#336]
Not sure if this issue is better placed on the bioconda issue board, but the most recent version of TBB  (v2021.1.1) causes a runtime error with the `bowtie2-align-s` binary available on bioconda.

```
bowtie2 --version
/home/bkille/packages/miniconda3/bin/bowtie2-align-s: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory
(ERR): Description of arguments failed!
Exiting now ...
```

On another machine I obtained the error 
```
bowtie2 -h
/scratch1/bkille/software/miniconda3/bin/bowtie2-align-s: symbol lookup error: /scratch1/bkille/software/miniconda3/bin/bowtie2-align-s: undefined symbol: _ZN3tbb10interface78internal15task_arena_base19internal_initializeEv
```

The issue was fixed on both systems by reverting tbb to the previous version `tbb=2020.2`

**Comment by wzthhm** [comment]
I met the same problem and reverting to the previous version can fix. thanks

**Comment by joreynajr** [comment]
I actually tried to downgrade to tbb=2020.2 but this didn't solve my issue and I'm not sure where to go from here, any ideas?

**Comment by hickman-santini** [comment]
Can you specify what version (tbb-2020.2-xxxx)? I encountered the same problem, but I'm not finding a way to downgrade to 2020.2, only can downgrade as far as 2020.3-2...

**Comment by bkille** [comment]
`conda install tbb=2020.2` did the trick for me. What happens when you try that?

**Comment by sgraindorge** [comment]
Hi ! 
I had the same issue. 
`conda install tbb=2020.2` worked for me also !!! 
Thanks a lot for your help ;)

**Comment by hickman-santini** [comment]
> `conda install tbb=2020.2` did the trick for me. What happens when you try that?

Thank you @bkille I'm not sure what I was doing before; that worked for me! :)

**Comment by Kinggerm** [comment]
Why does it not fixed by https://github.com/bioconda/bioconda-recipes/pull/27174?

**Comment by bioinfo-guy** [comment]
Same here, downgrading TBB solve the problem.

**Comment by zyzyzyzyh** [comment]
conda install tbb=2020.2   worked for me. finally can run tophat now after having tophat error for a week

**Comment by jpeasari** [comment]
> 

Thank you. It worked for me.

**Comment by alexrootcode** [comment]
Thank you, it worked for me as well

**Comment by ch4rr0** [comment]
I will be closing this issue since it seems to have been resolved.
