### ISSUE TITLE
--local returns no alignments, but --end-to-end does

### ISSUE THREAD

**Issue by ryandikdan** [BenLangmead/bowtie2#343]
Hello,
    I'm using bowtie2 in order to test how likely certain short sequences of DNA are to bind to an index of target sequences. I am therefore interested in using the --local argument since it doesn't necessitate end to end binding (which may be the case in terms of target binding). I have a fasta of sequences which are 20 nucleotides long and when I align like normal it works fine, but if I set it to --local, nothing aligns. I was under the assumption that local would increase the number of alignments found. I also tried the other variations such as --very-sensitive-local and --very-fast-local, and got the same result. Could the short length (20nt) of the sequences have something to do with this? I would like to use --local since I believe it would provide more information about target binding. Am I missing something about how it works?

I'm using bowtie2  version 2.3.4.1 (I just tested version 2.4.4 which yielded the same result) with the following command
```
bowtie2 -f -a -x bt2_index -U ./temp/ENST00000367468.fa -S ./temp/ENST00000367468.sam -p 16 --local
```
which gives 0 alignments but when I change it to
```
bowtie2 -f -a -x bt2_index -U ./temp/ENST00000367468.fa -S ./temp/ENST00000367468.sam -p 16
```
It works well with 100% alignment and many multiple alignments, which I expect.
Below is an example of the input fasta file and and the index was built using the human transcriptome
```
>probe_0
AATTGTCATACGACTTGCAG
>probe_1
ATTGTCATACGACTTGCAGT
>probe_2
TTGTCATACGACTTGCAGTG
>probe_3
TGTCATACGACTTGCAGTGA
>probe_4
GTCATACGACTTGCAGTGAG
>probe_5
TCATACGACTTGCAGTGAGC
...
```

**Comment by ch4rr0** [comment]
Hello @ryandikdan,

You will need to tweak the minimum score, `--score-min`, in order for you to obtain an alignment. When running in `local` mode Bowtie2 uses the scoring function G,20,8 ≍ `20 + 8.0 * ln(L)`, where L is the read length. The reads in your sample input all have a length of 20 and would therefore require an alignment score of ~44 for a match to be reported.
Assuming a default match bonus (2), and ignoring qualities, a perfect alignment would obtain a score of 40 which is below the 44 minimum score threshold. Here is a sample command that would report alignments:

``` text
bowtie2 -f -a -x bt2_index -U ./temp/ENST00000367468.fa -S ./temp/ENST00000367468.sam -p 16 --local --score-min G,20,7
```

I hope this helps.

**Comment by ryandikdan** [comment]
I had a feeling it had to do with their length. Perfect, thanks so much!
