### ISSUE TITLE
Dovetailed reads present in BAM with --no-discordant option

### ISSUE THREAD

**Issue by ijhoskins** [BenLangmead/bowtie2#344]
I am experiencing unexpected behavior upon alignment of dovetailed reads. The reads are reported despite passing the --no-discordant option.

I have attached a reference and paired test reads.
[dovetail_testing.tar.gz](https://github.com/BenLangmead/bowtie2/files/6751400/dovetail_testing.tar.gz)

I experienced this behavior with both bowtie2 version 2.4.2 and version 2.3.5.1.

I wonder if I am just misunderstand the meaning of dovetailed. Are reads considered dovetailed if there is no overlap between the reads (despite 5' ends being "past" the 3' end of the mate)?

**Comment by ijhoskins** [comment]
I am calling bowtie2 as ```bowtie2 --maxins 1000 --no-discordant --no-dovetail --fr --rf --mp 4 --rdg 6,4 --rfg 6,4 -f -x ~/reference_files/CBS_pEZY3.fa -U test_dovetail.fa | samtools view -u - | samtools sort - > test_dovetail_notail.bam```

**Comment by BenLangmead** [comment]
Do you get the expected output when you use both `--no-mixed` and `--no-discordant`?

**Comment by ijhoskins** [comment]
@BenLangmead I get the same (unexpected) output with use of (--no-discordant), (--no-mixed --no-discordant), and (--no-mixed --no-discordant --no-dovetail). Perhaps this is related to use of --fr and --rf together?

**Comment by ijhoskins** [comment]
This was likely related to use of --rf in https://github.com/BenLangmead/bowtie2/issues/346.
