### ISSUE TITLE
bowtie2-build: Encountered empty reference sequence

### ISSUE THREAD

**Issue by DharitriSaikia** [BenLangmead/bowtie2#349]
hello all,
I am trying to create an index of a reference genome for an insect species with Bowtie 2. I downloaded two genomes from NCBI (assembly) in fasta format. When I ran the 'bowtie2-build' command I encountered the following warnings: 
"Encountered empty reference sequence"
"Encountered reference sequence with only gaps"

Are they because of the presence of hard and soft-masked regions in the genomes?

Kindly let me know how to troubleshoot it.

**Comment by ch4rr0** [comment]
Bowtie2 issues this warning if it encounters sequence that contains anything but A,C,G, and T. The warning can be safely ignored.

For example, running `bowtie2-build` with the following reference will issue a "Encountered reference sequence with only gaps" when sequence 'b' is read.

Please let us know if this answers your question.

``` text
>a
ACGTGCCCTATAAATATGGCCCCCATCTAAAA
>b
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
>c
ATGTTTCCATCCCTTTAAATTCGGGGGGTAAT
```
