### ISSUE TITLE
Can Bowtie2 be used with GATK?

### ISSUE THREAD

**Issue by AldhairMedico** [BenLangmead/bowtie2#350]
Dear Bowtie2 developers, 

I want to compare GATK/BWA-MEM + Variant Caller vs GATK/BOWTIE2 + Variant Caller results. 
For that purpose, can I use the GATK interleaved fastq file generated according to their Best Practices or it is necessary to put the original 1 2 paired fasta files?

This is confusing for me because in Bowtie2 manual there is the option --interleaved that accepts a single interleaved fastq as input but I'm not sure if this is the same file that generated by GATK or not. Using the former option I can achieve a more similar result but I'm afraid of using the wrong input.

Thanks for your time

**Comment by ch4rr0** [comment]
Yes, you can use a GATK-produced interleave `FASTA/Q` with `bowtie2`, `--interleaved` works with either format.

**Comment by AldhairMedico** [comment]
It definitely worked! Thank you!
