### ISSUE TITLE
bug: missing @SQ lines in the header

### ISSUE THREAD

**Issue by eboyden** [BenLangmead/bowtie2#365]
Hi,

Using Bowtie2 `2.4.4` or `bug-fixes` I found that certain output bams break certain downstream tools like fgbio `ClipBam` and Picard `ValidateSamFile`.  I traced the problem back to how Bowtie2 indexes the reference I was using, which is a masked version of GRCh38_noAlt+decoy that N's out certain incorrect duplications and exogenous in the genome, based on bed files produced by GRC and T2T:

https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna.gz
https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_GRC_exclusions.bed
https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/references/GRCh38/GCA_000001405.15_GRCh38_GRC_exclusions_T2Tv2.bed

The problem seems to be that a few of the contigs are N'd out entirely by the masking, and Bowtie2 apparently ignores these contigs when building the index (unlike BWA, which keeps them).

```
cat GCA_000001405.15_GRCh38_GRC_exclusions_all.bed
chr9	70701806	70719798
chr13	86252979	86269524
chr13	111753855 	111789114
chr16	34339329	34456556
chr21	5010000	5166246
chr21	5966593	6161371
chr21	6427258	6580181
chr21	6789085	6934219
chr21	7743700	7865746
chrX	37085011	37099262
chr11_KI270721v1_random	0	100316
chr22_KI270734v1_random	0	165050
chr10_KI270825v1_alt	0	188315
chrUn_KI270752v1	0	27745

# References in Bowtie2 header
samtools/samtools-1.14/samtools view -H bowtie2.bam | egrep -c "^@SQ"
2577

# References in BWA-MEM2 header
samtools/samtools-1.14/samtools view -H bwa-mem2.bam | egrep -c "^@SQ"
2580

diff bowtie2.header bwa-mem2.header
43a44
> @SQ	SN:chr11_KI270721v1_random	LN:100316
59a61
> @SQ	SN:chr22_KI270734v1_random	LN:165050
182a185
> @SQ	SN:chrUn_KI270752v1	LN:27745
```

(The alt contig isn't "missing" because I was using a no-alt reference.)

I'm not sure what the SAM spec says about this, but presumably all reference contigs should appear in the header even if they're entirely N'd out.  Ideally downstream tools like Picard and fgbio would handle this better by simply ignoring contigs in the reference that don't appear in the bam header, or at least by throwing a proper error instead of mangling a lot of MD and NM tags and then crashing.  I confirmed that adding these lines back to the bam header manually fixes the problem with the downstream tools, which behave properly and exit cleanly.

**Comment by eboyden** [comment]
BTW not sure if this also affects Bowtie 1 - might be worth looking into

**Comment by ch4rr0** [comment]
I pushed a potential fix for this issue to the bug_fixes branch. Here's how I tested the changes:

Sample reference:

``` text
>a
GGGCGGCGACCTCGCGGGTTTTCGCTATTTATGAAAATTTTCCGGTTTAAGGCGTTTCCGTTCTTCTTCG
>b
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
>c
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
AGAAACGAAGAAATGATGGGTGATGGTTTCCTTTGGTGCTACTGCTGCCGGTTTGTTTTGAACAGTAAAC
```
Old code:

``` text
./bowtie2-align-s -x /tmp/lv -c GCGGCGACCTCGCGGGTTTTCGCTATTTATGAAAATTTTCCGGTTTAAGGCGTTTCCGTTCTTCTTCG
1 reads; of these:
  1 (100.00%) were unpaired; of these:
    0 (0.00%) aligned 0 times
    1 (100.00%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
100.00% overall alignment rate
@HD	VN:1.0	SO:unsorted
@SQ	SN:a	LN:70
@SQ	SN:c	LN:140
@PG	ID:bowtie2	PN:bowtie2	VN:2.4.4	CL:"/bowtie2/bowtie2-align-s -x /tmp/lv -c GCGGCGACCTCGCGGGTTTTCGCTATTTATGAAAATTTTCCGGTTTAAGGCGTTTCCGTTCTTCTTCG"
0	0	a	3	42	68M	*	0	0	GCGGCGACCTCGCGGGTTTTCGCTATTTATGAAAATTTTCCGGTTTAAGGCGTTTCCGTTCTTCTTCG	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:68	YT:Z:UU
```

New code (sequence 'b' is now present in the header):

``` text
./bowtie2-align-s -x /tmp/lv -c GCGGCGACCTCGCGGGTTTTCGCTATTTATGAAAATTTTCCGGTTTAAGGCGTTTCCGTTCTTCTTCG
1 reads; of these:
  1 (100.00%) were unpaired; of these:
    0 (0.00%) aligned 0 times
    1 (100.00%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
100.00% overall alignment rate
@HD	VN:1.0	SO:unsorted
@SQ	SN:a	LN:70
@SQ	SN:b	LN:140
@SQ	SN:c	LN:140
@PG	ID:bowtie2	PN:bowtie2	VN:2.4.4	CL:"/bowtie2/bowtie2-align-s -x /tmp/lv -c GCGGCGACCTCGCGGGTTTTCGCTATTTATGAAAATTTTCCGGTTTAAGGCGTTTCCGTTCTTCTTCG"
0	0	a	3	42	68M	*	0	0	GCGGCGACCTCGCGGGTTTTCGCTATTTATGAAAATTTTCCGGTTTAAGGCGTTTCCGTTCTTCTTCG	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:68	YT:Z:UU
```

Let me know if these changes address the issue at hand.

**Comment by eboyden** [comment]
Hi @ch4rr0 - quick question, does the fix require remaking the index?  Or are old indexes fine and I just need to rerun alignment?

**Comment by eboyden** [comment]
BTW the `bowtie2-build` help message still says that Bowtie2 indexes don't work with Bowtie, which hasn't been true since Bowtie 1.2.3 :)

**Comment by ch4rr0** [comment]
I pushed a couple of changes that should take care of both issues. I am not sure why `python` complained about `deque` not support the `insert` method since it shows up when I ran `dir(deque)`.

**Comment by eboyden** [comment]
Thanks @ch4rr0, it looks like everything works now.  I really appreciate your responsiveness to reported issues, it's one of the reasons why I'm such a big Bowtie2 fan.
