### ISSUE TITLE
bowtie2-inspect not writing fasta?

### ISSUE THREAD

**Issue by cole-aifi** [BenLangmead/bowtie2#367]
Where does `bowtie2-inspect` write the FASTA? I have the GRCh38_noalt_as folder full of .bt2 files but I would like the FASTA from whence they came in order to use bedtools' `getfasta` with some ATAC data. If someone could point me where to find the reference FASTA that would help too. Since my BED files were made using this exact reference i'd like to stay consistent.

When I use `bowtie2-inspect` it just spews the FASTA sequences into the terminal and as far as I can see no FASTA ever comes of it.

**Comment by ch4rr0** [comment]
`bowtie2-inspect` prints to stdout but you can redirect the output to a file when using a *sh shell like so:

`./bowtie2-inspect ref_file > filename.fa`

**Comment by ch4rr0** [comment]
I have included a `-o/--output` flag to bowtie2-inspect that will give the user the option of saving output to a file. The change is currently available in the `bug_fixes` branch and will be rolled out as part of the next release.

**Comment by cole-aifi** [comment]
thank you! very helpful

**Comment by ch4rr0** [comment]
FYI -- this is already available in production.
