### ISSUE TITLE
Local alignment with bowtie2

### ISSUE THREAD

**Issue by Pooryamb** [BenLangmead/bowtie2#368]
Dear bowtie2 developer,

I just posted a question in Biostars. It seems like bowtie2 behaves weirdly if we specify high gap penalties. I would appreciate it if you could take a look at it:

Dear All,

I need to align many sequences against a single reference sequence locally. And I need the ungapped alignment. I ran the bowtie2 with the following options;

bowtie2 --local --rdg 1000,1000 --rfg 1000,1000 -x $myDatabase -f -U $FastaOfSequences -S $SamOutput

I have set gap opening and extension penalties to 1000 so that the alignments will not have any gap in between.

When I look at the sam output, I see some sequences that share a stretch of > 60 nt with the target sequence, but bowtie2 has not mapped them!

When I remove gap penalty options (--rdg 1000,1000 --rfg 1000,1000), the mentioned problem does not happen. However, some of the alignments have a gap in between. I am surprised that many of my sequences map with target when I use the default gap penalties but not with the increased gap penalties. In contrast, there is no gap in their alignment (with default parameters)! It is odd because I expected that increasing the gap penalty would get rid of alignments with gaps in between, but it also removes some ungapped alignments.

Later, I tried lowering gap penalties (--rdg 100,100 --rfg 100,100). It worked perfectly and output gapless alignments.

Yet, the question is why bowtie2 comes up with this problem when high gap penalties are used.

I would appreciate it if anyone could double-check this issue. I have copied one of the query sequences and my target sequence. This is my query:

TTATATTTTTTTTTGACAAGCCTTCCTATTATTCTTTTATATATAAATTGATAATAAC TGTGTTAAAAAAAAAATATATTAAATAAAATATAAAAATAATAAATAAATATAAATAA TATTAATAATATAAATTTAAATTATATAATTTAGAAATAGTTTTGTTTTTATTTTGGT TTTATAAAATGTTTTTTCTATGTCTTGTGTGCTTAAG

This is my target (that you need to index it before searching the query against it):

TTTTATATTTTTTTTTGACAAGCCTTCCTATTATTCTTTT ATATATAAATTGATAATAACTGTGTTAAACAAAACTGATT ATTTTGATAATAAAATATACTATATGATAATATATCGTAA TTATATAATGATCCGAATATATCAAAATATAATGATAAAA ATAAAAAATCTTTTAAAAAAAAACTAAAAAATGATATAAT AAATAA

Best wishes,

**Comment by ch4rr0** [comment]
This does not work for `--rdg 1000,1000` because the sum of the pair of numbers must not exceed 255. This is not documented anywhere, and would have only gotten caught if the `--debug` flag was specified. I will address this in time for the next release. I apologise of the inconvenience.

``` text
# rdg exceeds 255
/bowtie2 $ ./bowtie2-align-s-debug -x example/index/lambda_virus example/reads/longreads.fq --rdg 128,128 -u2
Warning: Running in debug mode.  Please use debug mode only for diagnosing errors, and not for typical use of Bowtie 2.
MAX_U8: 255
assert_leq: expected (256) <= (255)
aligner_swsse_ee_u8.cpp:859
assertion "0" failed: file "aligner_swsse_ee_u8.cpp", line 859, function "alignNucleotidesEnd2EndSseU8"
abort trap (core dumped)

# rdg less than 255
/bowtie2 $ ./bowtie2-align-s-debug -x example/index/lambda_virus example/reads/longreads.fq --rdg 128,127 -u2
Warning: Running in debug mode.  Please use debug mode only for diagnosing errors, and not for typical use of Bowtie 2.
MAX_U8: 255
2 reads; of these:
  2 (100.00%) were unpaired; of these:
    0 (0.00%) aligned 0 times
    2 (100.00%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
100.00% overall alignment rate
@HD	VN:1.5	SO:unsorted	GO:query
@SQ	SN:gi|9626243|ref|NC_001416.1|	LN:48502
@PG	ID:bowtie2	PN:bowtie2	VN:2.4.5	CL:"/bowtie2/bowtie2-align-s-debug -x example/index/lambda_virus example/reads/longreads.fq --rdg 128,127 -u2"
r1	16	gi|9626243|ref|NC_001416.1|	12259	42	194M	*	0	0	GGGCCGCCATTGATGCGAAAAGCCGGGGGCTGACTGACCGGCAGGCAGAACGGGAAGCCACGGAACAGCGCCTGAAGGAACAGTATGGCGATAATCCGCTGGCGCTGAATAACGTCGTGTCAGAGCAGAAAAAGACCTGGGCGGCTGAAGACCAGCTTCGCGGGAACTGGATGGCAGGCCTGAAGTCCGGCTGG	8+25;+39E.:<73=(@*.6AH0;>1%20$EH/-.4A<.1-F8:<:1>A029F3";&AE#**E6;H5@2)-+B.7,49AF#,,",B!959=-1.E-&0%(@=&AB19A03))@+6/44D&?")>!6B#2=C,612/7,=+8,A&14+$&,(B66*(BDH79$"27!3<H=A4/71)4:)0>4/*>-@3,E%&%7	AS:i:-3	XN:i:0	XM:i:1	XO:i:0	XG:i:0	NM:i:1	MD:Z:116A77	YT:Z:UU
r2	0	gi|9626243|ref|NC_001416.1|	15516	42	313M	*	0	0	AAGCAGTAAGGGGCATACCCCGCGCGAAGCGAAGGACAACCTGAAGTCCACGCAGTTGCTGAGTGTGATCGATGCCATCAGCGAAGGGCCGATTGAAGGTCCGGTGGATGGCTTAAAAAGCGTGCTGCTGAACAGTACGCCGGTGCTGGACANTGAGGGNAATACCAACATATCCGGTGTCACGGTGGTGTTCCGGGCTGGTGAGCAGGAGCAGACTCCGCCGGAGGGATTTGAATCCTCCGGCTCCGAGACGGTGCTGGGTACGGAAGTGAAATATGACACGCCGATCACCCGCACCATTACGTCTGCAAAC	60./".G76C,0220H8@4B)"+&F2,0>$+%%%.&@><*%.=!!%G&$GB"+!*G)5<!;&!C?<(:7<<2'5?,<(?0.3)<?5%B@+6>G.B&B4D0D>D93B?H9"47!G$G50)AF(/A:005$*@,3>0F0'!3H<<B'/1!;+*3?&D3H%--HG*7,+#CH;.6)F!$4$FH;,?H:/-86!+7>93E,C1@,/.)H+8@C*(7/:4)*E2823.+>&EE/#A2A:*3>7(52@#,9-=@$$4)H,/F"9$!$EG%=0.@B>1@H7*+;682>@$D@/@(*6F2;66#AFBE4-45E*04-6=75	AS:i:-2	XN:i:0	XM:i:2	XO:i:0	XG:i:0	NM:i:2	MD:Z:152C6G153	YT:Z:UU
```

**Comment by Pooryamb** [comment]
Thanks for your reply.
