### ISSUE TITLE
paired end mode:  is --un-conc reporting incompatible with -k mode?

### ISSUE THREAD

**Issue by BobMorrison** [BenLangmead/bowtie2#37]
I often use -k mode to find multiple valid alignments per read.  I also often use the --un-conc-gz reporting mode to capture non-concordantly aligned read pairs for subsequent analysis.   By design, the pair of non-aligned read files have identical numbers of reads in identical matching order, so they are still valid mate pair files.

But when I use -k with a value greater than one during a paired end alignment, the  --un-conc files end up with unequal numbers of reads.  Clearly some reads are only being written to one of the un-aligned files, breaking the rule for valid mate pair files.  In tests, the mate-2 file ends up with more reads, but neither file has the expected number of reads -- given the summary alignment count details reported by Bowtie2.

Are these two modes incompatible, or is finding secondary alignments somehow corrupting what gets reported as non-concordant read pairs?  Thanks!

**Comment by BobMorrison** [comment]
More info:  ran some tests on small datasets -- confirmed outcome and source of the problem:

1)  The main outcome problem is that the  --un-conc files are getting duplicate read entries written out (to just file 1 or file 2 but not both), so the files end up having unequal numbers of reads and the mates are no longer in perfect paired order.

2)  The cause is from secondary non-concordant alignments.  With K > 1, the alignment file gets a secondary alignment written (as it should), and that mate's  --un-conc file (#1 or #2) gets a second copy of the raw read written out (which should not happen).

Hope this helps!!

**Comment by BenLangmead** [comment]
We think we fixed this in the 2.3.1 release.  Can you retry with 2.3.1?

**Comment by BobMorrison** [comment]
OK, will give it a try.

BTW, thanks for the continual improvements to a great suite of software tools..!!
________________________________

**Comment by BenLangmead** [comment]
We haven't heard back, and so are closing this for now

**Comment by BobMorrison** [comment]
Hi Ben-   I’ve been so busy, haven’t had time to update to the newer version or test this bug fix.
Thanks again for all your efforts to improve this great software tool!!
