### ISSUE TITLE
clarification on -fr vs -f vs --fr flags

### ISSUE THREAD

**Issue by stephenfloor** [BenLangmead/bowtie2#374]
Hello, 

Thanks for writing great software and your work maintaining it. I ran into a vexing issue that would be easy to fix for people in the future. Somehow my command line ended up dropping a dash on the --fr flag, so I was running bowtie2 with the -fr flag. This was interpreted by bowtie2 as the -f flag, which led it to try to interpret the input as fasta instead of fastq. Would it be possible to throw an error with the parameter -fr instead of interpreting it as -f, since -fr is likely a typo for --fr? 

I realize this is kind of a minute issue, but also seems simple to fix and might lead to a more robust user experience!
Thanks,
Stephen

**Comment by ch4rr0** [comment]
Read formats should indeed be mutually exclusive options. I have pushed a change to the `bug_fixes` branch to address this.

**Comment by ch4rr0** [comment]
FYI -- this change is already available in production.
