### ISSUE TITLE
Database question

### ISSUE THREAD

**Issue by Jediworm** [BenLangmead/bowtie2#377]
Hello. 

I would like to ask a question about making a bowtie2 database. I am using the kneaddata human genome + human contaminants file to decontaminate my data, which uses bowtie2. However, I would also like to include a number of plant genomes in the bowtie2 database as well. The provided kneaddata human genome files are already in bt2 format (so, I assume they have already been used with bowtie2). The plant genomes are in fasta format. As a rough example, I am currently running "bowtie2-build Species1.fasta,Species2.fasta,Species3.fasta TreeGenome". When this command finishes running, can I just copy and paste the human genome bt2 files into the same output folder as the aforementioned command? Or, do I need to source the kneaddata human genome + human contaminants fasta file and additionally run bowtie2-build with that file and my plant genomes?

Thanks for your advice!

Regards,
William

**Comment by ch4rr0** [comment]
Hello,

If you're looking to combine Plant + kneaddata human genome + human contaminants, you will have to rebuild the index with all the necessary FASTAs. You can also opt for running two alignments, one against the kneaddata human genome + human contaminants index, then a second against the Plant index. I hope this helps.
