### ISSUE TITLE
plans for CHM13 v2.0 index file?

### ISSUE THREAD

**Issue by hmraimeryoung-95** [BenLangmead/bowtie2#378]
My lab/PI is very interested in starting to use the new CHM13 genome from the T2T consortium. We already started to test our data with the H. sapiens CHM13plusY index available on the site. Once downloaded we saw that the file indicates it is the draftv1.0_PlusY build of CHM13. We are particularly interested in rDNA regions which were known gaps in v1.0 and were filled with v1.1 and now CHM13 is up to v2.0 which is noted to be v1.1 plus the Y chromosome.

**Comment by BenLangmead** [comment]
A Bowtie 2 index for CHM13 v2.0 is now available from https://genome-idx.s3.amazonaws.com/bt/chm13v2.0.zip.  We will update the sidebar on the Bowtie 2 website soon.
