### ISSUE TITLE
dyld error

### ISSUE THREAD

**Issue by korjent** [BenLangmead/bowtie2#379]
First I am not a very experienced user.
But I installed GetOrganelle and it crashes on bowtie2.
I tried installing on 2 different macs, but no luck.
Any help appreciated. 

dyld: Symbol not found: __ZNSt12length_errorD1Ev
  Referenced from: /Users/a1638383/opt/anaconda3/bin/bowtie2-align-s
  Expected in: /usr/local/lib/libtbb.dylib
 in /Users/a1638383/opt/anaconda3/bin/bowtie2-align-s
(ERR): Description of arguments failed!
Exiting now ...

**Comment by ch4rr0** [comment]
Hello,

Bioconda still has TBB as a dependency for bowtie2 even though we no longer have TBB as a dependency. In any event you can use `conda install tbb=2020.2` (from issue #336) to install the "missing" library. I hope this helps.
