### ISSUE TITLE
The optimized read length for bowtie2 to handle

### ISSUE THREAD

**Issue by Duannai** [BenLangmead/bowtie2#383]
Hello, just an easy question.

What is the optimized read length for bowtie2 to handle? Can bowtie2 handle the reads shorter than 50 bp? For instance, the reads with 30 bp.

Thanks in advance!

Mort

**Comment by ch4rr0** [comment]
Hello,

Bowtie is best suited for aligning short reads. Bowtie 2 can handle short reads, but you may need to tweak a few parameters, such as seed length (-L), if the desired alignments are not reported. I hope this helps.
