### ISSUE TITLE
A question about -X

### ISSUE THREAD

**Issue by NJU-Bio-Info** [BenLangmead/bowtie2#389]
Hi, when I use bowtie2 to perform CUT&Tag alignment. I set -X 700 and filter the reads whose mapq<20 but I can still observe fragment size >700 in bam file. I wonder why I get this result?

**Comment by ch4rr0** [comment]
I was able to reproduce this issue. I will update this thread as soon as I have a proper fix.

**Comment by ch4rr0** [comment]
Taking a second look at the issue it appears that some of your reads are longer than the 700 nucleotides you specified for `maxIns`. `bowtie2` then adjusts the value of `maxIns` by setting it to the length of the longer fragment that makes up the pair. So I ask, what is your scenario and what behavior were you looking for?

**Comment by BenLangmead** [comment]
(Just following on @ch4rr0's comment, since he and I discussed this earlier.)  We're curious: Does it make sense to you that some of the reads produced by the CUT&Tag assay would be quite long, longer even than what you specified for the `-X` parameter?
