### ISSUE TITLE
FASTA parser

### ISSUE THREAD

**Issue by har-wradim** [BenLangmead/bowtie2#39]
Bowtie2 seems to incorrectly parse FASTA record definitions with extra greater-than character(s) appearing in them. According to the [accepted consensus](http://www.ncbi.nlm.nih.gov/BLAST/blastcgihelp.shtml), FASTA definitions occupy whole lines and only the first '>' symbol on a line serves as the definition line indicator.

E.g.:

	$ cat myreads.fa
	>A <B> <C>
	NNNNNNNNNN
	$ bowtie2 -x myref --no-hd -fU myreads.fa
	Warning: skipping read 'A <B' because length (1) <= # seed mismatches (0)
	Warning: skipping read 'A <B' because it was < 2 characters long
	Warning: skipping read ' <C' because length (1) <= # seed mismatches (0)
	Warning: skipping read ' <C' because it was < 2 characters long
	3 reads; of these:
	  3 (100.00%) were unpaired; of these:
		3 (100.00%) aligned 0 times
		0 (0.00%) aligned exactly 1 time
		0 (0.00%) aligned >1 times
	0.00% overall alignment rate
	A	4	*	0	0	*	*	0	0	N	I	YT:Z:UU	YF:Z:LN
		4	*	0	0	*	*	0	0	C	I	YT:Z:UU	YF:Z:LN
	2	4	*	0	0	*	*	0	0	NNNNNNNNNN	IIIIIIIIII	YT:Z:UU	YF:Z:NS

**Comment by BenLangmead** [comment]
Yes, I see this issue.  Fixed in the master branch now and fix will be present in next release.  Please re-open if you find issue persists in next release.

Best,
Ben
