### ISSUE TITLE
Truncated fastq output with --un

### ISSUE THREAD

**Issue by ondovb** [BenLangmead/bowtie2#41]
When using `--un` with fastq input, some records are truncated in the unaligned output, with the following record starting without a newline. The total characters in the truncated records always seems to be 8192, suggesting a buffer size limit issue.

**Comment by tauanajc** [comment]
I found the same issue with input fasta files. I am running bowtie on the output of Trinity (newest version 2.2.0) and some records in the output of bowtie have the next header concatenated with the sequence. Any solution to that yet?

**Comment by BenLangmead** [comment]
Could you try with the latest version (v2.3.2) and let us know whether this is still an issue?

**Comment by ch4rr0** [comment]
I am closing this issue for now. Please feel free to reopen if you continue to experience the same behavior in v2.3.2 and above.
