### ISSUE TITLE
Keep /1 and /2 at end of reads

### ISSUE THREAD

**Issue by mocat2** [BenLangmead/bowtie2#42]
Hi,

I know it's possible to figure out the reads with the flag, but I'm wondering if you might be able to point where in the source code the read names are printed, so that I could modify it to keep the /1 and /2, rather than removing these from the names?

Thanks in advance!

**Comment by BenLangmead** [comment]
This is a good place to look:
https://github.com/BenLangmead/bowtie2/blob/eda270a560adb01e356fe505b01ee82fb0cb6bcf/sam.h#L221
