### ISSUE TITLE
Bowtie 2.5.1 - living in the future

### ISSUE THREAD

**Issue by HenrikBengtsson** [BenLangmead/bowtie2#421]
<https://bowtie-bio.sourceforge.net/bowtie2/index.shtml> says:

"Version 2.5.1 - Feb 17, 2023"

and

"Bowtie2 v2.5.1 | 02/17/23"

I'm really into the future myself, but this is something else :p

**Comment by ch4rr0** [comment]
Whoops! Should be fixed now.
