### ISSUE TITLE
many tests fail with 2.5.1

### ISSUE THREAD

**Issue by nieder** [BenLangmead/bowtie2#424]
Running `make test` on 2.5.1 fails many tests. It's hard to know where an individual test starts, but the test output is full of errors about the number of mate files/sequences:
```
./bowtie2-build  --quiet --sanity  .simple_tests.pl.fa .simple_tests.tmp
./bowtie2     --ff --quiet -M 1 --reads-per-batch 7 -x .simple_tests.tmp -q -1 .simple_tests.1a.fq.gz -2 .simple_tests.2a.fq.gz
Warning: -M is deprecated.  Use -D and -R to adjust effort instead.
@HD	VN:1.5	SO:unsorted	GO:query
@SQ	SN:0	LN:47
@PG	ID:bowtie2	PN:bowtie2	VN:2.5.1	CL:"/sw/build.build/bowtie2-2.5.1-1/bowtie2-2.5.1/bowtie2-align-s --wrapper basic-0 --ff --quiet -M 1 --reads-per-batch 7 -x .simple_tests.tmp -q -1 .simple_tests.1a.fq.gz -2 .simple_tests.2a.fq.gz"
r0	67	0	2	42	18M	=	24	41	GCTATCATCACGCGGATA	IIIIIIIIIIIIIIIIII	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:18	YS:i:0	YT:Z:CP
r0	131	0	24	42	19M	=	2	-41	CGCATCGACATTAATATCC	IIIIIIIIIIIIIIIIIII	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:19	YS:i:0	YT:Z:CP
References:
>0
AGCTATCATCACGCGGATATTAGCGCATCGACATTAATATCCCCAAA
./bowtie2 -x .dummy_index -1.simple_tests.1a.fq.gz -2 .simple_tests.2a.fq.gz| samtools view -b -o .test.bam
Error: 2 mate files/sequences were specified with -1, but 1
mate files/sequences were specified with -2.  The same number of mate files/
sequences must be specified with -1 and -2.
Error: Encountered internal Bowtie 2 exception (#1)
Command: /sw/build.build/bowtie2-2.5.1-1/bowtie2-2.5.1/bowtie2-align-s --wrapper basic-0 -x .dummy_index -1.simple_tests.1a.fq.gz -1  -2  
(ERR): bowtie2-align exited with value 1
[main_samview] fail to read the header from "-".
```

**Comment by ch4rr0** [comment]
Hello,

I am assuming that you are referring to the simple tests. The errors that I get during my run today were exactly the ones that we expect to fail. Any additional errors would immediately cause the test suite to abort.

``` text
Error: Read 0 has more read characters than quality values.
Error: Read 0 has more quality values than read characters.
Error: Encountered internal Bowtie 2 exception (#1)
Error: Encountered internal Bowtie 2 exception (#1)
Error: Read r0 has more read characters than quality values.
Error: Read r0 has more read characters than quality values.
Error: reads file does not look like a FASTQ file
Error: reads file does not look like a FASTA file
Error: reads file does not look like a FASTA file
Error: Read r0 has more read characters than quality values.
Error: Read r0 has more quality values than read characters.
Error: Read MachName_RunNum_Lane_Tile_X_Y_Index/0 has more read characters than quality values.
```

The two "Encountered internal Bowtie 2 exception" errors are the result of incorrect parameters passed to the `--trim-to` option, which again expect.

Can you provide some more information on what system you're running on such as operating system, processor architecture?

**Comment by nieder** [comment]
I'm on macOS 10.14.6 (x86_64). I'm attaching a build log of the entire `make test` output. I the above errors, but many others, and the test suite terminates with an error code.

[bowtie2_2.5.1_test_log.txt](https://github.com/BenLangmead/bowtie2/files/10731860/bowtie2_2.5.1_test_log.txt)

**Comment by nieder** [comment]
It seems to be an issue with the /usr/bin/perl (v5.18.4) that comes with the system. When I install perl5.28.2 (which also installs an unversioned 'perl'), then the tests pass.

**Comment by nieder** [comment]
This can probably be closed unless bowtie2 is expected to pass with perl5.18

**Comment by ch4rr0** [comment]
Hello,

We do not have any plans on supporting older versions of Perl, so I will go ahead and close this issue.
