### ISSUE TITLE
2.5.1 mingw binary release do not contain *.exe files.

### ISSUE THREAD

**Issue by sis6789** [BenLangmead/bowtie2#429]
2.5.1 mingw binary release do not contain *.exe files.

**Comment by sis6789** [comment]
D:\Downloads\bowtie2-2.5.1-mingw-x86_64 디렉터리

23-01-18  12:04    <DIR>          .
23-03-28  10:59    <DIR>          ..
23-01-18  11:26             1,307 AUTHORS
23-01-18  11:29            26,907 bowtie2
23-01-18  11:46        22,135,684 bowtie2-align-l
23-01-18  12:01        19,081,019 bowtie2-align-l-debug
23-01-18  11:39        22,175,673 bowtie2-align-s
23-01-18  11:57        19,074,355 bowtie2-align-s-debug
23-01-16  07:57             3,602 bowtie2-build
23-01-18  11:33         9,601,803 bowtie2-build-l
23-01-18  11:52         9,583,233 bowtie2-build-l-debug
23-01-18  11:31         9,608,107 bowtie2-build-s
23-01-18  11:51         9,577,475 bowtie2-build-s-debug
23-01-18  11:29                41 bowtie2-build.bat
23-01-16  07:57             2,762 bowtie2-inspect
23-01-18  11:49         8,344,907 bowtie2-inspect-l
23-01-18  12:03         6,071,189 bowtie2-inspect-l-debug
23-01-18  11:48         8,360,822 bowtie2-inspect-s
23-01-18  12:02         6,076,868 bowtie2-inspect-s-debug
23-01-18  11:29                43 bowtie2-inspect.bat
23-01-18  11:29                32 bowtie2.bat
23-01-18  11:29                 5 BOWTIE2_VERSION
23-01-18  12:03    <DIR>          doc
23-01-18  12:03    <DIR>          example
23-01-16  07:57            35,147 LICENSE
23-01-18  11:29            87,462 MANUAL
23-01-16  07:57           116,698 MANUAL.markdown
23-01-18  11:29            32,850 NEWS
23-01-18  11:29             6,285 README.md
23-01-18  12:03    <DIR>          scripts
23-01-16  07:57               248 TUTORIAL
              26개 파일         150,004,524 바이트
               5개 디렉터리  1,759,212,859,392 바이트 남음

**Comment by ch4rr0** [comment]
Hello, my apologies for this mistake. I will re-upload the Windows package later. In the meantime you can manually add the .exe extension to the binaries and that should work.

**Comment by sis6789** [comment]
Thank you for your effort.나의 iPhone에서 보냄2023. 4. 4. 02:26, ch4rr0 ***@***.***> 작성:﻿
Hello, my apologies for this mistake. I will re-upload the Windows package later. In the meantime you can manually add the .exe extension to the binaries and that should work.

**Comment by sis6789** [comment]
Would you check my problem?
I have mailed this to ***@***.***

My problem is as follow:

In blastn subject query, two 15bp long fasta file can used for subject
query as follow command:
blastn -subject short.fasta -query query.fasta -task blastn -perc_identity
95 -outfmt "10 qseqid ..."

I have tried following steps to use bowtie2 with same data.
bowtie2-build-s -f short.fasta read12
bowtie2 -x read12  --local  --no-hd  --no-sq  --no-unal  --no-discordant
-p 2  -k 1  -U query.fastq  -S out.sam

The result is 100% un-aligned!

In another case with 110bp fasta, bowtie2 have done well.

Would you advise me, what is the preoblem?
Does minimum length exist for index fasta?

If possible, I want to know the problem and solutions.

I can not find web pages abount minimum length of index fasta.
And there is no length description in bowtie2 manual.

2023년 4월 4일 (화) 오전 2:26, ch4rr0 ***@***.***>님이 작성:

**Comment by ch4rr0** [comment]
Bowtie may be the answer, but we don't have any windows binaries currently available. I'll try to put one together sometime today if you're willing to wait.

**Comment by ch4rr0** [comment]
Hello,

Bowtie works better for short reads. You can find a `bowtie` package for Windows here: http://0x0.st/HXHr.zip

The link is only valid for 24 hours, below is the file hash.

c8cbd8ab407e1cab954cac769f133fbd  bowtie-1.3.1-mingw-aarch64.zip

Let me know if you have any questions.

**Comment by sis6789** [comment]
Thanks, I'll check it out.

2023년 4월 6일 (목) 오전 12:51, ch4rr0 ***@***.***>님이 작성:
