### ISSUE TITLE
bowtie2-2.5.1-mingw-x86_64 does not support for compressed fastq files

### ISSUE THREAD

**Issue by junjunlab** [BenLangmead/bowtie2#435]
Hi, I downloaded bowtie2-2.5.1-mingw-x86_64 and I found this version can only support with un-compressed fastq files but not compressed fastq. Here is the error:

![1683517886946](https://user-images.githubusercontent.com/64965509/236729963-c5374a13-fda0-43ef-8a0f-92e5a7a46be9.png)

Thanks!

**Comment by ch4rr0** [comment]
Hello,

This has been fixed in the latest commits to `bug_fixes`. Our upcoming release will include these changes. I have tested the changes the changes to make sure that they work as expected.

**Comment by ch4rr0** [comment]
This is has been fixed in v2.5.2.
