### ISSUE TITLE
MQ scores are really low after using Bowtie2 with GATK

### ISSUE THREAD

**Issue by hkarakurt8742** [BenLangmead/bowtie2#445]
Dear developer of Bowtie2,
I have a genomic data (from GIAB, HG005, SRR2962693) and I used both BWA and Bowtie2 for alignment and used the same GATK pipeline for variant calling. The problem is, the MQ scores are maximum 42 while when I use Bowtie2 while BWA-MEM scores are really high in average. What might be the problem? I also used Hisat2 and the MQ scores are also looking similar to BWA while Bowtie2 generated MQ scores are really low. I created Bowtie2 index and used this code for alignment:

`
bowtie2 -p 12 -x bowtie_idx/hg19_bwt -1 SRR2962693_1.fastq.gz -2 SRR2962693_2.fastq.gz -S SRR2962693.sam
`

Is there any specific parameter for this job or increasing sensitivity or changing alignment to local may help?

Thank you in advance

**Comment by ch4rr0** [comment]
Hello,

BWA MEM uses local mode by default. Adding `--local` to your `bowtie2` command line should bring the MAPQ closer to BWA's. I hope this helps.
