### ISSUE TITLE
Make Bowtie2 architecture independent

### ISSUE THREAD

**Issue by wilwan01** [BenLangmead/bowtie2#46]
Hi @BenLangmead, any plan to make Bowtie2 architecture independent? Bowtie2 won't even compile for other architectures, due to hard-coded x86 SSE optimizations. It would be useful to have an option to turn this off if running this on non-x86 hardware platforms, or add in optimisations for other architectures, i.e., ARM.

**Comment by xnox** [comment]
bowtie1 is successfully compiled for amd64, ppc64le, s390x, arm64.  Indeed turning off SSE would be a good start, is there at all a non-SSE code-path in bowtie2?

**Comment by IvantheDugtrio** [comment]
Hi @wilwan01, I've gone through bowtie2's source code and all of the vectorized code is located in the aligner_swsse* files. You cannot simply turn off SSE as the source code calls these functions. The best option for now would be to use macros and run the Aarch64 or PPC64 equilvalent vector functions in place of the Intel functions. For ARM I suggest looking at the NEON SIMD library. Also beware that you probably need a 64-bit platform to compile or run this.

**Comment by wilwan01** [comment]
Hi @IvantheDugtrio, agree that "you cannot simply turn off SSE as the source code calls these functions.", perhaps it could be a feature for Bowtie3, like what Isaac3 did.

**Comment by BenLangmead** [comment]
This is correct -- there is no non-SSE path through Bowtie 2.  We are not planning on creating such a path since dynamic programming performance depends quite crucially on SSE-style vectorization.

**Comment by xnox** [comment]
but all of ppc64le, s390x and arm64 have SSE-style vectorization and e.g. both gcc & clang can vectorize the code for you on all of those architectures as far as I understand.

**Comment by BenLangmead** [comment]
We'd be open to accepting a contribution for one or more of those other architectures if it could be done in a way that doesn't over-complicate the code and doesn't sacrifice performance on Intel/SSE.  We're not adding it to our own TODO list, though, since the vast majority of our users are Intel/SSE.

In our experience (on Intel architectures), gcc and icc auto-vectorizers produce code that's appreciably slower than our hand-coded loops.  We're happy to be proven wrong for other architectures.

**Comment by ch4rr0** [comment]
The [simde project](https://github.com/simd-everywhere/simde) has made this a possibility.
We are now able to compile and run Bowtie2 on ARM, IBM-Z, S390x when using this project. You may
need to disable the `popcnt` instruction when compiling on some of these architectures e.g. on
ARM `bowtie2` can be compiled using `make bowtie2-align-s POPCNT_CAPABILITY=0`.
