### ISSUE TITLE
option --dovetail or --no-dovetail

### ISSUE THREAD

**Issue by carl-** [BenLangmead/bowtie2#47]
I found that in the online manual for bowite 2.2.9, there is an option --dovetail but in the help message of bowtie2 program, there is no --dovetail but a --no-dovetail option.
I also found that the 'gDovetailMatesOK' is false by default in file  bt2_search.cpp#L10.

may I set 'gDovetailMatesOK' to true by enable --dovetail ?

and perhaps the online manual or the program help message should be updated .

**Comment by BenLangmead** [comment]
At some point in the past, we got mixed up about this.  Bowtie 2 actually has both `--dovetail` and `--no-dovetail` arguments but, as you point out, dovetailing is disabled by default.  So specifying `--no-dovetail` does nothing to change the default.  Specifying `--dovetail` turns it on, so this should be the option documented in the usage message.  We are working to fix this.  But in the meantime, you ought to be able to use `--dovetail`

**Comment by BenLangmead** [comment]
This is fixed in 2.3.1.
