### ISSUE TITLE
Multithreading issue, unpaired mode

### ISSUE THREAD

**Issue by pzalkind** [BenLangmead/bowtie2#48]
I'm currently trying to use bowtie2 to align paired reads merged in a single file, and to gain some time I'm trying to use the multithreading option of bowtie2 (-p/--threads option). Yet, so far either on my personal machine or on the cloud solution we're using, bowtie2-align-l (called by bowtie2) runs on a single core, for hours and hours then (merged reads file >= 10GB).

Edit : Ok, I think it's my bad, I've tried with small files and it works nicely, we're just using too big reads files. You can close the issue.

**Comment by BenLangmead** [comment]
Will do

**Comment by ksiklenka** [comment]
i'm having a similar issue with bowtie2 in paired end mode.  Bowtie2 v2.3.2 calls bowtie2-align-s and caps out at 1 thread. My fastq files are 10 gb each. I've ever had a problem before

actual command used:
`bowtie2 -p 12 -t -q -N 1 -L 25 -X 2000 --no-mixed --no-discordant -x ./DBA_2J_N -1 $r1 -2 $r2 -S $out.sam `
