### ISSUE TITLE
Segmentation fault (core dumped) (ERR): bowtie2-align exited with value 139

### ISSUE THREAD

**Issue by pageale** [BenLangmead/bowtie2#481]
Version: version 2.4.1
64-bit
Built on 
Fri Feb 28 17:23:43 UTC 2020
Compiler: gcc version 7.3.0 (crosstool-NG 1.23.0.450-d54ae)

I tried this command and it gives "Segmentation fault (core dumped)
(ERR): bowtie2-align exited with value 139"

`bowtie2 -x ~/Projects/ichor/rawdata/index_ref/ref -1 small_R1.fastq -2 small_R2.fastq --verbose -S out`

Things I tried already:
* -p 1 
* diving the fastq into small files (1000)
* re-doing the index reference file

 

total       used       free  compartido búfer/caché  available
Memory:          15           3           9           0           2          11
Swap:             1           1           0

Finally, i attach the output from verbose

`Headers:
    len: 2945849067
    bwtLen: 2945849068
    sz: 736462267
    bwtSz: 736462267
    lineRate: 7
    offRate: 4
    offMask: 0xfffffffffffffff0
    ftabChars: 10
    eftabLen: 20
    eftabSz: 160
    ftabLen: 1048577
    ftabSz: 8388616
    offsLen: 184115567
    offsSz: 1472924536
    lineSz: 128
    sideSz: 128
    sideBwtSz: 96
    sideBwtLen: 384
    numSides: 7671482
    numLines: 7671482
    ebwtTotLen: 981949696
    ebwtTotSz: 981949696
    color: 0
    reverse: 0
`

**Comment by ch4rr0** [comment]
Hello,

It is possible that the index in question is larger than the amount of available memory on your system? Can you confirm this?

**Comment by pageale** [comment]
Hello !
At the end, I was able to run it, probably as you mention it was due to memory because it executes normally after I finished other jobs in the computer. 

5,3G	index_ref/

Anyways, thank you so much for replying !!
