### ISSUE TITLE
Match Bonus causes segfault in local mode

### ISSUE THREAD

**Issue by mykmaley** [BenLangmead/bowtie2#54]
Below is a scenario that triggers a segfault when processing reads that appear to trigger the match bonus algorithm on certain reads and causes bowtie2 to segfault.  If I run the code in debug mode, I get an assertion, apparently related to the match bonus (-ma) being non-zero.  If I set -ma to zero (0), the alignment runs, but obviously the alignments are suspect since we're triggering code that is documented as:

_"The best possible score in local mode equals the **match bonus times the length of the read**. This happens when there are no differences between the read and the reference."_

Which would result in a score of zero.

The two read files (renamed to .txt for upload) are the smallest set of paired reads that I could get to recreate the issue.

Here's my attempt at isolating the issue:

## Version
```
[root@cmp001 bowtie2-2.2.9]# ./bowtie2 --version
/root/bowtie2-2.2.9/bowtie2-align-s version 2.2.9
64-bit
Built on localhost.localdomain
Thu Apr 21 18:36:37 EDT 2016
Compiler: gcc version 4.1.2 20080704 (Red Hat 4.1.2-54)
Options: -O3 -m64 -msse2  -funroll-loops -g3 -DPOPCNT_CAPABILITY
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
```
## Setting environment
```
[root@cmp001 bowtie2-2.2.9]# BOWTIE2_INDEXES=/data/aligner/bowtie2/indexes/HOMO_SAPIEN/hg19
[root@cmp001 bowtie2-2.2.9]# export BOWTIE2_INDEXES
```
## Attempted Alignment
```
[root@cmp001 bowtie2-2.2.9]# ./bowtie2 --local --very-fast --ma 2 --mp 6 --np 1 --rdg 5,3 --rfg 5,3 --score-min C,-0.6,-0.6 --skip 0 --trim5 0 --trim3 0 --phred33 --mm -x hg19 -1 ~/segfault-reads-1 -2 ~/segfault-reads-2 -S /tmp/out.sam
(ERR): bowtie2-align died with signal 11 (SEGV)
```

## Debugging Attempted Alignment
```
[root@cmp001 bowtie2-2.2.9]# ./bowtie2 --debug --local --very-fast --ma 2 --mp 6 --np 1 --rdg 5,3 --rfg 5,3 --score-min C,-0.6,-0.6 --skip 0 --trim5 0 --trim3 0 --phred33 --mm -x hg19 -1 ~/segfault-reads-1 -2 ~/segfault-reads-2 -S /tmp/out.sam
Warning: Running in debug mode.  Please use debug mode only for diagnosing errors, and not for typical use of Bowtie 2.
assert_gt: expected (0) > (0)
aligner_swsse_loc_u8.cpp:314
bowtie2-align-s-debug: aligner_swsse_loc_u8.cpp:314: TAlScore SwAligner::alignGatherLoc8(int&, bool): Assertion `0' failed.
(ERR): bowtie2-align died with signal 6 (ABRT)
```
## Setting -ma to zero  
```
[root@cmp001 bowtie2-2.2.9]# ./bowtie2 --debug --local --very-fast --ma 0 --mp 6 --np 1 --rdg 5,3 --rfg 5,3 --score-min C,-0.6,-0.6 --skip 0 --trim5 0 --trim3 0 --phred33 --mm -x hg19 -1 ~/segfault-reads-1 -2 ~/segfault-reads-2 -S /tmp/out.sam
Warning: Running in debug mode.  Please use debug mode only for diagnosing errors, and not for typical use of Bowtie 2.
256 reads; of these:
  256 (100.00%) were paired; of these:
    85 (33.20%) aligned concordantly 0 times
    171 (66.80%) aligned concordantly exactly 1 time
    0 (0.00%) aligned concordantly >1 times
    ----
    85 pairs aligned concordantly 0 times; of these:
      6 (7.06%) aligned discordantly 1 time
    ----
    79 pairs aligned 0 times concordantly or discordantly; of these:
      158 mates make up the pairs; of these:
        89 (56.33%) aligned 0 times
        62 (39.24%) aligned exactly 1 time
        7 (4.43%) aligned >1 times
82.62% overall alignment rate
```

## Running with -ma disabled without debugging. Yields poor alignment
```
[root@cmp001 bowtie2-2.2.9]# ./bowtie2 --local --very-fast --ma 0 --mp 6 --np 1 --rdg 5,3 --rfg 5,3 --score-min C,-0.6,-0.6 --skip 0 --trim5 0 --trim3 0 --phred33 --mm -x hg19 -1 ~/segfault-reads-1 -2 ~/segfault-reads-2 -S /tmp/out.sam
256 reads; of these:
  256 (100.00%) were paired; of these:
    85 (33.20%) aligned concordantly 0 times
    171 (66.80%) aligned concordantly exactly 1 time
    0 (0.00%) aligned concordantly >1 times
    ----
    85 pairs aligned concordantly 0 times; of these:
      6 (7.06%) aligned discordantly 1 time
    ----
    79 pairs aligned 0 times concordantly or discordantly; of these:
      158 mates make up the pairs; of these:
        89 (56.33%) aligned 0 times
        62 (39.24%) aligned exactly 1 time
        7 (4.43%) aligned >1 times
82.62% overall alignment rate
```
[segfault-reads-1.txt](https://github.com/BenLangmead/bowtie2/files/485283/segfault-reads-1.txt)
[segfault-reads-2.txt](https://github.com/BenLangmead/bowtie2/files/485282/segfault-reads-2.txt)

**Comment by BenLangmead** [comment]
I am curious why you are combining `--ma 2` and `--score-min C,-0.6,-0.6`.  It doesn't make much sense to have a non-zero match bonus and then a minimum overall score that is negative.  Giving `--score-min` non-negative coefficients should fix it.  In the meantime, I'll add a friendly error message to take the place of this crash.  Thanks for the report.

**Comment by mykmaley** [comment]
A fix is appreciated.

Regarding your question, I'm not specifically executing that command line. It was submitted to me as a failure mode for a use case and I'm merely trying to keep software from exploding under 'normal' use cases.

I appreciate the additional insight into the cause of the segfault. That information should help me prevent the scenario that causes the issue.

**Comment by BenLangmead** [comment]
Fix is now in the master branch.  The next release will include the fix.  Please re-open if next release doesn't fix this for you.  Thanks again for the report.
