### ISSUE TITLE
Bowtie2-build fails if any all N sequences are present

### ISSUE THREAD

**Issue by RSherman15** [BenLangmead/bowtie2#55]
When bowtie2-build encounters a sequence of all Ns (which may occur when processing repeat-masked contigs), it fails with the following error:
**\* glibc detected **\* bowtie2-build: double free or corruption (out): 0x00000000046805c0 ***

It appears this issue has been documented by others as well - a google search of the error yielded this result: https://github.com/ibest/ARC/issues/33

**Comment by atulkakrana** [comment]
I have encountered the same issue. When can we expect a fix?

**Comment by BenLangmead** [comment]
Could you please post an example FASTA for for which this happens, preferable a very small one?  I cannot reproduce on any small examples I've tried.

**Comment by RSherman15** [comment]
Sure. Here's a fasta where I get this error with bowtie2-build. Just checked and I'm running Bowtie 2 version 2.2.5, so maybe this has been fixed since then; I can give upgrading a try.

[bowtieBuildFailureExample.fa.zip](https://github.com/BenLangmead/bowtie2/files/508940/bowtieBuildFailureExample.fa.zip)

**Comment by BenLangmead** [comment]
We think we fixed this in yesterday's 2.3.1 release.  Can you try again with that version?

**Comment by RSherman15** [comment]
It works (at least on my example that was failing previously). Thanks!
