### ISSUE TITLE
Bowtie 2 manual claims --score-min default in --local mode is G,20,8, but is actually G,0,10

### ISSUE THREAD

**Issue by atsteffen** [BenLangmead/bowtie2#56]
The bowtie 2 manual entry for --score-min claims:
"... The default in --end-to-end mode is L,-0.6,-0.6 and the default in --local mode is G,20,8"

However, when --local (or one of the *-local presets) is specified and --score-min G,20,8 is provided the results are different then when leaving --score-min off the command line.

Upon inspection of the source code, I found within scoring.h:
# define DEFAULT_MIN_CONST_LOCAL (0.0f)
# define DEFAULT_MIN_LINEAR_LOCAL (10.0f)

These constants are used to initialize the costMin variable in aligner_seed_policy.cpp. 

providing --score-min G,0,10 in local mode and the results become consistent

**Comment by BenLangmead** [comment]
You're right!  We're working on the best way to fix this.

Best,
Ben

**Comment by BenLangmead** [comment]
Fix is now in branch [issue56](https://github.com/BenLangmead/bowtie2/tree/issue56).  We'll be testing this a bit.

**Comment by BenLangmead** [comment]
Fix present in release 2.3.1
