### ISSUE TITLE
Installation of bowtie2 on MacOS using terminal

### ISSUE THREAD

**Issue by aliexclusive** [BenLangmead/bowtie2#59]
I'm trying to install bowtie2 (latest version) on MacOS using terminal. It's not working. Giving following error.
-bash: bowtie2: command not found
-bash: bowtie2-build: command not found
etc...
I'm using following platform.
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16).
Can anyone guide me to install bowtie2 on MacOS

**Comment by ch4rr0** [comment]
Are you installing from source or homebrew? If you're starting from a checkout of bowtie2, and the file path of the binaries are not included in your PATH variable, can you prepared ./ when running the binaries from the checkout directory? Let me know if that helps.

**Comment by aliexclusive** [comment]
Many thanks... It's working now with PATH variable.
