### ISSUE TITLE
Bowtie2 local alignment issue when reference seqs are shorter than 20bp

### ISSUE THREAD

**Issue by zhangqunyuan** [BenLangmead/bowtie2#60]
I am trying Bowtie2 local alignment (bowtie2 --local), to align fastq reads to a set of reference sequences. I have thousands of very short reference sequences (I treat them as many short chromosomes). I observed that bowtie2 --local was not able to align any reads to the reference sequences shorter than 20bp, when it worked fine for those reference sequences above 21bp.  I wonder if there is any solution.

**Comment by aakashsur** [comment]
I believe the seed length is set to 20 so set -L to something smaller, this might cause other issues like non-unique mapping however.

**Comment by ch4rr0** [comment]
I am marking this issue as closed. Please feel free to reopen if you feel that it has not been addressed.
