### ISSUE TITLE
Bioconda not up to date with bowtie2 2.2.9

### ISSUE THREAD

**Issue by davidmartinad200** [BenLangmead/bowtie2#61]
Hello,
To keep me up to date with latest packages i use Bioconda to update all my bioIT packages, which i personally find very useful.
 I just realized that bowtie2 is still in version 2.2.8 in the Bioconda repository where as release 2.2.9 is out since April 2016. 

I´m just wondering is bowtie 2 is not promoted anymore on the Bioconda website and if i should directly download latest releases from your website ?

Thanks

**Comment by ch4rr0** [comment]
Hello @davidmartinad200,

The bowtie2 bioconda recipe has been updated to support our most recent release, v2.3.0.
