### ISSUE TITLE
Mappings Below Minimum Score Output

### ISSUE THREAD

**Issue by DarioS** [BenLangmead/bowtie2#65]
I have found reads in the SAM file with score below the threshold.

The command is

```
bowtie2 -q -N 1 -L 5 -i C,3 --gbar 1 --mp 1,1 --rdg 0,1 --rfg 0,1 --score-min L,-1 --end-to-end --norc -x /home/indexes/libraryA -U CRISPR.fastq --quiet -S CRISPR.sam --un notAligned.fasta
```

I see CIGAR entires like `7M3I4M2I5M` which have a score below -1, if calculated according to the documentation.

**Comment by BenLangmead** [comment]
The specification `--score-min L,-1` is incomplete; it sets only the constant coefficient and not the linear one.  The linear coefficient will remain at its `--end-to-end` default, which is -0.6.  Try `--score-min L,-1,0` instead.

**Comment by DarioS** [comment]
Thank you. I should have used `--score-min C,-1`.
