### ISSUE TITLE
Not multi-threadding during build

### ISSUE THREAD

**Issue by TealFurnholm** [BenLangmead/bowtie2#67]
I am having multi-threadding issues. I'm running this line 
bowtie2-build -f --noref --threads 19 ./Genes.fasta GENESDB
and checked the flux system. 
It indicates that it is NOT using multiple threads (if it were the %CPU would be 1900).

PID     USER    PR  NI    VIRT     RES      SHR  S  %CPU  %MEM     TIME+      COMMAND
24190 tname  20   0    0.140t  0.139t   1392 R   100.0     14.1     368:08.11  bowtie2-build-l

I have a 123GB fasta file of genes, so it can take weeks to finish (I've run it for weeks and flux kills the job before it finishes). It would really help to have it multi-thread on this.

**Comment by ch4rr0** [comment]
What version of Bowtie2 are you using?

**Comment by TealFurnholm** [comment]
Latest one as of November.

Easiest way to reproduce the issue is to get some reads that have polyA/Ts
in them
(eg: AAAAAAAAAAATAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAA)

Then in your reference database put "PolyA" and "PolyT" gene
>PolyA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

Make the reference index, match, then check the -notmatched file for Poly
A/T.
You will see most don't get a match.

You can also make some ribosomal "reads" from E. coli and Staphylococcus
aureus, and see if you match all of them (correctly).

I think the problem comes from none of the RNA-seq related aligners were
designed with microbiomes (10000+ reference genomes with all that gene
redundancy) in mind.

Best,
Teal

**Comment by ch4rr0** [comment]
I might be mistaken, but this does not seem related to the original issue. Our recent release 2.3.0 supports parallel index building. If possible can you give this version a shot?

**Comment by TealFurnholm** [comment]
The original issue is that bowtie2 misses real matches (thus they wind up
in the -notmatched nm.gz).
Based on what I saw with my reads, it was not matching about 30% of the
polyAs, and after checking downstream, it was missing a significant number
of ribosomal reads.
I was mapping to ribosomal reference database and then using notmatched
reads as the ribo-free to match to the real reference database). I was
merely indicating how you could easily reproduce this error, but this is a
MAJOR problem for all of those now starting to do microbiome RNA-seq, where
there will be large numbers of genomes in the reference database, and will
have to use multi-mapping and have to make sure that we aren't losing 30%
of real matches.

FastQ -> map to ribosomal -> get not matched (non-ribo) reads -> map to
protein coding genes

**Comment by BenLangmead** [comment]
It seems you have two issues open (this one and #57) and some of your comments here relate to the other issue.  Do you still have any issues with multithreaded `bowtie2-build` when using bowtie 2 2.3.0?  Note that index building is not totally parallelizable -- there are some serial portions -- so you won't necessarily see full utilization at all times.  Sometimes you will see just 1 thread busy and all others idle.

**Comment by BenLangmead** [comment]
Closing this, as the multithreading issue is due to portions of the code that cannot be fully parallelized.
