### ISSUE TITLE
Was 2.3.0 retagged?

### ISSUE THREAD

**Issue by jonchang** [BenLangmead/bowtie2#68]
Hi, I'm a maintainer for homebrew and looking to get bowtie 2.3.0 packaged. Homebrew/homebrew-science#4753 has a checksum that differs from what I'm currently getting while downloading bowtie. Was version 2.3.0 re-tagged?

```
==> Installing bowtie2 
==> Downloading https://github.com/BenLangmead/bowtie2/archive/v2.3.0.tar.gz
==> Downloading from https://codeload.github.com/BenLangmead/bowtie2/tar.gz/v2.3.0
==> Verifying bowtie2-2.3.0.tar.gz checksum
Error: SHA256 mismatch
Expected: 7ff24321e3e726c4d5f1baa0c46cceeb3611215de5c3bf59abfe89e5046c6628
Actual: 9804fddf36233f3f92c11e2250224de3395790cf35c8280c66387075df078221
```

**Comment by ch4rr0** [comment]
Apologies @jonchang,
Yes It was retagged. I will update the packages today for consistency.
