### ISSUE TITLE
Incorrect Release Date on SourceForge

### ISSUE THREAD

**Issue by DarioS** [BenLangmead/bowtie2#69]
The [SourceForge homepage of Bowtie 2](http://bowtie-bio.sourceforge.net/bowtie2/index.shtml) contains a news item **Version 2.3.0 - Dec 13, 2016**.  **13** should be **31**.

**Comment by BenLangmead** [comment]
The 13th is the date when we first starting uploading the released files, so I think the date as stated is accurate.
