### ISSUE TITLE
Unmapped Reads in SAM File Although Unmapped File Specified

### ISSUE THREAD

**Issue by DarioS** [BenLangmead/bowtie2#70]
Even though I used `--un` and the unaligned FASTA file has numerous entries of unmapped read sequences in it, I still see unmapped reads in the SAM file, such as:

```
M00692:47:000000000-AWB3P:1:1103:21059:10521	4	*	0	0	*	*	0	0	TAACAATGGTCTTGTGCAAAGGACGAAACAGCGGTGCAAGTAGACTCGCTGGT	CC@CCGGECCCCE9F<6<6;<E@FFGECE@-;6@B@FEEFEFFGGGGFGGECC	YT:Z:UU
```

The unaligned read IDs in the FASTA file do not appear in the SAM file and the reads with SAM flag 4 (unmapped) do not appear in the FASTA file of unmapped reads. This should be fixed so that all unmapped reads are written to the FASTA file and none appear in the SAM file.

**Comment by BenLangmead** [comment]
You can use `--no-unal` to suppress SAM records for reads that fail to align
