### ISSUE TITLE
TBB Flags

### ISSUE THREAD

**Issue by max1c** [BenLangmead/bowtie2#71]
What flags is bowtie 2.3.0 using to build with TBB? No matter what flags I set I get:

In file included from bt2_idx.h:42:0,
                 from bt2_build.cpp:27:
blockwise_sa.h:24:21: fatal error: tbb/tbb.h: No such file or directory
compilation terminated.
In file included from ds.h:30:0,
                 from ref_read.h:33,
                 from ref_read.cpp:20:
threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
compilation terminated.
In file included from ds.h:30:0,
                 from edit.h:29,
                 from edit.cpp:21:
threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
compilation terminated.
In file included from bt2_idx.h:42:0,
                 from bt2_idx.cpp:25:
blockwise_sa.h:24:21: fatal error: tbb/tbb.h: No such file or directory
compilation terminated.
In file included from bt2_idx.h:42:0,
                 from bt2_io.cpp:25:
blockwise_sa.h:24:21: fatal error: tbb/tbb.h: No such file or directory
compilation terminated.

Bowtie 1.2.0 doesn't have this issue.

**Comment by guto03** [comment]
I'm having the same problema here...
