### ISSUE TITLE
Incorrect (?) paired end mapping in SAM output?

### ISSUE THREAD

**Issue by azufre451** [BenLangmead/bowtie2#73]
Hello,

I have been using bowtie2 for mapping paired end Illumina reads against contigs which were built using those reads. Indeed, you would expect the (central) mates of the same pair to be on the same contig.

However, when looking at the alignments, specifically the 3rd and 7th fields of the SAM format, i often see cases where the two mates map to different contigs). Moreover, this does not seem to be supported by the alignment itself. I experienced this scenario:

I got one sam-record where read_1 (1st in pair) maps to contig_A, and its mate (2nd in pair) maps to contig_B (according to the 7th field in the SAM record). However, when I look for a sam-record where read_1 (2nd in pair) maps to contig_B, I am unable to find it. 

I am using Bowtie2 like this:
`--end-to-end -a --no-unal -x contigs -1 R1.fastq -2 R2.fastq`

The issue remains with or without the -a option, and was experienced both with local and global alignment. This is an example (files are attached):

**"1st in pair" alignments**

HWI-ST1296:117:C7C6FACXX:7:1102:18725:26702     65      **NODE_168**        3152    255     100M    **NODE_1**  54496   0       [...]    [...]  AS:i:0  XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:100        YS:i:0  YT:Z:DP

i.e. Node 168 (1st in pair) / Node 1 (2nd in pair)

From my understanding, this read is mapping on Node_168 but the SAM record says that its mate aligns on nodes 1. However, there is no "2nd in pair" aligning on Node_1. Instead, the 2nd-in-pair aligns (as expected) on Node 168:

**"2nd in pair" alignments**

HWI-ST1296:117:C7C6FACXX:7:1102:18725:26702     153     **NODE_168**        3292    255     100M    **=**       3292    0       [...]    [...]  AS:i:0  XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:100        YT:Z:UP

i.e. Node 168 (2nd in pair) / Node 168 (1st in pair)

Any idea about why this is happening? Is the information on the 7th field of the SAM format incorrect?

Many thanks for your help,

Moreno

[test_bw2_pairedend.zip](https://github.com/BenLangmead/bowtie2/files/721408/test_bw2_pairedend.zip)

**Comment by ch4rr0** [comment]
Your reads `R1.fq` and `R2.fq` don't line up. Below is the first few lines of each file. The first read in `R1.fq`, `HWI-ST1296:117:C7C6FACXX:7:1103:6048:40838`, should also be the first read in `R2.fq` and so on. Please let me know if that helps.

```
R1.fq
@HWI-ST1296:117:C7C6FACXX:7:1103:6048:40838 1:N:0:TAAGGCGAAGAGTAGA
CCTTTATATTTTTATTTAATGCTATTCTTCTCTACAACTATCATAGGTGCTCTTTTATTGTATTTACCTTTCACTGGTAAAAAGCCAATATCATTTTTAG
+
BBBFFFFFFFFFFIIIIFFIIII<FIIIIIIIIFIIIIIFIIIIIIIFFIIIIIIFIIIIFIIIIIIIIIIIIIIBFFFIFIIIIFFFFFFFFFFFFFFF
@HWI-ST1296:117:C7C6FACXX:7:1102:21227:96888 1:N:0:TAAGGCGAAGAGTAGA
AGTTTGTTGATAAATAAGACCTCTCCATTTTAAATCTTCAATTAATACATTCGTCATTATTATTTCCTCCTATTTATAATTATTTAGTGAATACTTGTTA
+
BBBBBFFFFFFFFFIIFIFFFBFFBBFFFFFFFFI<<FBFF7FBFBFFFFBBBBFBFBFFBFFFBFFBBBBFBIIFBFFFBFBB<<<<<<<BB<<7<<BB
@HWI-ST1296:117:C7C6FACXX:7:1111:8827:21775 1:N:0:TAAGGCGAAGAGTAGA
GTAAAGTTATCTTTTAAAAGCTGTCGTAAGTCTTTCGATAAGTTCGTCATTTCATCAATCGAATCTACTCTTTTTTGATATAACCATTCAAAAATCTGTT

R2.fq
@HWI-ST1296:117:C7C6FACXX:7:1107:10516:96679 2:N:0:TAAGGCGAAGAGTAGA
GGATAGAGATGTCTGAAAACTGAGAAGGAAGCAAAATATTGAGACAGAGTCTCCATCACTTGCATCTGAGTTTTAAGCATAAGACATCACTAGAGGAAAT
+
BB<FB0<<0B<BFF0BB<BBFFF<FFBBB7BBBFFFFIFFB7F7BFBFBFBBFBFFFBF<<<<FFFFFFFFBFFFFF<BFFFB<BBFFBB<7<B<<BB<B
@HWI-ST1296:117:C7C6FACXX:7:1107:4592:63321 2:N:0:TAAGGCGAAGAGTAGA
TTTACTACGATCGTATTTTTCTTTTGCCATTTGAGTAAAAGCCTCCAATAAAATATATTTTATAGATAGACAGTAGGCAATACAGTCTAACTTTCCTTAC
+
BBBFFFFF070BFF<FB7FFFFIIFIBBFFFBFFIBFIIFFFFF0BFIFFFFFFFFFFFFIIIIBFIIIBFFIFFFFFFFFFFFFFFFBBBBFBBBBBBB
@HWI-ST1296:117:C7C6FACXX:7:1106:16348:22864 2:N:0:TAAGGCGAAGAGTAGA
GTCATTATGACATTACTTACTGTAAATCCATTCGATAATGTTGGATTATCAGCCTTAGTTGCAGCAGTACCTATTATTTTATTTTTATTATGCTTAA```
