### ISSUE TITLE
How do I specify mapping criteria of % and read length?

### ISSUE THREAD

**Issue by shimingt** [BenLangmead/bowtie2#74]
Hello there,

How do I specify the mapping criteria of x% match over Y% of the read-length?

What are the kind of options should I put in?

Cheers!

**Comment by BenLangmead** [comment]
There is no way to specify that kind of policy directly.  Your best bet is to craft the policy you need using the ` --ma`, `--mp`, `--np`, `--rdg` and `--rfg` parameters as discussed here: http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#scores-higher-more-similar
