### ISSUE TITLE
Missing --12 input argument for interleaved FASTQ reads

### ISSUE THREAD

**Issue by heuermh** [BenLangmead/bowtie2#75]
We would like to pipe interleaved FASTQ format (paired reads, alternating records) to bowtie2 from Apache Spark and noticed there isn't a `--12 <r>` input argument.

Does bowtie2 attempt to pair the reads specified in the unpaired reads input argument `-U <r>`?  We could use that as a workaround.

Thanks in advance!

**Comment by ch4rr0** [comment]
Bowtie2 does support tab5/6 inputs. If you're able to convert your inputs to any of these formats then you can pass the --tab5/--tab6 option to bowtie to have them processed.

**Comment by heuermh** [comment]
It appears that `-U <r>` considers all reads unpaired, so that won't work for us.

I've never heard of tab5/6 format, will it work to provide a single pipe of paired reads and have them interpreted as such?  It's kind of a pain to do an additional conversion step, and to something that's not a "standard" format.  Interleaved FASTQ is supported by the `--12` input argument in bowtie and many other tools.

**Comment by dnbh** [comment]
In case it might be helpful, I have a small [tab6 executable](https://github.com/dnbh/SimpleUtilities) from one of my projects that I've used.

One would use it in the following way:

```bash
tab6 fq1 fq2 | bowtie2 <lots of options> --tab6 -
```

**Comment by heuermh** [comment]
Thanks for the suggestion, @dnbh.

We're coming from Apache Spark; from an `RDD[AlignmentRecord]` ([RDD](https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.rdd.RDD) of [AlignmentRecord](https://github.com/bigdatagenomics/bdg-formats/blob/master/src/main/resources/avro/bdg.avdl#L95)s) distributed in RAM across a cluster of compute nodes, specifically.  Our [pipe API](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala#L205) only allows for a single stream to external tools so we'd want to do the conversion in Spark before streaming out.

Is there a spec or reference link for tab5/6?  Looks simple enough.

**Comment by BenLangmead** [comment]
It's an undocumented feature, though we have used it for a while (in Hadoop -- probably not a terribly different scenario from yours) and are considering promoting to a supported and documented feature.

`--tab5` is easy to describe.  Each read or pair is on a single line.  An unpaired read line is `[name]\t[seq]\t[qual]\n`.  A paired-end read line is `[name]\t[seq1]\t[qual1]\t[seq2]\t[qual2]\n`.  An input file can be a mix of unpaired and paired-end reads and Bowtie 2 recognizes each according to the number of fields, handling each as it should.

`--tab6` is similar except, for paired-end reads, the second end can have a different name from the first: `[name1]\t[seq1]\t[qual1]\t[name2]\t[seq2]\t[qual2]\n`.

**Comment by BenLangmead** [comment]
The `--12` option in Bowtie is like the `--tab5` option in Bowtie 2.  I don't think Bowtie or Bowtie 2 ever directly supported interleaved FASTQ -- could be misremembering though

**Comment by heuermh** [comment]
You're right :)

"`bowtie` can align paired-end reads when properly paired read files are specified using the `-1` and `-2` options (for pairs of raw, FASTA, or FASTQ read files), or using the `--12` option (for Tab-delimited read files)"
http://bowtie-bio.sourceforge.net/manual.shtml

**Comment by ch4rr0** [comment]
@heuermh - are you compiling bowtie2 from source? If so, I just now committed a change to support interleaved FASTQ files (using the --12 option). If not I could create a patched binary for your convenience. It would be appreciated if you could help test this out.

**Comment by heuermh** [comment]
@ch4rr0 I'm using bowtie2 from homebrew/linuxbrew, but I can certainly test anything by building from source.

Since I misunderstood the intent of `--12` in bowtie (version 1), perhaps the option for interleaved FASTQ in bowtie2 should be something else?

**Comment by BenLangmead** [comment]
I agree, @heuermh.  @ch4rr0: let's give interleaved FASTQ a new parameter name instead of re-using `--12`.  Maybe `-Q`.

**Comment by ch4rr0** [comment]
New parameter, --interleaved, added as of bowtie 2.3.1.

**Comment by heuermh** [comment]
Thank you, @ch4rr0 @BenLangmead!

**Comment by maglau** [comment]
Can --interleaved and -U be used at the same time?

--interleaved xxx_pairs.fastq -q -U xxx_singles.fastq

I tried, but the results indicated that only the paired-end reads file following --interleaved were used. And interesting, bowtie2 thought that they were unpaired.

_37440178 reads; of these:
  37440178 (100.00%) were unpaired; of these:_
