### ISSUE TITLE
Retrieve number of reads 

### ISSUE THREAD

**Issue by sagnikbanerjee15** [BenLangmead/bowtie2#76]
Hello,

I am using bowtie to map singe end reads to a larger group of reads to validate de novo assembling. After completion of each bowtie run, the program outputs a count which basically outlines the number of reads which were unmapped, mapped exactly once and mapped more than once. I wish to obtain that exact count from the bam file which is produced as a result of bowtie run. Also I am unsure as how to read the number of reads which have been aligned 'n' times from the output file.

Thank you.

**Comment by BenLangmead** [comment]
With its default parameters, Bowtie 2 reports 1 alignment per read, even if the read was found to align repetitively.  Repetitively aligned reads have a value in the `XS:i` extra field but, by default, Bowtie 2 does not output the number of alignments found.  (In fact, it doesn't attempt to determine the number of valid alignments.)  If that's something you need from the output of Bowtie 2, consider using the `-k` or `-a` parameters and then counting the number of records per read.
