### ISSUE TITLE
Pointer comparison issue

### ISSUE THREAD

**Issue by outpaddling** [BenLangmead/bowtie2#81]
Clang 4.0 flagged the following error:

```
aligner_result.cpp:1133:10: error: ordered comparison between pointer and zero ('const char *' and 'int')
        if(flag > 0) {
           ~~~~ ^ ~
```
The code:
```
bool AlnFlags::printYF(BTString& o, bool first) const {
        const char *flag = "";
        if     (!lenfilt_) flag = "LN";
        else if(!nfilt_  ) flag = "NS";
        else if(!scfilt_ ) flag = "SC";
        else if(!qcfilt_ ) flag = "QC";
        if(flag > 0) {
                if(!first) o.append('\t');
                o.append("YF:Z:");
                o.append(flag);
                return false;
        }
        return true;
}

```
Looking at the code, I'm not quite sure what this comparison is attempting.  Did you mean to check for a NULL pointer or a nul byte in flag[0]?  As the code sits, flag will always be > 0, since addresses are unsigned and no string constant assigned to it will ever have an address of 0.  I think it should either be 

```
const char *flag = NULL;
if ( flag != NULL )

```
or

```
const char *flag = "";
if (*flag != '\0').

```

**Comment by dnbh** [comment]
I'm surprised it didn't emit a warning saying that it would always evaluate to true, as that comparison can only ever return true. This is a simple mistake of missing a "*" before flag on that line.

**Comment by outpaddling** [comment]
OK, that's what I would have guessed, but I don't like patching based on guesses.  ;-)  Might you want to use != instead of > in case a non-English string might be added in the future?  Signed chars > 127 will be considered negative in an 8-bit charset.
