### ISSUE TITLE
Output Alignments in BAM Format

### ISSUE THREAD

**Issue by DarioS** [BenLangmead/bowtie2#83]
STAR can output alignments as sorted BAM files. Can this convenience also be provided by Bowtie 2?

**Comment by BenLangmead** [comment]
I'm not sure this provides much utility beyond simply piping Bowtie 2's output to `samtools`, as in this command line (taken from http://seqanswers.com/forums/showthread.php?t=29205):

```
bowtie2 -x $your_ref -U $in | samtools view -bSu - | samtools sort - $out
```

Am I wrong?

**Comment by DarioS** [comment]
Yes, that's essentially the same. There's probably not much difference in performance, either, since recent versions of samtools allow parallelised sorting.
