### ISSUE TITLE
First read-name char sometimes omitted for tabbed inputs, 2.3.0 & later

### ISSUE THREAD

**Issue by BenLangmead** [BenLangmead/bowtie2#85]
In `--tab5` mode (and presumably all the tabbed modes), for the first read for all read batches after the first, the first character of read name is omitted in the SAM output.  This is most easily observed with `--reads-per-batch 1`, where only the first read name is presented correctly; all subsequent read names have first character omitted.  This is the case in both Bowtie 2.3.0 and 2.3.1.

**Comment by ch4rr0** [comment]
A fix has been committed to branch v2.3.1.1. I tested on both tab5 and tab6 input. I will however keep this issue open until the changes are merged to master.
