### ISSUE TITLE
MREVERSE flag not set if read doesn't align

### ISSUE THREAD

**Issue by jakewendt** [BenLangmead/bowtie2#88]
It seems that if a read aligns reverse complement, setting REVERSE (16),
the MREVERSE flag (32 or 0x20) is not set for its mate if it does not align.
It only sets if the mate actually does align.
Is this truely the desired result?

For example.

Use a small chunk of hg19 chr1 as the reference.

```
$ cat ref.fa 
>chr
TTCACCATTTTTCTTTTCGTTAACTTGCCGTCAGCCTTTTCTTTGACCTC
TTCTTTCTGTTCATGTGTATTTGCTGTCTCTTAGCCCAGACTTCCCGTGT
CCTTTCCACCGGGCCTTTGAGAGGTCACAGGGTCTTGATGCTGTGGTCTT
CATCTGCAGGTGTCTGACTTCCAGCAACTGCTGGCCTGTGCCAGGGTGCA
AGCTGAGCACTGGAGTGGAGTTTTCCTGTGGAGAGGAGCCATGCCTAGAG
```

```
$ bowtie2-build ref.fa ref
```

Use a small chunk of the reference in reverse complement to align ...

```
$ echo ">query/1" > query_1.fa
$ echo "TTCTTTCTGTTCATGTGTATTTGCTGTCTCTTAGCCCAGACTTCCCGTGTCCTTTCCACCGGGCCTTTGAGAGGTCACAGGGTCTTGATGCTGTGGTCTT" | awk 'BEGIN{comp["A"]="T";comp["T"]="A";comp["C"]="G";comp["G"]="C";}{a=$0;for(i=length(a);i!=0;i--)x=x comp[substr(a,i,1)];print x}' >> query_1.fa
```

```
$ cat query_1.fa 
>query/1
AAGACCACAGCATCAAGACCCTGTGACCTCTCAAAGGCCCGGTGGAAAGG
ACACGGGAAGTCTGGGCTAAGAGACAGCAAATACACATGAACAGAAAGAA
```

Use some random data that won't align as its mate ...

```
$ cat query_2.fa 
>query/2
CAGCGGCCCTGCCTCCTACCCTTGCGCCTCATGACCAGCTTGTTGAAGAG
ATCCGACATCAAGTGCCCACCTTGGCTCGTGGCTCTCACTGCAACGGGAA
```

```
$ bowtie2 -f -x ref -1 query_1.fa -2 query_2.fa 
1 reads; of these:
  1 (100.00%) were paired; of these:
    1 (100.00%) aligned concordantly 0 times
    0 (0.00%) aligned concordantly exactly 1 time
    0 (0.00%) aligned concordantly >1 times
    ----
    1 pairs aligned concordantly 0 times; of these:
      0 (0.00%) aligned discordantly 1 time
    ----
    1 pairs aligned 0 times concordantly or discordantly; of these:
      2 mates make up the pairs; of these:
        1 (50.00%) aligned 0 times
        1 (50.00%) aligned exactly 1 time
        0 (0.00%) aligned >1 times
50.00% overall alignment rate
@HD	VN:1.0	SO:unsorted
@SQ	SN:chr	LN:250
@PG	ID:bowtie2	PN:bowtie2	VN:2.2.9	CL:".local/bin/bowtie2-align-s --wrapper basic-0 -f -x ref -1 query_1.fa -2 query_2.fa"
query	89	chr	51	42	100M	=	51	0	TTCTTTCTGTTCATGTGTATTTGCTGTCTCTTAGCCCAGACTTCCCGTGTCCTTTCCACCGGGCCTTTGAGAGGTCACAGGGTCTTGATGCTGTGGTCTT	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:100	YT:Z:UP
query	133	chr	51	0	*	=	51	0	CAGCGGCCCTGCCTCCTACCCTTGCGCCTCATGACCAGCTTGTTGAAGAGATCCGACATCAAGTGCCCACCTTGGCTCGTGGCTCTCACTGCAACGGGAA	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	YT:Z:UP
```

The aligned read's flags appear correct ...
89 = 64 + 16 + 8 + 1 ( READ1, REVERSE, MUNMAP, PAIRED )

However, its unaligned mates flags are ...
133 = 128 + 4 + 1 (READ2, UNMAP, PAIRED) 

MREVERSE is unset.

**Comment by BenLangmead** [comment]
We should ponder that.  This seems like it has come up before, but I couldn't find it in the GitHub issue archives just now.  I took another look at the SAM spec and it does not seem to take a position either way.  We'll take a look.  Is there a compelling reason to change this in your opinion?

**Comment by jakewendt** [comment]
If I remember correctly, this came up when we were searching and selecting reads where one read would align and its mate would not. When the read that aligned did so forward (ie. not reverse), there was no issue. Both reads were forward in the SAM file preserving direction. However, on the occasion that the read aligned in reverse it is reversed in the SAM file and as the unaligned mate is still forward in the SAM file, the extracted reads were in opposing directions. In order to preserve direction, I was referencing the MREVERSE flag and would then reverse the unaligned read to match the aligned read's direction. That's when I noticed that it was never set and had to analyze them as a pair rather than individually.

**Comment by ch4rr0** [comment]
@jakewendt would you be able to confirm whether this commit addresses the issue?

**Comment by BenLangmead** [comment]
Looks good to me, as long as it passes a simple test to check for regression

**Comment by jakewendt** [comment]
Looks good to me as well. Thank you.
