### ISSUE TITLE
Bowtie2-build fails in legacy mode due to TBB requirements

### ISSUE THREAD

**Issue by FelixKrueger** [BenLangmead/bowtie2#89]
Hi Ben,

We have been getting bug reports that the Bismark genome preparation fails with Bowtie2 v2.3.1. We don't  currently have TBB installed, and it would require rebuilding the entire cluster to get Bowtie2 to work (which is not possible right now). I have thus downloaded the legacy version which seems to work, yet the `bowtie2-build` process still fails to run:

    bowtie2-build: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory

This is what I get for bowtie2-align-s:
```
/bi/apps/bowtie2/2.3.1 $ ldd bowtie2-align-s
        linux-vdso.so.1 =>  (0x00007fffc9dff000)
        libreadline.so.6 => /lib64/libreadline.so.6 (0x000000376c000000)
        libtinfo.so.5 => /lib64/libtinfo.so.5 (0x000000377a800000)
        libz.so.1 => /bi/apps/zlib/1.2.8/lib/libz.so.1 (0x00007f5a1f457000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x000000376b400000)
        libstdc++.so.6 => /bi/apps/gcc/5.2.0/lib64/libstdc++.so.6 (0x00007f5a1f0c9000)
        libm.so.6 => /lib64/libm.so.6 (0x000000376ac00000)
        libgcc_s.so.1 => /bi/apps/gcc/5.2.0/lib64/libgcc_s.so.1 (0x00007f5a1eeb3000)
        libc.so.6 => /lib64/libc.so.6 (0x000000376a800000)
        /lib64/ld-linux-x86-64.so.2 (0x000000376a400000)
```
And here is what I see for `bowtie2-build-s`:
```
/bi/apps/bowtie2/2.3.1 $ ldd bowtie2-build-s
        linux-vdso.so.1 =>  (0x00007ffffe9bc000)
        libreadline.so.6 => /lib64/libreadline.so.6 (0x000000376c000000)
        libtinfo.so.5 => /lib64/libtinfo.so.5 (0x000000377a800000)
        libz.so.1 => /bi/apps/zlib/1.2.8/lib/libz.so.1 (0x00007f5d2034b000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x000000376b400000)
        libtbb.so.2 => not found
        libtbbmalloc_proxy.so.2 => not found
        libstdc++.so.6 => /bi/apps/gcc/5.2.0/lib64/libstdc++.so.6 (0x00007f5d1ffbc000)
        libm.so.6 => /lib64/libm.so.6 (0x000000376ac00000)
        libgcc_s.so.1 => /bi/apps/gcc/5.2.0/lib64/libgcc_s.so.1 (0x00007f5d1fda6000)
        libc.so.6 => /lib64/libc.so.6 (0x000000376a800000)
        /lib64/ld-linux-x86-64.so.2 (0x000000376a400000)

```

Is it a possibility that the wrong binaries were packaged up for the legacy distribution?

Many thanks, Felix

**Comment by ch4rr0** [comment]
Looking into it

**Comment by ch4rr0** [comment]
I uploaded a new legacy package which should resolve the issue.

**Comment by FelixKrueger** [comment]
Thanks for looking into this so quickly! 

I am getting a different error now though:
```
 ldd /bi/apps/bowtie2/2.3.1/bowtie2-build-s
/bi/apps/bowtie2/2.3.1/bowtie2-build-s: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /bi/apps/bowtie2/2.3.1/bowtie2-build-s)
        linux-vdso.so.1 =>  (0x00007fff2d50f000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x000000376b400000)
        libstdc++.so.6 => /bi/apps/gcc/5.2.0/lib64/libstdc++.so.6 (0x00007fc482c3a000)
        libm.so.6 => /lib64/libm.so.6 (0x000000376ac00000)
        libgcc_s.so.1 => /bi/apps/gcc/5.2.0/lib64/libgcc_s.so.1 (0x00007fc482a24000)
        libc.so.6 => /lib64/libc.so.6 (0x000000376a800000)
        /lib64/ld-linux-x86-64.so.2 (0x000000376a400000)
```

```
bowtie2-build --version
bowtie2-build: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by bowtie2-build)
```

Is this something I need to fix on our side? 
Cheers, Felix

**Comment by ch4rr0** [comment]
Your version of GLIBC is too old. You will need to update it before you can proceed.

**Comment by FelixKrueger** [comment]
Hmm, you seem to have changed the GLIBC versions from the previous legacy version (see ldd above) and all other previous versions which will break on all Centos6 and Rocks6 clusters. We could probably find a local work-around but couldn't you compile it with the versions that worked? Thanks, Felix

**Comment by BenLangmead** [comment]
Yes, we discussed this and plan to ensure better glibc compatibility and a stabler build process going forward.  We appreciate your making us aware of it.

**Comment by FelixKrueger** [comment]
Excellent, let me know once you've got a new version available, I'm happy to test it.

**Comment by ch4rr0** [comment]
I have been fiddling with a docker container for building portable binaries. I have not yet figured it all out, but I think this latest package should work in your environment.

**Comment by FelixKrueger** [comment]
Thanks for trying to figure this out, unfortunately the latest package seems to have introduced a new dependency that wasn't present before:

/bi/apps/bowtie2/2.3.1 $ ldd bowtie2-build-s
        linux-vdso.so.1 =>  (0x00007fff05b85000)
        libreadline.so.5 => /opt/rocks/lib/libreadline.so.5 (0x00007f901e5b4000)
        **libtermcap.so.2 => not found**
        libz.so.1 => /bi/apps/zlib/1.2.8/lib/libz.so.1 (0x00007f901e39d000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x000000376b400000)
        libstdc++.so.6 => /bi/apps/gcc/5.2.0/lib64/libstdc++.so.6 (0x00007f901e00f000)
        libm.so.6 => /lib64/libm.so.6 (0x000000376ac00000)
        libgcc_s.so.1 => /bi/apps/gcc/5.2.0/lib64/libgcc_s.so.1 (0x00007f901ddf9000)
        libc.so.6 => /lib64/libc.so.6 (0x000000376a800000)
        /lib64/ld-linux-x86-64.so.2 (0x000000376a400000)

/bi/apps/bowtie2/2.3.1 $ ldd bowtie2-align-s
        linux-vdso.so.1 =>  (0x00007fffd51ce000)
        libreadline.so.5 => /opt/rocks/lib/libreadline.so.5 (0x00007fdaef922000)
        **libtermcap.so.2 => not found**
        libpthread.so.0 => /lib64/libpthread.so.0 (0x000000376b400000)
        libm.so.6 => /lib64/libm.so.6 (0x000000376ac00000)
        libgcc_s.so.1 => /bi/apps/gcc/5.2.0/lib64/libgcc_s.so.1 (0x00007fdaef70a000)
        libc.so.6 => /lib64/libc.so.6 (0x000000376a800000)
        /lib64/ld-linux-x86-64.so.2 (0x000000376a400000)


/bi/apps/bowtie2/2.3.1/bowtie2-align-s: error while loading shared libraries: libtermcap.so.2: cannot open shared object file: No such file or directory
(ERR): Description of arguments failed!
Exiting now ...

**Comment by ch4rr0** [comment]
Uploaded another. libreadline and libtermcap should now be statically linked.

**Comment by FelixKrueger** [comment]
Great stuff, it works fine now! Many thanks, Felix
