### ISSUE TITLE
Get different result with local align

### ISSUE THREAD

**Issue by XINBADA426** [BenLangmead/bowtie2#90]
Dose the size of genome index has an effect on the local align result?
The command like this
```bash
bowtie2 --local -S out.sam -p 4 --mm -x genome -1 ~ -2 ~  
```
Now genome1 is a sequence in genome2, and I use them to build index independent, and use the command up to make align. But the result is the one which use genome2 as reference has a match but the other one dosen't. When I use BWA, both of the two reference get the match.

-----

[fq.zip](https://github.com/BenLangmead/bowtie2/files/872804/fq.zip)
[rovAseg1.zip](https://github.com/BenLangmead/bowtie2/files/872773/rovAseg1.zip)

----

*the genome2 is too big to upload,but the result is the same with useing BWA. The rovAseg1.zip is genome1.*

**Comment by ch4rr0** [comment]
Is there any way you can upload genome2 to dropbox and share the link? I would like to recreate this issue.

**Comment by XINBADA426** [comment]
Here is the [link](ftp://ftp.ncbi.nlm.nih.gov/refseq/release/viral/viral.1.1.genomic.fna.gz) .

**Comment by XINBADA426** [comment]
Below is the link:

**Comment by XINBADA426** [comment]
Below is the link:
ftp://ftp.ncbi.nlm.nih.gov/refseq/release/viral/viral.1.1.genomic.fna.gz

**Comment by BenLangmead** [comment]
This is not unexpected, given that Bowtie 2 uses heuristics.  The heuristics prune the search space, causing Bowtie 2 to miss some alignments.  The pruning effect is more pronounced when the genome is longer and more repetitive.

**Comment by XINBADA426** [comment]
Thanks BenLangmead!!!
