### ISSUE TITLE
Might there be Windows binaries for 2.3.1 or later releases?

### ISSUE THREAD

**Issue by molecules** [BenLangmead/bowtie2#91]
Dear Developers,

Is there going to be a Windows binary distribution for 2.3.1 or later? I personally and professionally use Linux, but at the moment I'm writing up some bioinformatics instructions for people that are using Windows.

Thanks,
Christopher Bottoms
Informatics Research Core Facility
University of Missouri

**Comment by ch4rr0** [comment]
Yes we will continue to support Windows. I am formalizing our Windows build environment, but the binary should be up by tomorrow afternoon.

**Comment by molecules** [comment]
Thanks so much for the work in making the Windows binaries available and for all of your work on bowtie2 itself!

**Comment by ch4rr0** [comment]
The binary will be delayed until tomorrow. I had a few issues getting libraries statically linked. Sorry for the inconvenience.

**Comment by ch4rr0** [comment]
I was able to get past the above issue, but unfortunately ran into another. In 2.3.1 I introduced the  `poll ` system call for monitoring file handles which isn't portable to Windows. I have a release scheduled for the next week or two that includes a fix for this issue.

Is there a reason why you want to use bowtie2 2.3.1? Would 2.3.0 suffice for your work as we do have Windows binaries available for that version?

**Comment by molecules** [comment]
No hurry. We can use older versions in the mean time. Thanks so much for all of your work on this!

**Comment by tmdefreitas** [comment]
Any update on this? I see that 2.3.2 also did not have a windows binary, and was wondering if one could be created.

**Comment by ch4rr0** [comment]
Yes, there will be and they will be out tomorrow.

**Comment by ch4rr0** [comment]
A little bit late but I have uploaded the Windows binary for the legacy build (Bowtie 2 compiled with pthreads). TBB build will probably be uploaded tomorrow.

**Comment by molecules** [comment]
Thanks for the Windows binary. I'm not requesting a TBB build on Windows, myself, so I'm closing this issue. Feel free to reopen it (or open a new one) if a Windows TBB build is a priority for you.
