### ISSUE TITLE
Short reads alignment: 0 mismatch rule not respected

### ISSUE THREAD

**Issue by FlorianThibord** [BenLangmead/bowtie2#92]
Hi,
I'm writing this report because I observed a strange behavior with bowtie2. And I suspect this behavior to affect mostly alignments on references with short sequence.

I'm using Bowtie2 in order to map short reads (between 15 and 28 nt) against mature mirna reference sequences (ranging from 17 to 28nt in length).
I don't want any mismatch to occur in an alignment, and luckily the maximum seed length in bowtie2 is 28 nt, so I can forbid any mismatch in my alignment using the parameters -L 28 (the seed length), -N 0 (the mismatch number within the seed), and --no-1mm-upfront (to forbid any 1mm alignment attempt before trying the multiseed heuristic).

Here is the command I'm using:
`bowtie2 --end-to-end -a -D 20 -R 3 -N 0 --no-1mm-upfront -L 28 -i S,1,0.5 --norc -x mirbase_hsa -q my_trimmed_reads.fq -S out.sam
`
99.9% of aligned reads don't have any mismatchs. But for a few hundreds of them, i can observe mismatchs and insertions! These incriminated reads are 22 to 24 nt long, so the seed should cover the whole sequence and no mismatch should be accepted. Here is an IGV screenshot of such reads mapping with an insertion and a mismatch on a 21 long reference sequence:
[IGV screenshot](http://i65.tinypic.com/2mwdttg.png)

Here is the fastq line for the first read with an insertion and a mismatch (all reads with that pattern look the same):
```
@NS500388:284:HMVTJBGXY:1:11103:12180:4814 1:N:0:GAGTGG
TCACAGTGAACCGGTCTCTTTT
+
AAAAAEEEEEEEEEEEEEEEEE
```
And here is the fasta line for the reference sequence:
```
>hsa-miR-128-3p
TCACAGTGAACCGGTCTCTTT
```
As a keen observer would note, the reference sequence match the read, except for 1 'T' missing on the 3' end. So bowtie2 should not allow this alignment, as we are in end-to-end mode.
But it would appear that bowtie2 employs a malicious strategy in order to respect the end-to-end rule, by creating one deletion and a mismatch, thus disrespecting the NO MISMATCH rule.

In local mode, this read would have been accepted, with a 1 nt soft-clip on the right side.

I observed this behavior with other references, and it's always the same pattern: an insertion and a mismatch are created to allow a long read on a shorter reference sequence, even if I specified 0 mismatch allowed in the parameter.

So I'm wondering: Why is this happening? I'm I missing something?

PS: my bowtie2 version is 2.2.4 

**************************** UPDATE ****************************

I kept on with my investigation, and I realized the weird behavior I described can't be observed if the reference file contains only the sequence mentioned previously (hsa-miR-128-3p). If you run Bowtie2 with this sequence only, everything works fine, meaning the read is not mapped (as expected). 
BUT, if you add just one other reference sequence, and this sequence starts with the letter 'T', then Bowtie2 map the read with an insertion and a mismatch.
Then I tried with another reference starting with an 'A', and in this case the read is not mapped. So I guess it has something to do with the fact that all references are concatenated together before mapping.

You can try this at home with the following reference to print in a file named mirbase_hsa.fa:
```
>hsa-miR-128-3p
TCACAGTGAACCGGTCTCTTT
>hsa-test
T

```
And copy the following read to map (the same as before) in a file named my_trimmed_reads.fq:
```
@NS500388:284:HMVTJBGXY:1:11103:12180:4814 1:N:0:GAGTGG
TCACAGTGAACCGGTCTCTTTT
+
AAAAAEEEEEEEEEEEEEEEEE

```
Then you can run the following script:
```
bowtie2-build mirbase_hsa.fa mirbase_hsa
bowtie2 --end-to-end -a -D 20 -R 3 -N 0 --no-1mm-upfront -L 28 -i S,1,0.5 --norc -x mirbase_hsa -q my_trimmed_reads.fq -S out.sam

```
And you should see that the read is mapping when it should not. You can also try to change the following ref (miR-test) and make it start with an 'A' instead of a 'T' and you should see that the read is not mapping. 

My guess is that when a read is aligns (with no mismatch) on two references (concatenated), a strategy is employed to keep that alignment on the reference with most bases aligned, by creating insertions and mismatchs, thus disregarding the rules set as parameters.

Is there a way to avoid this behavior?

PS: I tried this with the latest version of Bowtie2 (2.3.1) and this behavior can still be observed.

**Comment by BenLangmead** [comment]
A couple notes:

1. The scoring scheme you're specifying is not actually disallowing alignments with no mismatches.  To accomplish that (in `--end-to-end` mode), specify this option: `--score-min C,0,0`.  That says to disallow any mismatches and gaps
2. Bowtie (not Bowtie 2) is probably a better tool for what you're trying to do.

I see why the behavior you describe is not what you expected, but that's mostly explained by the fact that you're trying to affect Bowtie 2's behavior purely by modifying how it does the seed alignment step.  You need to change to scoring scheme if you'd like to modify how Bowtie 2 does the dynamic programming step -- which is the important one to tackle.

**Comment by FlorianThibord** [comment]
Thank you very much for your answer! 

Since MAPQ score was 255 for all my alignments, I didn't try to change the scoring options. But now I realize MAPQ score is not related to Alignment Score (if the read maps uniquely)! And indeed the AS score is lower for these reads with mismatchs and gaps. So the `--score-min` option solves my problem.

PS: I use Bowtie too, and it's by comparing both outputs (Bowtie and Bowtie2) that I found out about these unwanted alignments, and I wanted to understand why.
