### ISSUE TITLE
Is there upper limit of bases to build index?

### ISSUE THREAD

**Issue by FangYangUW** [BenLangmead/bowtie2#98]
To whom it may concern:

I am using Bowtie2 to build index for reference genomes. The file size is 49GB. The job hasn’t been finished after 44 hours. Is there upper limit of bases to build index?

I look forward to your reply. Thanks a lot for your help in advance.

Fang

**Comment by BenLangmead** [comment]
With `bowtie2-build-l`, the upper limit is 2 ^ 64, which is so huge it should never be an issue.

With `bowtie2-build-s`, the upper limit is 2 ^ 32, which -- as you probably already know -- is too small for your reference.

Did this ever complete?  If you share the output you've seen from it so far, we may be able to help diagnose a performance issue.

**Comment by FangYangUW** [comment]
Hi Ben,

Thanks a lot for your help. It is completed.

Regards,

Fang

**Comment by BenLangmead** [comment]
Glad to hear it
